/**
 * Velxio project (`.vlx`) generation.
 *
 * Velxio (https://velxio.dev — source vendored under `external/velxio`,
 * AGPL-3.0) is an open-source multi-board emulator. Its native project format
 * is a single JSON file (`format: "velxio-project"`, `version: 1`) carrying
 * the boards, the source files, the placed components and the wires between
 * them. Its importer (`frontend/src/utils/vlxFile.ts`) reads exactly the shape
 * produced here, so a project generated by this module opens on the canvas
 * ready to compile and run.
 *
 * Three rules this file keeps:
 *
 *   1. It is derived from the SAME Wokwi projection the diagram export uses,
 *      so the simulator, the firmware and the wiring instructions cannot
 *      drift apart. There is no second source of truth.
 *   2. A part Velxio has no verified model for is reported in `unsupported`,
 *      never substituted with a lookalike. A dead part on the canvas is worse
 *      than an honest gap.
 *   3. Every mapping table here has an inverse in `vlx-sync.ts`, which folds
 *      canvas edits back into `diagram.json`. Change one, change the other.
 */

import type { Diagram } from '@/types/diagram';
import type { GeneratedCodeFile } from '@/types/project';

import { toWokwiDiagram, translatePin } from '@/modules/diagram-generator/wokwi';
import {
  BOARD_KIND_BY_CATALOG_ID,
  BOARD_KIND_BY_WOKWI_TYPE,
  CAD_BENCH_PREFIX,
  METADATA_BY_WOKWI_TYPE,
  WOKWI_TYPE_BY_METADATA,
  cadBenchCatalogId,
  cadBenchId,
  isCadBenchComponent,
  refinePart,
  velxioCatalogKeyFor,
} from './velxio-key';

/*
 * Re-exported so the rest of the codebase keeps importing these from the
 * `.vlx` module it already knows. The definitions live in `velxio-key.ts`
 * because `wokwi.ts` needs them too and must not import this file back.
 */
export {
  BOARD_KIND_BY_CATALOG_ID,
  BOARD_KIND_BY_WOKWI_TYPE,
  CAD_BENCH_PREFIX,
  METADATA_BY_WOKWI_TYPE,
  WOKWI_TYPE_BY_METADATA,
  cadBenchCatalogId,
  cadBenchId,
  isCadBenchComponent,
  velxioCatalogKeyFor,
};
export type { VelxioCatalogKey } from './velxio-key';
import { getSeedComponent } from '@/modules/components/catalog';

/* -------------------------------------------------------------------------- */
/* The .vlx shape (mirrors upstream VlxPayload)                               */
/* -------------------------------------------------------------------------- */

export interface VlxBoard {
  id: string;
  name?: string;
  boardKind: string;
  x: number;
  y: number;
  activeFileGroupId: string;
  languageMode?: 'arduino' | 'micropython' | 'espidf';
  serialBaudRate?: number;
  libraries?: string[];
}

export interface VlxComponent {
  id: string;
  metadataId: string;
  x: number;
  y: number;
  properties: Record<string, unknown>;
}

export interface VlxWireEndpoint {
  componentId: string;
  pinName: string;
  x: number;
  y: number;
}

export type VlxSignalType = 'power-vcc' | 'power-gnd' | 'analog' | 'digital' | 'pwm' | 'i2c' | 'spi' | 'usart';

export interface VlxWire {
  id: string;
  start: VlxWireEndpoint;
  end: VlxWireEndpoint;
  waypoints: { x: number; y: number }[];
  color: string;
  signalType?: VlxSignalType;
}

export interface VlxProject {
  format: 'velxio-project';
  version: 1;
  exportedAt: string;
  name: string;
  boards: VlxBoard[];
  fileGroups: Record<string, { name: string; content: string }[]>;
  components: VlxComponent[];
  wires: VlxWire[];
  activeBoardId: string | null;
}

export interface VelxioProjectResult {
  project: VlxProject;
  json: string;
  /** Wokwi part types / nets Velxio has no model for — reported, not faked. */
  unsupported: string[];
  /** Everything the Wokwi projection itself could not represent. */
  warnings: string[];
  /**
   * Instances placed on the canvas as CAD bench parts (see `cadBenchId`).
   * Their shape and pins are real; the emulator has no electrical model for
   * them, so they are inert. Reported so the UI can say exactly that instead
   * of pretending they simulate.
   */
  cadBench: { id: string; catalogId: string; name: string }[];
}


/**
 * Normalise a Wokwi board pin to the pin NAME the Velxio board element exposes.
 *
 * The ESP32 devkit element's pins are `D4`, `D21`, `3V3`, `VIN`, `GND.1`,
 * `GND.2`… while the Wokwi projection emits bare GPIO numbers on AVR boards
 * and `Dnn` on ESP32 boards. Wiring to a pin that does not exist silently
 * drops the wire on import, so the translation happens here, once.
 */
export function velxioBoardPin(pin: string, boardKind: string): string | null {
  const value = pin.trim();
  if (!value) return null;
  const upper = value.toUpperCase();

  const isEsp32 = boardKind.startsWith('esp32');
  if (/^GND(\.\d+)?$/.test(upper)) return isEsp32 ? 'GND.1' : 'GND.1';
  if (/^3(\.3|V3)V?$/.test(upper) || upper === '3V3') return '3V3';
  if (upper === '5V') return isEsp32 ? 'VIN' : '5V';
  if (upper === 'VIN') return 'VIN';
  if (/^A\d+$/.test(upper)) return upper;
  if (/^(VP|VN|EN|RX0|TX0|RX2|TX2|RESET)$/.test(upper)) return upper;

  const gpio = /^(?:GPIO|D)?(\d{1,2})$/.exec(upper);
  if (gpio) {
    const number = gpio[1] as string;
    // AVR elements name their digital pins by bare number; ESP32 uses Dnn.
    return isEsp32 ? `D${number}` : number;
  }
  return null;
}

/** Wire colour + logical signal type, from what the net carries. */
function classifyWire(boardPin: string, partPin: string): { color: string; signalType: VlxSignalType } {
  if (boardPin.startsWith('GND')) return { color: '#3b3b3b', signalType: 'power-gnd' };
  if (boardPin === '3V3' || boardPin === 'VIN' || boardPin === '5V') {
    return { color: '#d32f2f', signalType: 'power-vcc' };
  }
  const pin = partPin.toUpperCase();
  // A part exposing BOTH SDA and SCL is on a bus; a DHT22's "SDA" is its
  // single-wire data line and must not be labelled I²C.
  if (pin === 'SCL') return { color: '#f5a623', signalType: 'i2c' };
  if (/^A\d+$/.test(boardPin)) return { color: '#7ed321', signalType: 'analog' };
  return { color: '#5c9ded', signalType: 'digital' };
}

/**
 * Classify a wire between two peripheral pins (no board net involved).
 *
 * Velxio re-derives signal types from board pin metadata on import, so this is
 * a best-effort colour: a named supply leg is a supply leg, anything else is a
 * signal. A series resistor between a pin and an LED anode has no polarity of
 * its own, and claiming one would colour the canvas wrongly.
 */
function classifyPartWire(fromPin: string, toPin: string): { color: string; signalType: VlxSignalType } {
  const supply = /^(VCC|VDD|V\+|\+|5V|3V3|3V|VIN|V_IN|VBAT|VBUS)$/i;
  const ground = /^(GND|GND\d*|VSS|V-|-|COM)$/i;
  if (supply.test(fromPin) || supply.test(toPin)) return { color: '#d32f2f', signalType: 'power-vcc' };
  if (ground.test(fromPin) || ground.test(toPin)) return { color: '#3b3b3b', signalType: 'power-gnd' };
  return { color: '#5c9ded', signalType: 'digital' };
}

/* -------------------------------------------------------------------------- */
/* Generation                                                                 */
/* -------------------------------------------------------------------------- */

const BOARD_POS = { x: 120, y: 160 };
const PART_COLUMN_X = 660;
/** CAD bench parts hold their own column, to the right of the simulated ones,
 *  so a user can see at a glance which half of the design the emulator can
 *  actually solve. */
const CAD_PART_COLUMN_X = 1180;
const PART_ROW_Y = 60;
const PART_ROW_HEIGHT = 170;
/** Rough pin anchors. Velxio recalculates them from real element geometry on
 *  import; these only keep freshly imported wires from starting at the origin. */
const PIN_OFFSET = { x: 40, y: 30 };

const BOARD_ID = 'board-1';
const FILE_GROUP_ID = 'group-1';

export interface VelxioProjectInput {
  projectName: string;
  diagram: Diagram;
  /** The generated firmware. The entry sketch MUST come first. */
  files: Pick<GeneratedCodeFile, 'path' | 'content'>[];
  entryPoint?: string;
  libraries?: string[];
  /** Overridden in tests so the output is byte-stable. */
  exportedAt?: string;
}

/**
 * Velxio only compiles the files inside the board's file group, and it wants
 * flat names (`sketch.ino`, `config.h`) — a nested `firmware/sketch.ino`
 * breaks the `#include "config.h"` the sketch emits. Flattening here keeps
 * the project self-contained; a name collision after flattening is reported
 * rather than silently dropping a file.
 */
function flattenFiles(files: Pick<GeneratedCodeFile, 'path' | 'content'>[]): {
  group: { name: string; content: string }[];
  collisions: string[];
} {
  const group: { name: string; content: string }[] = [];
  const collisions: string[] = [];
  const seen = new Set<string>();
  for (const file of files) {
    const name = file.path.split('/').pop() ?? file.path;
    if (seen.has(name)) {
      collisions.push(file.path);
      continue;
    }
    seen.add(name);
    group.push({ name, content: file.content });
  }
  return { group, collisions };
}

/** Only sources belong in the compile group — a README would fail the build. */
function isCompilableSource(path: string): boolean {
  return /\.(ino|h|hpp|c|cpp|cc)$/i.test(path);
}

export function generateVelxioProject(input: VelxioProjectInput): VelxioProjectResult {
  const projection = toWokwiDiagram(input.diagram);
  const wokwi = projection.diagram;
  const unsupported: string[] = [];

  const boardPart = wokwi.parts.find((part) => BOARD_KIND_BY_WOKWI_TYPE[part.type] !== undefined);
  const diagramController = input.diagram.components.find((component) => component.category === 'microcontroller');
  const kindFromDiagram = diagramController ? BOARD_KIND_BY_CATALOG_ID[diagramController.ref] : undefined;
  const boardKind = boardPart
    ? (BOARD_KIND_BY_WOKWI_TYPE[boardPart.type] as string)
    : kindFromDiagram ?? 'arduino-uno';
  if (!boardPart) {
    const skipped = projection.skippedParts.find((part) => part.id === diagramController?.id);
    unsupported.push(
      kindFromDiagram
        ? `board: the controller (${diagramController?.ref}) was not placed in the simulator projection` +
          `${skipped ? ` — ${skipped.reason}` : ''}, so the canvas opens as a ${boardKind} from the diagram itself. ` +
          'The parts are inspectable, but wires to the board and the firmware run are not reproduced.'
        : 'board: no controller in this diagram maps to a Velxio board — the project opens with an Arduino Uno so the ' +
          'parts are still inspectable, but the firmware will not run.',
    );
  }
  const boardPartIds = new Set(
    wokwi.parts.filter((part) => BOARD_KIND_BY_WOKWI_TYPE[part.type] !== undefined).map((part) => part.id),
  );

  /* Components ------------------------------------------------------------- */
  const components: VlxComponent[] = [];
  const positions = new Map<string, { x: number; y: number }>();
  /** Per-part Wokwi pin name → Velxio pin name, where the models disagree. */
  const pinRenames = new Map<string, Record<string, string>>();
  let row = 0;
  for (const part of wokwi.parts) {
    if (boardPartIds.has(part.id)) continue;
    const mapped = METADATA_BY_WOKWI_TYPE[part.type];
    if (!mapped) {
      if (!unsupported.includes(part.type)) unsupported.push(part.type);
      continue;
    }
    const refined = refinePart(part.id, mapped);
    const position = { x: PART_COLUMN_X, y: PART_ROW_Y + row * PART_ROW_HEIGHT };
    row += 1;
    positions.set(part.id, position);
    if (refined.pins) pinRenames.set(part.id, refined.pins);
    components.push({ id: part.id, metadataId: refined.metadataId, ...position, properties: { ...part.attrs } });
  }
  /*
   * CAD bench parts ---------------------------------------------------------
   *
   * Everything the projection could not place as a simulated part gets a
   * second chance here, as long as it is a real electrical part rather than a
   * wiring medium: it is carried onto the canvas with its catalog id as its
   * CAD key, wired like any other part. `component.ref` is the catalog id the
   * CAD layer is indexed by, so the geometry the canvas and the 3D bench draw
   * is the same spec the admin studio previews — no second model to drift.
   *
   * Deliberately excluded:
   *   • the controller (an inert board on the canvas would run nothing, and a
   *     fake board is exactly what Wireup refuses to do — its `unsupported`
   *     report stands);
   *   • wiring media (`metadata.electrical === false`: breadboard, jumpers);
   *   • anything already placed as a simulated part.
   */
  const cadBench: VelxioProjectResult['cadBench'] = [];
  /*
   * The ids the mapping loop above actually PLACED. A part the Wokwi
   * projection carried into `wokwi.parts` but Velxio has no element for (its
   * type is absent from `METADATA_BY_WOKWI_TYPE`, e.g. a motor with no
   * registered element) never became a component — so it must be eligible for
   * the CAD bench tier below instead of vanishing from both.
   */
  const projectedIds = new Set(components.map((component) => component.id));
  const componentById = new Map(input.diagram.components.map((component) => [component.id, component]));
  let cadRow = 0;
  for (const component of input.diagram.components) {
    if (projectedIds.has(component.id)) continue;
    if (!isCadBenchComponent(component)) continue;
    const catalogId = component.ref;
    const position = { x: CAD_PART_COLUMN_X, y: PART_ROW_Y + cadRow * PART_ROW_HEIGHT };
    cadRow += 1;
    positions.set(component.id, position);
    components.push({
      id: component.id,
      metadataId: cadBenchId(catalogId),
      ...position,
      properties: { cadKey: catalogId, ...(component.simulator?.attrs ?? {}) },
    });
    cadBench.push({ id: component.id, catalogId, name: component.name });
  }
  /** Built AFTER the loop above — a Set snapshot taken earlier would be empty. */
  const cadBenchIds = new Set(cadBench.map((entry) => entry.id));
  const cadCatalogIdById = new Map(cadBench.map((entry) => [entry.id, entry.catalogId]));
  const placed = new Set(components.map((component) => component.id));
  const renamePin = (partId: string, pin: string): string => pinRenames.get(partId)?.[pin] ?? pin;

  /* Wires ------------------------------------------------------------------ */
  const wires: VlxWire[] = [];
  wokwi.connections.forEach(([from, to], index) => {
    const [fromId = '', fromPin = ''] = splitEndpoint(from);
    const [toId = '', toPin = ''] = splitEndpoint(to);
    /*
     * A wire with a CAD bench end is rebuilt below straight from the canonical
     * diagram: the Wokwi projection drops it (it cannot place that endpoint),
     * and handling it here would report it as unsupported and then draw it
     * anyway.
     */
    if (cadBenchIds.has(fromId) || cadBenchIds.has(toId)) return;

    // Normalise so the board is always the END of the wire, matching the
    // generator's own convention and making the reverse sync unambiguous.
    const fromIsBoard = boardPartIds.has(fromId);
    const toIsBoard = boardPartIds.has(toId);
    if (fromIsBoard === toIsBoard) {
      /*
       * part↔part: a Velxio wire is just two component pins
       * (`start.componentId/pinName` → `end.componentId/pinName`), so a series
       * resistor feeding an LED anode is fully representable. Dropping these
       * used to lose every current-limiting resistor from the canvas — Velxio's
       * own gallery test flags exactly that as an unprotected LED.
       */
      if (!fromIsBoard && placed.has(fromId) && placed.has(toId)) {
        const fromAnchor = positions.get(fromId) ?? { x: PART_COLUMN_X, y: PART_ROW_Y };
        const toAnchor = positions.get(toId) ?? { x: PART_COLUMN_X, y: PART_ROW_Y };
        const { color, signalType } = classifyPartWire(fromPin, toPin);
        wires.push({
          id: `wire-${index + 1}`,
          start: {
            componentId: fromId,
            pinName: renamePin(fromId, fromPin),
            x: fromAnchor.x + PIN_OFFSET.x,
            y: fromAnchor.y + PIN_OFFSET.y,
          },
          end: {
            componentId: toId,
            pinName: renamePin(toId, toPin),
            x: toAnchor.x + PIN_OFFSET.x,
            y: toAnchor.y + PIN_OFFSET.y + 12,
          },
          waypoints: [],
          color,
          signalType,
        });
        return;
      }
      // board↔board, or a part Velxio has no model for: nothing to draw.
      if (!unsupported.includes(`wire:${from}->${to}`)) unsupported.push(`wire:${from}->${to}`);
      return;
    }
    const partEnd = fromIsBoard ? { id: toId, pin: toPin } : { id: fromId, pin: fromPin };
    const rawBoardPin = fromIsBoard ? fromPin : toPin;
    if (!placed.has(partEnd.id)) return; // its component was skipped — no dangling wire

    const boardPin = velxioBoardPin(rawBoardPin, boardKind);
    if (!boardPin) {
      if (!unsupported.includes(`pin:${rawBoardPin}`)) unsupported.push(`pin:${rawBoardPin}`);
      return;
    }

    const anchor = positions.get(partEnd.id) ?? { x: PART_COLUMN_X, y: PART_ROW_Y };
    const { color, signalType } = classifyWire(boardPin, partEnd.pin);
    wires.push({
      id: `wire-${index + 1}`,
      start: {
        componentId: partEnd.id,
        pinName: renamePin(partEnd.id, partEnd.pin),
        x: anchor.x + PIN_OFFSET.x,
        y: anchor.y + PIN_OFFSET.y,
      },
      end: {
        componentId: BOARD_ID,
        pinName: boardPin,
        x: BOARD_POS.x + PIN_OFFSET.x,
        y: BOARD_POS.y + PIN_OFFSET.y + index * 12,
      },
      waypoints: [],
      color,
      signalType,
    });
  });

  /*
   * CAD-bench wires ---------------------------------------------------------
   *
   * The Wokwi projection drops every connection whose endpoint it cannot
   * place, so wires to a CAD bench part never reach the loop above — a pump
   * would arrive on the canvas with its body and no wires, which is exactly
   * the "half the build is missing" complaint this tier exists to fix.
   *
   * They are therefore rebuilt from the CANONICAL diagram (the same source the
   * projection reads). One deliberate difference: a CAD bench part's pin name
   * is passed through untouched, because those pins ARE the catalog pins (its
   * spec is derived from the same registry entry, and `verify:cad-link` holds
   * its anchors to it). A pin the catalog part does not have is reported
   * instead of exported — Velxio would drop such a wire silently on import.
   */
  const boardInstanceIds = new Set(
    input.diagram.components
      .filter((component) => component.category === 'microcontroller')
      .map((component) => component.id),
  );
  const endpointKey = (componentId: string, pin: string): string => `${componentId}:${pin}`;
  const emitted = new Set(
    wires.map((wire) => `${endpointKey(wire.start.componentId, wire.start.pinName)}>${endpointKey(wire.end.componentId, wire.end.pinName)}`),
  );

  input.diagram.connections.forEach((connection, index) => {
    const touchesCad = cadBenchIds.has(connection.from.component) || cadBenchIds.has(connection.to.component);
    if (!touchesCad) return; // simulated-tier wires were built above

    const fromIsBoard = boardInstanceIds.has(connection.from.component);
    const toIsBoard = boardInstanceIds.has(connection.to.component);

    /*
     * Normalise a CAD bench part's pin to the catalog's canonical spelling
     * (accepting a declared alias), and refuse a pin the part does not have:
     * the canvas resolves pins by name, so an alias or a typo would be dropped
     * silently there — and would never resolve against the 3D anchor either.
     * Both the 2D symbol and the 3D body are keyed by the canonical name.
     */
    const canonicalPin = (componentId: string, pin: string): string | null => {
      const catalogId = cadCatalogIdById.get(componentId);
      if (!catalogId) return pin; // a simulated part: name passes through
      const definition = getSeedComponent(catalogId);
      if (!definition) return pin; // nothing to check it against
      const lower = pin.toLowerCase();
      const match = definition.pins.find(
        (candidate) =>
          candidate.name.toLowerCase() === lower ||
          candidate.aliases?.some((alias) => alias.toLowerCase() === lower),
      );
      return match ? match.name : null;
    };
    const fromPin = canonicalPin(connection.from.component, connection.from.pin);
    const toPin = canonicalPin(connection.to.component, connection.to.pin);
    if (fromPin === null || toPin === null) {
      const missing = fromPin === null ? `${connection.from.component}.${connection.from.pin}` : `${connection.to.component}.${connection.to.pin}`;
      unsupported.push(`pin:${missing} (not present on the catalog part backing its CAD bench model)`);
      return;
    }

    // Translate the board end (if this wire has one) to the emulator's pin
    // vocabulary; part ends keep their catalog names.
    const resolveEnd = (
      componentId: string,
      pin: string,
      isBoard: boolean,
    ): { componentId: string; pinName: string; x: number; y: number } | null => {
      const anchor = positions.get(componentId) ?? { x: CAD_PART_COLUMN_X, y: PART_ROW_Y };
      if (isBoard) {
        const translated = velxioBoardPin(pin, boardKind);
        if (!translated) {
          if (!unsupported.includes(`pin:${pin}`)) unsupported.push(`pin:${pin}`);
          return null;
        }
        return {
          componentId: BOARD_ID,
          pinName: translated,
          x: BOARD_POS.x + PIN_OFFSET.x,
          y: BOARD_POS.y + PIN_OFFSET.y + index * 12,
        };
      }
      if (!placed.has(componentId)) {
        unsupported.push(`wire:${connection.from.component}:${connection.from.pin}->${connection.to.component}:${connection.to.pin} (endpoint not placed)`);
        return null;
      }
      if (!cadCatalogIdById.has(componentId)) {
        /*
         * The other end is a SIMULATED part (a pump driven through a MOSFET,
         * say). Its pin must be translated into the simulator element's own
         * vocabulary exactly like the main wire loop does — the CAD part keeps
         * its catalog names, the simulated part does not.
         */
        const simulated = componentById.get(componentId);
        const translated = translatePin(simulated?.simulator?.part, pin);
        if (!translated) {
          unsupported.push(`pin:${componentId}.${pin} has no equivalent on ${simulated?.simulator?.part ?? 'its simulator element'}`);
          return null;
        }
        return {
          componentId,
          pinName: renamePin(componentId, translated),
          x: anchor.x + PIN_OFFSET.x,
          y: anchor.y + PIN_OFFSET.y + index * 12,
        };
      }
      return {
        componentId,
        pinName: pin,
        x: anchor.x + PIN_OFFSET.x,
        y: anchor.y + PIN_OFFSET.y + index * 12,
      };
    };

    const start = resolveEnd(connection.from.component, fromPin, fromIsBoard);
    const end = resolveEnd(connection.to.component, toPin, toIsBoard);
    if (!start || !end) return;
    if (start.componentId === end.componentId) return; // self-connection

    const key = `${endpointKey(start.componentId, start.pinName)}>${endpointKey(end.componentId, end.pinName)}`;
    const reverse = `${endpointKey(end.componentId, end.pinName)}>${endpointKey(start.componentId, start.pinName)}`;
    if (emitted.has(key) || emitted.has(reverse)) return;
    emitted.add(key);

    const { color, signalType } = end.pinName && start.componentId === BOARD_ID
      ? classifyWire(start.pinName, end.pinName)
      : classifyPartWire(start.pinName, end.pinName);
    wires.push({ id: `wire-${wires.length + 1}`, start, end, waypoints: [], color, signalType });
  });

  /* Files ------------------------------------------------------------------ */
  const sources = input.files.filter((file) => isCompilableSource(file.path));
  const entry = input.entryPoint
    ? sources.find((file) => file.path === input.entryPoint)
    : sources.find((file) => file.path.endsWith('.ino'));
  const ordered = entry ? [entry, ...sources.filter((file) => file !== entry)] : sources;
  const { group, collisions } = flattenFiles(ordered);
  for (const collision of collisions) {
    unsupported.push(
      `file:${collision} — two firmware files flatten to the same name inside the Velxio file group; only the first was kept.`,
    );
  }
  if (group.length === 0) {
    unsupported.push('firmware: no compilable source in this build, so the board opens with an empty sketch.');
  }

  const project: VlxProject = {
    format: 'velxio-project',
    version: 1,
    exportedAt: input.exportedAt ?? new Date().toISOString(),
    name: input.projectName,
    boards: [
      {
        id: BOARD_ID,
        name: boardPart?.id ?? 'Controller',
        boardKind,
        x: BOARD_POS.x,
        y: BOARD_POS.y,
        activeFileGroupId: FILE_GROUP_ID,
        languageMode: 'arduino',
        serialBaudRate: 115_200,
        libraries: input.libraries ?? [],
      },
    ],
    fileGroups: { [FILE_GROUP_ID]: group },
    components,
    wires,
    activeBoardId: BOARD_ID,
  };

  return {
    project,
    json: JSON.stringify(project, null, 2),
    unsupported,
    warnings: projection.warnings,
    cadBench,
  };
}

/** `part:PIN` → `[part, PIN]`, tolerating pin names that contain a dot. */
function splitEndpoint(endpoint: string): [string, string] {
  const index = endpoint.indexOf(':');
  if (index < 0) return [endpoint, ''];
  return [endpoint.slice(0, index), endpoint.slice(index + 1)];
}
