/**
 * Velxio project (`.vlx`) generation.
 *
 * Velxio (https://velxio.dev — source vendored under `external/velxio`,
 * AGPL-3.0) is an open-source multi-board emulator. Its native project format
 * is a single JSON file (`format: "velxio-project"`, `version: 1`) carrying
 * the boards, the source files, the placed components and the wires between
 * them. Its importer (`frontend/src/utils/vlxFile.ts`) reads exactly the shape
 * produced here, so a project generated by this module opens on the canvas
 * ready to compile and run.
 *
 * Three rules this file keeps:
 *
 *   1. It is derived from the SAME Wokwi projection the diagram export uses,
 *      so the simulator, the firmware and the wiring instructions cannot
 *      drift apart. There is no second source of truth.
 *   2. A part Velxio has no verified model for is reported in `unsupported`,
 *      never substituted with a lookalike. A dead part on the canvas is worse
 *      than an honest gap.
 *   3. Every mapping table here has an inverse in `vlx-sync.ts`, which folds
 *      canvas edits back into `diagram.json`. Change one, change the other.
 */

import type { Diagram } from '@/types/diagram';
import type { GeneratedCodeFile } from '@/types/project';

import { toWokwiDiagram } from '@/modules/diagram-generator/wokwi';

/* -------------------------------------------------------------------------- */
/* The .vlx shape (mirrors upstream VlxPayload)                               */
/* -------------------------------------------------------------------------- */

export interface VlxBoard {
  id: string;
  name?: string;
  boardKind: string;
  x: number;
  y: number;
  activeFileGroupId: string;
  languageMode?: 'arduino' | 'micropython' | 'espidf';
  serialBaudRate?: number;
  libraries?: string[];
}

export interface VlxComponent {
  id: string;
  metadataId: string;
  x: number;
  y: number;
  properties: Record<string, unknown>;
}

export interface VlxWireEndpoint {
  componentId: string;
  pinName: string;
  x: number;
  y: number;
}

export type VlxSignalType = 'power-vcc' | 'power-gnd' | 'analog' | 'digital' | 'pwm' | 'i2c' | 'spi' | 'usart';

export interface VlxWire {
  id: string;
  start: VlxWireEndpoint;
  end: VlxWireEndpoint;
  waypoints: { x: number; y: number }[];
  color: string;
  signalType?: VlxSignalType;
}

export interface VlxProject {
  format: 'velxio-project';
  version: 1;
  exportedAt: string;
  name: string;
  boards: VlxBoard[];
  fileGroups: Record<string, { name: string; content: string }[]>;
  components: VlxComponent[];
  wires: VlxWire[];
  activeBoardId: string | null;
}

export interface VelxioProjectResult {
  project: VlxProject;
  json: string;
  /** Wokwi part types / nets Velxio has no model for — reported, not faked. */
  unsupported: string[];
  /** Everything the Wokwi projection itself could not represent. */
  warnings: string[];
}

/* -------------------------------------------------------------------------- */
/* Mapping tables                                                             */
/* -------------------------------------------------------------------------- */

/**
 * Wokwi board part type → Velxio `boardKind` (this picks which CPU core
 * emulates the sketch). Only boards present in Velxio's `BoardKind` union are
 * listed; an unlisted board falls back to `arduino-uno` ONLY if it is an AVR
 * part, otherwise the caller is told the board is unsupported.
 */
export const BOARD_KIND_BY_WOKWI_TYPE: Record<string, string> = {
  'wokwi-esp32-devkit-v1': 'esp32',
  'wokwi-esp32-devkit-c-v4': 'esp32-devkit-c-v4',
  'wokwi-esp32-s3-devkitc-1': 'esp32-s3',
  'wokwi-esp32-c3-devkitm-1': 'esp32-c3',
  'wokwi-arduino-uno': 'arduino-uno',
  'wokwi-arduino-nano': 'arduino-nano',
  'wokwi-arduino-mega': 'arduino-mega',
  'wokwi-pi-pico': 'raspberry-pi-pico',
  'wokwi-pi-pico-w': 'pi-pico-w',
  'wokwi-attiny85': 'attiny85',
};

/**
 * Catalog controller id → Velxio `boardKind`.
 *
 * The table above is keyed by Wokwi *element*, which only exists once the
 * diagram projection has placed the board. When the controller is skipped — no
 * simulator part in the catalog, or `supported: false` — that lookup finds
 * nothing, and the exporter used to open an Arduino Uno regardless of what the
 * user actually designed. The diagram still names the controller (`ref`), so
 * fall back to that before falling back to a guess.
 */
const BOARD_KIND_BY_CATALOG_ID: Record<string, string> = {
  'esp32-devkit-v1': 'esp32',
  'arduino-uno-r3': 'arduino-uno',
  'arduino-nano': 'arduino-nano',
};

/**
 * Wokwi part type → Velxio component `metadataId`.
 *
 * Velxio's catalog (`external/velxio/frontend/public/components-metadata.json`,
 * 156 parts) is generated from wokwi-elements, so the id is usually the element
 * name without the `wokwi-` prefix — with a few upstream renames (`bme280` →
 * `bmp280`, the L293D module → `motor-driver-l293d`). Anything not listed here
 * has no verified Velxio model and is reported instead of guessed.
 *
 * Every value below is machine-verified by `pnpm verify:simulator` against two
 * ground truths in the vendored repo: the metadata file itself (the id must
 * exist AND its tag must be runtime-definable in the pinned build) and the
 * `PartSimulationRegistry` `register(...)` calls in
 * `frontend/src/simulation/parts/` (which decide whether the part actually
 * *behaves*, not just renders). The catalog `simulator.supported` claims are
 * held to the same standard — a `supported: true` without registered behaviour
 * fails the gate.
 */
export const METADATA_BY_WOKWI_TYPE: Record<string, string> = {
  'wokwi-led': 'led',
  'wokwi-rgb-led': 'rgb-led',
  'wokwi-buzzer': 'buzzer',
  'wokwi-pushbutton': 'pushbutton',
  'wokwi-potentiometer': 'potentiometer',
  'wokwi-resistor': 'resistor',
  'wokwi-capacitor': 'capacitor',
  'wokwi-servo': 'servo',
  'wokwi-stepper-motor': 'stepper-motor',
  'wokwi-dht22': 'dht22',
  'wokwi-hc-sr04': 'hc-sr04',
  'wokwi-pir-motion-sensor': 'pir-motion-sensor',
  'wokwi-photoresistor-sensor': 'photoresistor-sensor',
  'wokwi-ntc-temperature-sensor': 'ntc-temperature-sensor',
  'wokwi-mpu6050': 'mpu6050',
  'wokwi-ssd1306': 'ssd1306',
  'wokwi-lcd1602': 'lcd1602',
  'wokwi-lcd2004': 'lcd2004',
  'wokwi-neopixel': 'neopixel',
  'wokwi-neopixel-matrix': 'neopixel-matrix',
  'wokwi-bme280': 'bmp280',
  'wokwi-bmp280': 'bmp280',
  'wokwi-gas-sensor': 'gas-sensor',
  'wokwi-relay-module': 'relay',
  'wokwi-ks2e-m-dc5': 'ks2e-m-dc5',
  'wokwi-membrane-keypad': 'membrane-keypad',
  'wokwi-ir-receiver': 'ir-receiver',
  'wokwi-analog-joystick': 'analog-joystick',
  'wokwi-slide-switch': 'slide-switch',
  'wokwi-slide-potentiometer': 'slide-potentiometer',
  'wokwi-hx711': 'hx711',
  'wokwi-ds1307': 'ds1307',
  'wokwi-a4988': 'a4988',
  'wokwi-microsd-card': 'microsd-card',
  'wokwi-7segment': '7segment',
  'wokwi-led-bar-graph': 'led-bar-graph',
  'wokwi-led-ring': 'led-ring',
  'wokwi-ili9341': 'ili9341',
  'wokwi-breadboard': 'breadboard',
  'wokwi-breadboard-mini': 'breadboard-mini',
  'wokwi-dip-switch-8': 'dip-switch-8',
  'wokwi-tilt-switch': 'tilt-switch',
  'wokwi-ky-040': 'ky-040',
  'wokwi-gps-neo6m': 'gps-neo6m',
  'wokwi-ds3231': 'ds3231',
  // SPICE tier: active semiconductors + the solved power parts.
  'wokwi-diode-1n4007': 'diode-1n4007',
  'wokwi-diode-1n4148': 'diode-1n4148',
  'wokwi-diode-1n5819': 'diode-1n5819',
  'wokwi-bjt-2n2222': 'bjt-2n2222',
  'wokwi-mosfet-2n7000': 'mosfet-2n7000',
  'wokwi-mosfet-irf540': 'mosfet-irf540',
  'wokwi-opto-pc817': 'opto-pc817',
  'wokwi-battery-9v': 'battery-9v',
  'wokwi-reg-7805': 'reg-7805',
  // NOTE deliberately absent: 'wokwi-ds18b20', 'wokwi-l298n'. The pinned
  // Velxio catalog has no model for them, and putting a lookalike on the canvas
  // (an L293D standing in for an L298N, say) would wire the firmware to pins
  // that do not exist on the real part. They stay unsupported.
};

/**
 * Parts whose Velxio model depends on which catalog entry the instance came
 * from, not just on its Wokwi element.
 *
 * Velxio separates a polarised capacitor (`capacitor-electrolytic`, terminals
 * `+` and `\u2212`, and it verifies the polarity against the rail voltage) from a
 * plain one (`capacitor`, terminals `1`/`2`). Both reach the Wokwi projection as
 * `wokwi-capacitor`, so the instance id decides, and the terminals are renamed
 * to the polarised part's own names — Velxio's minus is U+2212, not a hyphen.
 */
const METADATA_REFINEMENTS: {
  matches: RegExp;
  metadataId: string;
  pins?: Record<string, string>;
}[] = [
  { matches: /^capacitor-[\w-]*electrolytic/i, metadataId: 'capacitor-electrolytic', pins: { '1': '+', '2': '\u2212' } },
  // Battery elements name their negative terminal with U+2212 (a true minus),
  // not the hyphen the catalog uses — same treatment as the electrolytic.
  { matches: /^battery-/i, metadataId: '', pins: { '-': '\u2212' } },
];

function refinePart(partId: string, metadataId: string): { metadataId: string; pins?: Record<string, string> } {
  for (const refinement of METADATA_REFINEMENTS) {
    // Match the mapped METADATA ID first, the instance id second: a hand-made
    // instance id ("bat-1") must not silently skip a pin rename that the part
    // type itself calls for. Both current refinements match either form.
    if (refinement.matches.test(metadataId) || refinement.matches.test(partId)) {
      return {
        metadataId: refinement.metadataId || metadataId,
        ...(refinement.pins ? { pins: refinement.pins } : {}),
      };
    }
  }
  return { metadataId };
}

/** The inverse table, used by the canvas→diagram sync. Kept adjacent on purpose. */
export const WOKWI_TYPE_BY_METADATA: Record<string, string> = Object.fromEntries(
  Object.entries(METADATA_BY_WOKWI_TYPE)
    // bmp280/bme280 both map to `bmp280`; the reverse picks the BME280 element,
    // which is the one the Wireup catalog actually ships.
    .filter(([wokwiType]) => wokwiType !== 'wokwi-bmp280')
    .map(([wokwiType, metadataId]) => [metadataId, wokwiType]),
);

/**
 * Normalise a Wokwi board pin to the pin NAME the Velxio board element exposes.
 *
 * The ESP32 devkit element's pins are `D4`, `D21`, `3V3`, `VIN`, `GND.1`,
 * `GND.2`… while the Wokwi projection emits bare GPIO numbers on AVR boards
 * and `Dnn` on ESP32 boards. Wiring to a pin that does not exist silently
 * drops the wire on import, so the translation happens here, once.
 */
export function velxioBoardPin(pin: string, boardKind: string): string | null {
  const value = pin.trim();
  if (!value) return null;
  const upper = value.toUpperCase();

  const isEsp32 = boardKind.startsWith('esp32');
  if (/^GND(\.\d+)?$/.test(upper)) return isEsp32 ? 'GND.1' : 'GND.1';
  if (/^3(\.3|V3)V?$/.test(upper) || upper === '3V3') return '3V3';
  if (upper === '5V') return isEsp32 ? 'VIN' : '5V';
  if (upper === 'VIN') return 'VIN';
  if (/^A\d+$/.test(upper)) return upper;
  if (/^(VP|VN|EN|RX0|TX0|RX2|TX2|RESET)$/.test(upper)) return upper;

  const gpio = /^(?:GPIO|D)?(\d{1,2})$/.exec(upper);
  if (gpio) {
    const number = gpio[1] as string;
    // AVR elements name their digital pins by bare number; ESP32 uses Dnn.
    return isEsp32 ? `D${number}` : number;
  }
  return null;
}

/** Wire colour + logical signal type, from what the net carries. */
function classifyWire(boardPin: string, partPin: string): { color: string; signalType: VlxSignalType } {
  if (boardPin.startsWith('GND')) return { color: '#3b3b3b', signalType: 'power-gnd' };
  if (boardPin === '3V3' || boardPin === 'VIN' || boardPin === '5V') {
    return { color: '#d32f2f', signalType: 'power-vcc' };
  }
  const pin = partPin.toUpperCase();
  // A part exposing BOTH SDA and SCL is on a bus; a DHT22's "SDA" is its
  // single-wire data line and must not be labelled I²C.
  if (pin === 'SCL') return { color: '#f5a623', signalType: 'i2c' };
  if (/^A\d+$/.test(boardPin)) return { color: '#7ed321', signalType: 'analog' };
  return { color: '#5c9ded', signalType: 'digital' };
}

/**
 * Classify a wire between two peripheral pins (no board net involved).
 *
 * Velxio re-derives signal types from board pin metadata on import, so this is
 * a best-effort colour: a named supply leg is a supply leg, anything else is a
 * signal. A series resistor between a pin and an LED anode has no polarity of
 * its own, and claiming one would colour the canvas wrongly.
 */
function classifyPartWire(fromPin: string, toPin: string): { color: string; signalType: VlxSignalType } {
  const supply = /^(VCC|VDD|V\+|\+|5V|3V3|3V|VIN|V_IN|VBAT|VBUS)$/i;
  const ground = /^(GND|GND\d*|VSS|V-|-|COM)$/i;
  if (supply.test(fromPin) || supply.test(toPin)) return { color: '#d32f2f', signalType: 'power-vcc' };
  if (ground.test(fromPin) || ground.test(toPin)) return { color: '#3b3b3b', signalType: 'power-gnd' };
  return { color: '#5c9ded', signalType: 'digital' };
}

/* -------------------------------------------------------------------------- */
/* Generation                                                                 */
/* -------------------------------------------------------------------------- */

const BOARD_POS = { x: 120, y: 160 };
const PART_COLUMN_X = 660;
const PART_ROW_Y = 60;
const PART_ROW_HEIGHT = 170;
/** Rough pin anchors. Velxio recalculates them from real element geometry on
 *  import; these only keep freshly imported wires from starting at the origin. */
const PIN_OFFSET = { x: 40, y: 30 };

const BOARD_ID = 'board-1';
const FILE_GROUP_ID = 'group-1';

export interface VelxioProjectInput {
  projectName: string;
  diagram: Diagram;
  /** The generated firmware. The entry sketch MUST come first. */
  files: Pick<GeneratedCodeFile, 'path' | 'content'>[];
  entryPoint?: string;
  libraries?: string[];
  /** Overridden in tests so the output is byte-stable. */
  exportedAt?: string;
}

/**
 * Velxio only compiles the files inside the board's file group, and it wants
 * flat names (`sketch.ino`, `config.h`) — a nested `firmware/sketch.ino`
 * breaks the `#include "config.h"` the sketch emits. Flattening here keeps
 * the project self-contained; a name collision after flattening is reported
 * rather than silently dropping a file.
 */
function flattenFiles(files: Pick<GeneratedCodeFile, 'path' | 'content'>[]): {
  group: { name: string; content: string }[];
  collisions: string[];
} {
  const group: { name: string; content: string }[] = [];
  const collisions: string[] = [];
  const seen = new Set<string>();
  for (const file of files) {
    const name = file.path.split('/').pop() ?? file.path;
    if (seen.has(name)) {
      collisions.push(file.path);
      continue;
    }
    seen.add(name);
    group.push({ name, content: file.content });
  }
  return { group, collisions };
}

/** Only sources belong in the compile group — a README would fail the build. */
function isCompilableSource(path: string): boolean {
  return /\.(ino|h|hpp|c|cpp|cc)$/i.test(path);
}

export function generateVelxioProject(input: VelxioProjectInput): VelxioProjectResult {
  const projection = toWokwiDiagram(input.diagram);
  const wokwi = projection.diagram;
  const unsupported: string[] = [];

  const boardPart = wokwi.parts.find((part) => BOARD_KIND_BY_WOKWI_TYPE[part.type] !== undefined);
  const diagramController = input.diagram.components.find((component) => component.category === 'microcontroller');
  const kindFromDiagram = diagramController ? BOARD_KIND_BY_CATALOG_ID[diagramController.ref] : undefined;
  const boardKind = boardPart
    ? (BOARD_KIND_BY_WOKWI_TYPE[boardPart.type] as string)
    : kindFromDiagram ?? 'arduino-uno';
  if (!boardPart) {
    const skipped = projection.skippedParts.find((part) => part.id === diagramController?.id);
    unsupported.push(
      kindFromDiagram
        ? `board: the controller (${diagramController?.ref}) was not placed in the simulator projection` +
          `${skipped ? ` — ${skipped.reason}` : ''}, so the canvas opens as a ${boardKind} from the diagram itself. ` +
          'The parts are inspectable, but wires to the board and the firmware run are not reproduced.'
        : 'board: no controller in this diagram maps to a Velxio board — the project opens with an Arduino Uno so the ' +
          'parts are still inspectable, but the firmware will not run.',
    );
  }
  const boardPartIds = new Set(
    wokwi.parts.filter((part) => BOARD_KIND_BY_WOKWI_TYPE[part.type] !== undefined).map((part) => part.id),
  );

  /* Components ------------------------------------------------------------- */
  const components: VlxComponent[] = [];
  const positions = new Map<string, { x: number; y: number }>();
  /** Per-part Wokwi pin name → Velxio pin name, where the models disagree. */
  const pinRenames = new Map<string, Record<string, string>>();
  let row = 0;
  for (const part of wokwi.parts) {
    if (boardPartIds.has(part.id)) continue;
    const mapped = METADATA_BY_WOKWI_TYPE[part.type];
    if (!mapped) {
      if (!unsupported.includes(part.type)) unsupported.push(part.type);
      continue;
    }
    const refined = refinePart(part.id, mapped);
    const position = { x: PART_COLUMN_X, y: PART_ROW_Y + row * PART_ROW_HEIGHT };
    row += 1;
    positions.set(part.id, position);
    if (refined.pins) pinRenames.set(part.id, refined.pins);
    components.push({ id: part.id, metadataId: refined.metadataId, ...position, properties: { ...part.attrs } });
  }
  const placed = new Set(components.map((component) => component.id));
  const renamePin = (partId: string, pin: string): string => pinRenames.get(partId)?.[pin] ?? pin;

  /* Wires ------------------------------------------------------------------ */
  const wires: VlxWire[] = [];
  wokwi.connections.forEach(([from, to], index) => {
    const [fromId = '', fromPin = ''] = splitEndpoint(from);
    const [toId = '', toPin = ''] = splitEndpoint(to);

    // Normalise so the board is always the END of the wire, matching the
    // generator's own convention and making the reverse sync unambiguous.
    const fromIsBoard = boardPartIds.has(fromId);
    const toIsBoard = boardPartIds.has(toId);
    if (fromIsBoard === toIsBoard) {
      /*
       * part↔part: a Velxio wire is just two component pins
       * (`start.componentId/pinName` → `end.componentId/pinName`), so a series
       * resistor feeding an LED anode is fully representable. Dropping these
       * used to lose every current-limiting resistor from the canvas — Velxio's
       * own gallery test flags exactly that as an unprotected LED.
       */
      if (!fromIsBoard && placed.has(fromId) && placed.has(toId)) {
        const fromAnchor = positions.get(fromId) ?? { x: PART_COLUMN_X, y: PART_ROW_Y };
        const toAnchor = positions.get(toId) ?? { x: PART_COLUMN_X, y: PART_ROW_Y };
        const { color, signalType } = classifyPartWire(fromPin, toPin);
        wires.push({
          id: `wire-${index + 1}`,
          start: {
            componentId: fromId,
            pinName: renamePin(fromId, fromPin),
            x: fromAnchor.x + PIN_OFFSET.x,
            y: fromAnchor.y + PIN_OFFSET.y,
          },
          end: {
            componentId: toId,
            pinName: renamePin(toId, toPin),
            x: toAnchor.x + PIN_OFFSET.x,
            y: toAnchor.y + PIN_OFFSET.y + 12,
          },
          waypoints: [],
          color,
          signalType,
        });
        return;
      }
      // board↔board, or a part Velxio has no model for: nothing to draw.
      if (!unsupported.includes(`wire:${from}->${to}`)) unsupported.push(`wire:${from}->${to}`);
      return;
    }
    const partEnd = fromIsBoard ? { id: toId, pin: toPin } : { id: fromId, pin: fromPin };
    const rawBoardPin = fromIsBoard ? fromPin : toPin;
    if (!placed.has(partEnd.id)) return; // its component was skipped — no dangling wire

    const boardPin = velxioBoardPin(rawBoardPin, boardKind);
    if (!boardPin) {
      if (!unsupported.includes(`pin:${rawBoardPin}`)) unsupported.push(`pin:${rawBoardPin}`);
      return;
    }

    const anchor = positions.get(partEnd.id) ?? { x: PART_COLUMN_X, y: PART_ROW_Y };
    const { color, signalType } = classifyWire(boardPin, partEnd.pin);
    wires.push({
      id: `wire-${index + 1}`,
      start: {
        componentId: partEnd.id,
        pinName: renamePin(partEnd.id, partEnd.pin),
        x: anchor.x + PIN_OFFSET.x,
        y: anchor.y + PIN_OFFSET.y,
      },
      end: {
        componentId: BOARD_ID,
        pinName: boardPin,
        x: BOARD_POS.x + PIN_OFFSET.x,
        y: BOARD_POS.y + PIN_OFFSET.y + index * 12,
      },
      waypoints: [],
      color,
      signalType,
    });
  });

  /* Files ------------------------------------------------------------------ */
  const sources = input.files.filter((file) => isCompilableSource(file.path));
  const entry = input.entryPoint
    ? sources.find((file) => file.path === input.entryPoint)
    : sources.find((file) => file.path.endsWith('.ino'));
  const ordered = entry ? [entry, ...sources.filter((file) => file !== entry)] : sources;
  const { group, collisions } = flattenFiles(ordered);
  for (const collision of collisions) {
    unsupported.push(
      `file:${collision} — two firmware files flatten to the same name inside the Velxio file group; only the first was kept.`,
    );
  }
  if (group.length === 0) {
    unsupported.push('firmware: no compilable source in this build, so the board opens with an empty sketch.');
  }

  const project: VlxProject = {
    format: 'velxio-project',
    version: 1,
    exportedAt: input.exportedAt ?? new Date().toISOString(),
    name: input.projectName,
    boards: [
      {
        id: BOARD_ID,
        name: boardPart?.id ?? 'Controller',
        boardKind,
        x: BOARD_POS.x,
        y: BOARD_POS.y,
        activeFileGroupId: FILE_GROUP_ID,
        languageMode: 'arduino',
        serialBaudRate: 115_200,
        libraries: input.libraries ?? [],
      },
    ],
    fileGroups: { [FILE_GROUP_ID]: group },
    components,
    wires,
    activeBoardId: BOARD_ID,
  };

  return {
    project,
    json: JSON.stringify(project, null, 2),
    unsupported,
    warnings: projection.warnings,
  };
}

/** `part:PIN` → `[part, PIN]`, tolerating pin names that contain a dot. */
function splitEndpoint(endpoint: string): [string, string] {
  const index = endpoint.indexOf(':');
  if (index < 0) return [endpoint, ''];
  return [endpoint.slice(0, index), endpoint.slice(index + 1)];
}
