'use client';

/**
 * FIRMWARE — the code for your board. File tabs, highlighted code, copy and
 * download. The "generated by" provenance / pin-map sync / char counts are only
 * shown under "details". Libraries are a clean table here too.
 */

import { useMemo, useState } from 'react';

import type { LibrariesArtifact } from '@/types/project';

import { Badge, Card, CopyButton, DownloadButton, Empty, Loader, SectionTitle } from '../ui';
import { CodeView, languageOf } from '../syntax';
import { useHub } from '../hub-context';

type View = 'firmware' | 'libraries';

export function FirmwarePanel() {
  const { project, running, details } = useHub();
  const code = project?.artifacts.code ?? null;
  const libraries = project?.artifacts.libraries ?? null;
  const files = code?.files ?? [];

  const [activePath, setActivePath] = useState<string | null>(null);
  const [view, setView] = useState<View>('firmware');

  const active = useMemo(() => {
    if (files.length === 0) return null;
    if (activePath) return files.find((file) => file.path === activePath) ?? files[0] ?? null;
    return files.find((file) => file.path === code?.entryPoint) ?? files[0] ?? null;
  }, [activePath, code?.entryPoint, files]);

  if (!code && !libraries) {
    return (
      <Card title="Firmware" wide count="none yet">
        {running ? (
          <Loader label="Writing the firmware from your parts and wiring" />
        ) : (
          <Empty>No firmware was generated for this build.</Empty>
        )}
      </Card>
    );
  }

  const effectiveView: View = code ? view : 'libraries';
  const librariesJson = libraries ? JSON.stringify(libraries, null, 2) : '';

  return (
    <Card
      title="Firmware"
      wide
      count={code ? `${files.length} file${files.length === 1 ? '' : 's'}` : 'libraries'}
      actions={
        <span className="row row--tight">
          <button type="button" className={effectiveView === 'firmware' ? 'filter filter--active' : 'filter'} onClick={() => setView('firmware')} disabled={!code}>
            firmware
          </button>
          <button type="button" className={effectiveView === 'libraries' ? 'filter filter--active' : 'filter'} onClick={() => setView('libraries')} disabled={!libraries}>
            libraries
          </button>
          {effectiveView === 'firmware' && active ? (
            <>
              <CopyButton text={active.content} label="copy" />
              <DownloadButton filename={active.path.replace(/[\\/]/g, '_')} content={active.content} mime="text/plain" label="download" />
            </>
          ) : null}
          {effectiveView === 'libraries' && librariesJson ? <DownloadButton filename="libraries.json" content={librariesJson} label="libraries.json" /> : null}
        </span>
      }
      footer={
        effectiveView === 'firmware' && code ? (
          <span>
            entry point <span className="mono-sm">{code.entryPoint}</span>
            {details ? <span> · pin map sync: {code.pinsSynchronised ? 'yes' : 'no'}</span> : null}
          </span>
        ) : (
          <span>{libraries ? `${libraries.libraries.length} librar${libraries.libraries.length === 1 ? 'y' : 'ies'}` : ''}</span>
        )
      }
    >
      {effectiveView === 'firmware' ? (
        files.length === 0 || !active || !code ? (
          <Empty>The code artifact is empty.</Empty>
        ) : (
          <div className="code">
            <div className="code__tabs" role="tablist">
              {files.map((file) => (
                <button key={file.path} type="button" role="tab" aria-selected={file.path === active.path} className={file.path === active.path ? 'code__tab code__tab--active' : 'code__tab'} onClick={() => setActivePath(file.path)} title={file.purpose}>
                  {file.path}
                </button>
              ))}
            </div>

            <div className="code__toolbar">
              <span className="mono-sm">{active.path}</span>
              <Badge>{active.language || languageOf(active.path)}</Badge>
              {details ? <Badge>generated by {active.generatedBy}</Badge> : null}
              <span style={{ flex: 1 }} />
              {details ? (
                <span>
                  {active.content.split('\n').length} lines · {active.content.length} chars
                </span>
              ) : null}
            </div>

            <CodeView content={active.content} language={active.language || languageOf(active.path)} />

            {active.purpose ? <p className="small muted" style={{ margin: '8px 0 0' }}>{active.purpose}</p> : null}
          </div>
        )
      ) : (
        <LibrariesView libraries={libraries} />
      )}

      {effectiveView === 'firmware' && files.length > 1 ? (
        <>
          <SectionTitle>Files</SectionTitle>
          <div className="table-wrap">
            <table className="table">
              <thead>
                <tr>
                  <th>path</th>
                  <th>language</th>
                  <th>purpose</th>
                </tr>
              </thead>
              <tbody>
                {files.map((file) => (
                  <tr key={file.path}>
                    <td className="mono-sm">{file.path}</td>
                    <td className="mono-sm">{file.language}</td>
                    <td className="small muted">{file.purpose}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      ) : null}
    </Card>
  );
}

function LibrariesView({ libraries }: { libraries: LibrariesArtifact | null }) {
  if (!libraries) return <Empty>No libraries were declared.</Empty>;

  return (
    <>
      {libraries.libraries.length === 0 ? (
        <Empty>The firmware only uses core headers — nothing to install.</Empty>
      ) : (
        <>
          <SectionTitle>Libraries</SectionTitle>
          <div className="table-wrap">
            <table className="table">
              <thead>
                <tr>
                  <th>name</th>
                  <th>import</th>
                  <th>why</th>
                </tr>
              </thead>
              <tbody>
                {libraries.libraries.map((entry) => (
                  <tr key={`${entry.name}-${entry.import}`}>
                    <td>
                      {entry.name}
                      {entry.builtIn ? <Badge tone="ok">built-in</Badge> : null}
                    </td>
                    <td className="mono-sm">{entry.import}</td>
                    <td className="small muted">{entry.purpose}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}

      {libraries.installCommands.length > 0 ? (
        <>
          <SectionTitle>To install</SectionTitle>
          <div className="table-wrap">
            <table className="table table--mono">
              <tbody>
                {libraries.installCommands.map((command) => (
                  <tr key={command}>
                    <td>{command}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      ) : null}
    </>
  );
}
