/** Display seed entries. */

import type { ComponentDefinition } from '@/types/component';

import { def, pin } from './helpers';

export const DISPLAYS: ComponentDefinition[] = [
  def({
    id: 'lcd-1602-i2c',
    name: '1602 LCD with I2C backpack (PCF8574)',
    category: 'display',
    description:
      '16x2 character LCD on a PCF8574 I2C backpack. Only four wires are needed (VCC, GND, SDA, SCL). Default address 0x27 (some backpacks use 0x3F), 5 V supply with a contrast trimmer and backlight jumper.',
    voltage: 5,
    minVoltage: 4.5,
    maxVoltage: 5.5,
    currentRequirements: { typicalMa: 20, maxMa: 40, note: 'Backlight dominates; ~2 mA with the backlight off.' },
    communicationProtocols: ['i2c'],
    pins: [
      pin('VCC', 'power', 'power', { required: true, voltage: 5, aliases: ['+', 'V+'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['-', 'V-'] }),
      pin('SDA', 'i2c', 'bidirectional', { required: true, signal: 'I2C data', aliases: ['D', 'SDI'] }),
      pin('SCL', 'i2c', 'input', { required: true, signal: 'I2C clock', aliases: ['C', 'SCK'] }),
    ],
    libraryRequirements: [
      { name: 'LiquidCrystal I2C', import: 'LiquidCrystal_I2C.h', manager: 'arduino', repository: 'https://github.com/johnrickman/LiquidCrystal_I2C', purpose: 'PCF8574 backpack driver for HD44780 LCDs' },
      { name: 'Wire', import: 'Wire.h', manager: 'arduino', purpose: 'I2C bus', builtIn: true },
    ],
    keywords: ['lcd', '1602', 'display', 'i2c lcd', 'character lcd', 'screen', 'text display'],
    aliases: ['lcd1602', '16x2 lcd', 'lcd display', 'i2c lcd'],
    simulator: { part: 'wokwi-lcd1602', supported: true, attrs: {} },
    metadata: { electrical: true, i2cAddress: '0x27', i2cAddressAlt: '0x3F', columns: 16, rows: 2 },
  }),

  def({
    id: 'oled-ssd1306-i2c',
    name: '0.96" SSD1306 OLED display (I2C)',
    category: 'display',
    description:
      '128x64 monochrome OLED driven by an SSD1306 over I2C. Works from 3.3 V or 5 V, draws ~20 mA, and needs only four wires. Default address 0x3C.',
    voltage: 5,
    minVoltage: 3,
    maxVoltage: 5,
    currentRequirements: { typicalMa: 20, maxMa: 25 },
    communicationProtocols: ['i2c'],
    pins: [
      pin('VCC', 'power', 'power', { required: true, voltage: 5, minVoltage: 3, maxVoltage: 5.5, aliases: ['+', 'V+', 'VIN', 'VDD'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['-', 'V-'] }),
      pin('SCL', 'i2c', 'input', { required: true, aliases: ['C', 'D0'] }),
      pin('SDA', 'i2c', 'bidirectional', { required: true, aliases: ['D', 'D1'] }),
    ],
    libraryRequirements: [
      { name: 'Adafruit SSD1306', import: 'Adafruit_SSD1306.h', manager: 'arduino', repository: 'https://github.com/adafruit/Adafruit_SSD1306', purpose: 'SSD1306 OLED driver' },
      { name: 'Adafruit GFX Library', import: 'Adafruit_GFX.h', manager: 'arduino', repository: 'https://github.com/adafruit/Adafruit-GFX-Library', purpose: 'Graphics primitives required by the SSD1306 driver' },
      { name: 'Wire', import: 'Wire.h', manager: 'arduino', purpose: 'I2C bus', builtIn: true },
    ],
    keywords: ['oled', 'ssd1306', 'display', 'i2c display', 'graphics', 'screen'],
    aliases: ['ssd1306', 'oled display', '0.96 oled', 'i2c oled'],
    simulator: { part: 'wokwi-ssd1306', supported: true, attrs: { i2cAddress: '0x3C' }, notes: 'Wokwi pins: DATA (SDA), CLK (SCL), VIN, GND, 3V3.' },
    metadata: { electrical: true, i2cAddress: '0x3C', resolution: '128x64', logicVoltage: 3.3, wideSupplyRange: true, fiveVoltTolerant: true },
  }),

  def({
    id: 'lcd-2004-i2c',
    name: '2004 LCD with I2C backpack (PCF8574)',
    category: 'display',
    description:
      '20x4 character LCD on a PCF8574 I2C backpack — the 16x2 layout with two more lines for menus and telemetry. Four wires only (VCC, GND, SDA, SCL). Default address 0x27 (some backpacks use 0x3F), 5 V supply with contrast trimmer and backlight jumper.',
    voltage: 5,
    minVoltage: 4.5,
    maxVoltage: 5.5,
    currentRequirements: { typicalMa: 25, maxMa: 50, note: 'Backlight dominates; ~2-3 mA with the backlight off.' },
    communicationProtocols: ['i2c'],
    pins: [
      pin('VCC', 'power', 'power', { required: true, voltage: 5, aliases: ['+', 'V+'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['-', 'V-'] }),
      pin('SDA', 'i2c', 'bidirectional', { required: true, signal: 'I2C data', aliases: ['D', 'SDI'] }),
      pin('SCL', 'i2c', 'input', { required: true, signal: 'I2C clock', aliases: ['C', 'SCK'] }),
    ],
    libraryRequirements: [
      { name: 'LiquidCrystal I2C', import: 'LiquidCrystal_I2C.h', manager: 'arduino', repository: 'https://github.com/johnrickman/LiquidCrystal_I2C', purpose: 'PCF8574 backpack driver for HD44780 LCDs' },
      { name: 'Wire', import: 'Wire.h', manager: 'arduino', purpose: 'I2C bus', builtIn: true },
    ],
    keywords: ['lcd', '2004', '20x4', 'display', 'i2c lcd', 'character lcd', 'screen', 'text display'],
    aliases: ['lcd2004', '20x4 lcd', 'lcd 2004', '4 line lcd', '2004 lcd'],
    simulator: {
      part: 'wokwi-lcd2004',
      supported: true,
      attrs: {},
      notes: 'Velxio implements the full HD44780 protocol over the emulated PCF8574 backpack (20 columns × 4 rows).',
    },
    metadata: { electrical: true, i2cAddress: '0x27', i2cAddressAlt: '0x3F', columns: 20, rows: 4 },
  }),

  def({
    id: 'seven-segment-1digit',
    name: '1-digit 7-segment display (common cathode, 5161AS)',
    category: 'display',
    description:
      'Single-digit 10-pin common-cathode 7-segment LED display (0.36", 5161AS-style). Each segment is an independent LED: drive segments HIGH through 220-330 Ω resistors while holding the common cathode at GND. Multiplex several digits by sharing segment lines and switching each COM in turn.',
    voltage: 2.2,
    minVoltage: 1.8,
    maxVoltage: 2.4,
    currentRequirements: { typicalMa: 80, maxMa: 160, note: '8 segments × 10-20 mA with all segments lit; duty-cycle limits apply when multiplexing.' },
    pins: [
      pin('A', 'digital', 'input', { required: true, signal: 'Segment A (top), through a resistor', aliases: ['SEG_A'] }),
      pin('B', 'digital', 'input', { required: true, signal: 'Segment B (top-right), through a resistor', aliases: ['SEG_B'] }),
      pin('C', 'digital', 'input', { required: true, signal: 'Segment C (bottom-right), through a resistor', aliases: ['SEG_C'] }),
      pin('D', 'digital', 'input', { required: true, signal: 'Segment D (bottom), through a resistor', aliases: ['SEG_D'] }),
      pin('E', 'digital', 'input', { required: true, signal: 'Segment E (bottom-left), through a resistor', aliases: ['SEG_E'] }),
      pin('F', 'digital', 'input', { required: true, signal: 'Segment F (top-left), through a resistor', aliases: ['SEG_F'] }),
      pin('G', 'digital', 'input', { required: true, signal: 'Segment G (middle), through a resistor', aliases: ['SEG_G'] }),
      pin('DP', 'digital', 'input', { required: false, signal: 'Decimal point, through a resistor', aliases: ['DOT', 'SEG_DP'] }),
      pin('COM', 'ground', 'input', { required: true, signal: 'Common cathode (the package exposes two COM pins on one internal net)', aliases: ['COM.1', 'COM.2', 'CATHODE', 'GND'] }),
    ],
    keywords: ['7 segment', 'seven segment', '7-segment', 'display', 'digit', 'led display', 'counter display'],
    aliases: ['7 segment display', 'seven segment', '7seg', 'segment display', '5161as'],
    simulator: {
      part: 'wokwi-7segment',
      supported: true,
      attrs: { digits: '1' },
      notes: 'Velxio lights segments A-G/DP from the wired pins (COM maps to COM.1). Segments left unwired simply stay dark — there is no electrical fault modelling.',
    },
    metadata: { electrical: true, noSupplyPins: true, digits: 1, common: 'cathode', requiresSeriesResistor: true, multiplexable: true },
  }),

  def({
    id: 'led-bar-graph-10',
    name: '10-segment LED bar graph (JL-B10D style)',
    category: 'display',
    description:
      'Ten independent LEDs in a bar package, 20 pins: anodes A1-A10 on one side, cathodes C1-C10 on the other. Each segment needs its own series resistor and its own pin (or a charlieplexed/multiplexed arrangement). The classic VU meter / level indicator: light n segments for a 0-10 reading.',
    voltage: 2.2,
    minVoltage: 1.8,
    maxVoltage: 2.4,
    currentRequirements: { typicalMa: 100, maxMa: 200, note: '10 segments × 10-20 mA when fully lit.' },
    pins: [
      pin('A1', 'digital', 'input', { required: true, signal: 'Segment 1 anode, through a resistor' }),
      pin('C1', 'ground', 'input', { required: true, signal: 'Segment 1 cathode', aliases: ['K1'] }),
      pin('A2', 'digital', 'input', { required: true, signal: 'Segment 2 anode, through a resistor' }),
      pin('C2', 'ground', 'input', { required: true, signal: 'Segment 2 cathode', aliases: ['K2'] }),
      pin('A3', 'digital', 'input', { required: true, signal: 'Segment 3 anode, through a resistor' }),
      pin('C3', 'ground', 'input', { required: true, signal: 'Segment 3 cathode', aliases: ['K3'] }),
      pin('A4', 'digital', 'input', { required: true, signal: 'Segment 4 anode, through a resistor' }),
      pin('C4', 'ground', 'input', { required: true, signal: 'Segment 4 cathode', aliases: ['K4'] }),
      pin('A5', 'digital', 'input', { required: true, signal: 'Segment 5 anode, through a resistor' }),
      pin('C5', 'ground', 'input', { required: true, signal: 'Segment 5 cathode', aliases: ['K5'] }),
      pin('A6', 'digital', 'input', { required: true, signal: 'Segment 6 anode, through a resistor' }),
      pin('C6', 'ground', 'input', { required: true, signal: 'Segment 6 cathode', aliases: ['K6'] }),
      pin('A7', 'digital', 'input', { required: true, signal: 'Segment 7 anode, through a resistor' }),
      pin('C7', 'ground', 'input', { required: true, signal: 'Segment 7 cathode', aliases: ['K7'] }),
      pin('A8', 'digital', 'input', { required: true, signal: 'Segment 8 anode, through a resistor' }),
      pin('C8', 'ground', 'input', { required: true, signal: 'Segment 8 cathode', aliases: ['K8'] }),
      pin('A9', 'digital', 'input', { required: true, signal: 'Segment 9 anode, through a resistor' }),
      pin('C9', 'ground', 'input', { required: true, signal: 'Segment 9 cathode', aliases: ['K9'] }),
      pin('A10', 'digital', 'input', { required: true, signal: 'Segment 10 anode, through a resistor' }),
      pin('C10', 'ground', 'input', { required: true, signal: 'Segment 10 cathode', aliases: ['K10'] }),
    ],
    keywords: ['led bar', 'bar graph', 'voltage indicator', 'vu meter', 'level meter', 'segment display', 'bargraph'],
    aliases: ['led bar graph', 'bar graph', '10 segment led', 'vu meter', 'level indicator'],
    simulator: {
      part: 'wokwi-led-bar-graph',
      supported: true,
      notes: 'Velxio drives all 10 segments independently (each anode works through the resolver), exactly like ten separate LEDs.',
    },
    metadata: { electrical: true, noSupplyPins: true, segments: 10, requiresSeriesResistor: true },
  }),

  def({
    id: 'tft-ili9341-28',
    name: '2.8" ILI9341 SPI TFT display (240x320, ILI9341)',
    category: 'display',
    description:
      '2.4-3.2" colour TFT panels share one driver: an ILI9341 controller over SPI with a 240x320 RGB-565 framebuffer. Wired 4-wire SPI plus D/C (command/data select), CS and RESET; the LED pin is the backlight anode, fed from 3.3 V or a GPIO-controlled transistor — the module carries the current-limiting hardware. Check the silk: many boards label MOSI as SDI and MISO as SDO.',
    voltage: 3.3,
    minVoltage: 3,
    maxVoltage: 5.5,
    currentRequirements: { typicalMa: 80, maxMa: 150, note: 'Backlight dominates (~80 mA at full); panel logic adds 20-60 mA.' },
    communicationProtocols: ['spi'],
    pins: [
      pin('VCC', 'power', 'power', { required: true, voltage: 3.3, minVoltage: 3, maxVoltage: 5.5, signal: 'Module supply (regulated on board)', aliases: ['+', 'VIN'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['-', 'VSS'] }),
      pin('CS', 'control', 'input', { required: true, signal: 'SPI chip select, active LOW', aliases: ['NSS', 'SS'] }),
      pin('RESET', 'control', 'input', { required: true, signal: 'Controller reset, active LOW', aliases: ['RST'] }),
      pin('DC', 'digital', 'input', { required: true, signal: 'Data/command select: LOW = command, HIGH = data', aliases: ['D/C', 'RS', 'A0'] }),
      pin('SDI', 'spi', 'input', { required: true, signal: 'SPI MOSI — data from MCU to the panel', aliases: ['MOSI', 'SDA'] }),
      pin('SCK', 'spi', 'input', { required: true, signal: 'SPI clock', aliases: ['SCLK', 'CLK', 'SCL'] }),
      pin('LED', 'power', 'input', { required: false, signal: 'Backlight anode — module carries the driver; feed from 3.3 V or a switching transistor', aliases: ['BL', 'BACKLIGHT'] }),
      pin('SDO', 'spi', 'output', { required: false, signal: 'SPI MISO — only needed when reading from the controller (most sketch loops never do)', aliases: ['MISO'] }),
    ],
    libraryRequirements: [
      { name: 'Adafruit ILI9341', import: 'Adafruit_ILI9341.h', manager: 'arduino', repository: 'https://github.com/adafruit/Adafruit_ILI9341', purpose: 'ILI9341 SPI driver' },
      { name: 'Adafruit GFX Library', import: 'Adafruit_GFX.h', manager: 'arduino', repository: 'https://github.com/adafruit/Adafruit-GFX-Library', purpose: 'Graphics primitives' },
      { name: 'SPI', import: 'SPI.h', manager: 'arduino', purpose: 'SPI bus', builtIn: true },
    ],
    keywords: ['tft', 'ili9341', 'display', 'spi display', 'colour display', 'color tft', 'lcd', '240x320'],
    aliases: ['ili9341', 'tft display', 'tft lcd', '2.8 tft', '2.4 tft', '240x320 display', 'colour tft'],
    simulator: {
      part: 'wokwi-ili9341',
      supported: true,
      attrs: {},
      notes: 'Velxio decodes the actual SPI command stream (CASET/PASET/RAMWR/MADCTL with D/C LOW=command HIGH=data), so Adafruit_ILI9341 sketches render on the emulated 240x320 panel including rotations 1/3. The capacitive-touch overlay is not modelled.',
    },
    metadata: { electrical: true, resolution: '240x320', logicVoltage: 3.3, colourDepth: 'RGB-565', spiMaxClockHz: 10000000, levelShiftNote: 'Bare panels are 3.3 V only; module regulators tolerate 5 V VCC but keep logic lines 3.3 V unless the board says otherwise.' },
  }),
];
