/** Microcontroller seed entries. */

import type { ComponentDefinition } from '@/types/component';

import { def, pin } from './helpers';

/**
 * ESP32 DevKit V1 (ESP-WROOM-32).
 * GPIO34-GPIO39 are input only (no internal pull-ups, cannot drive outputs).
 * GPIO6-GPIO11 are wired to the SPI flash and must never be used.
 * GPIO0/2/12/15 are strapping pins — usable but must not block boot.
 */
export const MICROCONTROLLERS: ComponentDefinition[] = [
  def({
    id: 'esp32-devkit-v1',
    name: 'ESP32 DevKit V1 (ESP-WROOM-32)',
    category: 'microcontroller',
    description:
      'Dual-core 32-bit MCU with integrated Wi-Fi 802.11 b/g/n and Bluetooth Classic + BLE. 3.3 V logic, 30 usable GPIO, 12-bit ADC, LEDC PWM, capacitive touch. Powered over USB or VIN (5 V) with an on-board 3.3 V regulator.',
    voltage: 3.3,
    minVoltage: 3.0,
    maxVoltage: 3.6,
    currentRequirements: {
      typicalMa: 80,
      maxMa: 500,
      note: 'Radio transmit bursts can reach ~500 mA on the 3.3 V rail; keep a bulk capacitor near the board.',
    },
    communicationProtocols: ['wifi', 'bluetooth', 'ble', 'uart', 'i2c', 'spi', 'i2s', 'adc', 'pwm', 'dac', 'one_wire'],
    compatibleMicrocontrollers: [],
    pins: [
      pin('3V3', 'power', 'power', { required: true, signal: '3.3 V logic supply output', voltage: 3.3, aliases: ['3.3V', 'VCC', '3V'] }),
      pin('VIN', 'power', 'power', { required: false, signal: '5 V unregulated input (USB pass-through)', voltage: 5, aliases: ['5V', 'VUSB'] }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Common ground', aliases: ['VSS'] }),
      pin('EN', 'control', 'input', { signal: 'Chip enable / reset', aliases: ['RESET', 'RST'] }),
      pin('GPIO0', 'digital', 'bidirectional', { signal: 'Strapping pin (boot mode)', aliases: ['0', 'D0'] }),
      pin('GPIO1', 'uart', 'bidirectional', { signal: 'UART0 TX (default Serial)', aliases: ['1', 'TX', 'TX0'] }),
      pin('GPIO2', 'digital', 'bidirectional', { signal: 'Strapping pin, on-board LED on most DevKits', aliases: ['2', 'D2'] }),
      pin('GPIO3', 'uart', 'bidirectional', { signal: 'UART0 RX (default Serial)', aliases: ['3', 'RX', 'RX0'] }),
      pin('GPIO4', 'digital', 'bidirectional', { signal: 'ADC2_CH0 / touch0', aliases: ['4', 'D4', 'A4'] }),
      pin('GPIO5', 'digital', 'bidirectional', { signal: 'VSPI CS default', aliases: ['5', 'D5'] }),
      pin('GPIO12', 'digital', 'bidirectional', { signal: 'Strapping pin (MTDI) — drives flash voltage, avoid as an output at boot', aliases: ['12', 'D12'] }),
      pin('GPIO13', 'digital', 'bidirectional', { signal: 'ADC2_CH4', aliases: ['13', 'D13'] }),
      pin('GPIO14', 'digital', 'bidirectional', { signal: 'VSPI SCK default / ADC2_CH6', aliases: ['14', 'D14'] }),
      pin('GPIO15', 'digital', 'bidirectional', { signal: 'Strapping pin (MTDO)', aliases: ['15', 'D15'] }),
      pin('GPIO16', 'digital', 'bidirectional', { signal: 'UART2 RX (PSRAM shares these on WROVER modules)', aliases: ['16', 'D16'] }),
      pin('GPIO17', 'digital', 'bidirectional', { signal: 'UART2 TX', aliases: ['17', 'D17'] }),
      pin('GPIO18', 'digital', 'bidirectional', { signal: 'VSPI SCK', aliases: ['18', 'D18'] }),
      pin('GPIO19', 'digital', 'bidirectional', { signal: 'VSPI MISO', aliases: ['19', 'D19'] }),
      pin('GPIO21', 'digital', 'bidirectional', { signal: 'Default I2C SDA', aliases: ['21', 'D21', 'SDA'] }),
      pin('GPIO22', 'digital', 'bidirectional', { signal: 'Default I2C SCL', aliases: ['22', 'D22', 'SCL'] }),
      pin('GPIO23', 'digital', 'bidirectional', { signal: 'VSPI MOSI', aliases: ['23', 'D23'] }),
      pin('GPIO25', 'digital', 'bidirectional', { signal: 'ADC2_CH8 / DAC1', aliases: ['25', 'D25', 'A0'] }),
      pin('GPIO26', 'digital', 'bidirectional', { signal: 'ADC2_CH9 / DAC2', aliases: ['26', 'D26', 'A1'] }),
      pin('GPIO27', 'digital', 'bidirectional', { signal: 'ADC2_CH7', aliases: ['27', 'D27', 'A2'] }),
      pin('GPIO32', 'digital', 'bidirectional', { signal: 'ADC1_CH4 (Wi-Fi safe ADC)', aliases: ['32', 'D32', 'A3'] }),
      pin('GPIO33', 'digital', 'bidirectional', { signal: 'ADC1_CH5 (Wi-Fi safe ADC)', aliases: ['33', 'D33', 'A4'] }),
      pin('GPIO34', 'analog', 'input', { signal: 'ADC1_CH6 — INPUT ONLY, no internal pull-up', aliases: ['34', 'A6'] }),
      pin('GPIO35', 'analog', 'input', { signal: 'ADC1_CH7 — INPUT ONLY, no internal pull-up', aliases: ['35', 'A7'] }),
      pin('GPIO36', 'analog', 'input', { signal: 'ADC1_CH0 / VP — INPUT ONLY', aliases: ['36', 'VP', 'A8'] }),
      pin('GPIO39', 'analog', 'input', { signal: 'ADC1_CH3 / VN — INPUT ONLY', aliases: ['39', 'VN', 'A9'] }),
    ],
    libraryRequirements: [
      { name: 'ESP32 Arduino core', import: 'Arduino.h', manager: 'arduino', purpose: 'Board support package for the ESP32', builtIn: true },
    ],
    exampleUsage: [
      'Bluetooth Classic (BluetoothSerial) remote control of a motor driver',
      'Wi-Fi telemetry with HTTP/MQTT publishing',
      'I2C sensor hub at 400 kHz on GPIO21/GPIO22',
    ],
    aliases: ['esp32', 'esp-32', 'esp32 devkit', 'esp32 devkit v1', 'esp32-wroom-32', 'esp32 dev module', 'node32s'],
    keywords: ['esp32', 'wifi', 'wi-fi', 'bluetooth', 'ble', '32-bit', 'microcontroller', 'mcu', 'wroom', 'devkit'],
    simulator: { part: 'wokwi-esp32-devkit-v1', supported: true, attrs: {} },
    metadata: {
      mcuProfileId: 'esp32-devkit-v1',
      logicVoltage: 3.3,
      // The board carries its own USB-fed regulator: for a logic-rail-only
      // design it *is* the power supply, so the planner must not report
      // "no power source" and the validator must not demand a battery.
      usbPowered: true,
      usbVoltage: 5,
      usbMaxCurrentMa: 500,
      onboardRegulator: '3.3 V LDO (AMS1117-3.3), fed from USB/VIN',
      cores: 2,
      clockMhz: 240,
      flashMb: 4,
      adcResolutionBits: 12,
      adcChannels: 'GPIO32-GPIO39 (ADC1 = Wi-Fi safe), GPIO0/2/4/12-15/25-27 (ADC2, blocked while Wi-Fi is active)',
      dacChannels: ['GPIO25', 'GPIO26'],
      inputOnlyPins: ['GPIO34', 'GPIO35', 'GPIO36', 'GPIO39'],
      reservedPins: ['GPIO6', 'GPIO7', 'GPIO8', 'GPIO9', 'GPIO10', 'GPIO11'],
      reservedReason: 'Wired to the SPI flash — using them prevents boot.',
      strappingPins: ['GPIO0', 'GPIO2', 'GPIO12', 'GPIO15'],
      defaultI2c: { sda: 'GPIO21', scl: 'GPIO22' },
      defaultSpi: { mosi: 'GPIO23', miso: 'GPIO19', sck: 'GPIO18', cs: 'GPIO5' },
      defaultUart: [
        { id: 'Serial', tx: 'GPIO1', rx: 'GPIO3', note: 'Used by the USB serial bridge / bootloader logs' },
        { id: 'Serial2', tx: 'GPIO17', rx: 'GPIO16', note: 'Free UART, commonly used for Bluetooth/HMI links' },
      ],
      bluetooth: { classic: true, ble: true, library: 'BluetoothSerial.h (Classic SPP), BLEDevice.h (BLE)' },
      maxGpioSinkMa: 12,
      recommendedGpioSinkMa: 8,
    },
  }),

  def({
    id: 'arduino-uno-r3',
    name: 'Arduino Uno R3',
    category: 'microcontroller',
    description:
      'ATmega328P based board. 5 V logic, 14 digital I/O (6 PWM), 6 analog inputs (10-bit ADC), one hardware UART, 7–12 V VIN with on-board regulators for 5 V and 3.3 V.',
    voltage: 5,
    minVoltage: 4.5,
    maxVoltage: 5.5,
    currentRequirements: {
      typicalMa: 45,
      maxMa: 200,
      note: 'Per-pin absolute maximum 40 mA; 20 mA is the recommended continuous limit.',
    },
    communicationProtocols: ['uart', 'i2c', 'spi', 'adc', 'pwm'],
    pins: [
      pin('D0', 'uart', 'bidirectional', { signal: 'Hardware UART RX — avoid, used by Serial/programming', aliases: ['RX', '0'] }),
      pin('D1', 'uart', 'bidirectional', { signal: 'Hardware UART TX — avoid, used by Serial/programming', aliases: ['TX', '1'] }),
      pin('D2', 'digital', 'bidirectional', { signal: 'External interrupt INT0', aliases: ['2'] }),
      pin('D3', 'pwm', 'bidirectional', { signal: 'PWM / external interrupt INT1', aliases: ['3'] }),
      pin('D4', 'digital', 'bidirectional', { aliases: ['4'] }),
      pin('D5', 'pwm', 'bidirectional', { aliases: ['5'] }),
      pin('D6', 'pwm', 'bidirectional', { aliases: ['6'] }),
      pin('D7', 'digital', 'bidirectional', { aliases: ['7'] }),
      pin('D8', 'digital', 'bidirectional', { aliases: ['8'] }),
      pin('D9', 'pwm', 'bidirectional', { aliases: ['9'] }),
      pin('D10', 'pwm', 'bidirectional', { signal: 'SPI SS / PWM', aliases: ['10', 'SS'] }),
      pin('D11', 'pwm', 'bidirectional', { signal: 'SPI MOSI / PWM', aliases: ['11', 'MOSI'] }),
      pin('D12', 'digital', 'bidirectional', { signal: 'SPI MISO', aliases: ['12', 'MISO'] }),
      pin('D13', 'digital', 'bidirectional', { signal: 'SPI SCK / on-board LED', aliases: ['13', 'SCK'] }),
      pin('A0', 'analog', 'input', { signal: 'ADC0, usable as digital D14', aliases: ['14'] }),
      pin('A1', 'analog', 'input', { signal: 'ADC1, usable as digital D15', aliases: ['15'] }),
      pin('A2', 'analog', 'input', { signal: 'ADC2, usable as digital D16', aliases: ['16'] }),
      pin('A3', 'analog', 'input', { signal: 'ADC3, usable as digital D17', aliases: ['17'] }),
      pin('A4', 'i2c', 'bidirectional', { signal: 'ADC4 / I2C SDA', aliases: ['SDA', '18'] }),
      pin('A5', 'i2c', 'bidirectional', { signal: 'ADC5 / I2C SCL', aliases: ['SCL', '19'] }),
      pin('5V', 'power', 'power', { required: true, voltage: 5, aliases: ['VCC', '5v'] }),
      pin('3V3', 'power', 'power', { voltage: 3.3, aliases: ['3.3V'], description: '50 mA max from the on-board regulator' }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['VSS'] }),
      pin('VIN', 'power', 'power', { voltage: 9, aliases: ['RAW'], signal: '7–12 V unregulated input' }),
      pin('RESET', 'control', 'input', { aliases: ['RST'] }),
    ],
    libraryRequirements: [{ name: 'Arduino AVR core', import: 'Arduino.h', manager: 'arduino', purpose: 'Board support package', builtIn: true }],
    exampleUsage: ['Line follower with IR sensors', '5 V servo and relay control', 'HC-05 Bluetooth control (needs level shifting on RX)'],
    aliases: ['uno', 'arduino uno', 'arduino uno r3', 'atmega328p'],
    keywords: ['arduino', 'uno', 'atmega328p', 'avr', '5v', 'microcontroller', 'mcu'],
    simulator: { part: 'wokwi-arduino-uno', supported: false, notes: 'AVR board — confirm the current simulator part id before targeting Wokwi.' },
    metadata: {
      mcuProfileId: 'arduino-uno-r3',
      logicVoltage: 5,
      usbPowered: true,
      usbVoltage: 5,
      usbMaxCurrentMa: 500,
      onboardRegulator: '5 V from USB, on-board regulator for VIN (7–12 V)',
      mcu: 'ATmega328P',
      clockMhz: 16,
      flashKb: 32,
      sramKb: 2,
      adcResolutionBits: 10,
      pwmPins: ['D3', 'D5', 'D6', 'D9', 'D10', 'D11'],
      interruptPins: ['D2', 'D3'],
      reservedPins: [],
      inputOnlyPins: [],
      defaultI2c: { sda: 'A4', scl: 'A5' },
      defaultSpi: { mosi: 'D11', miso: 'D12', sck: 'D13', cs: 'D10' },
      defaultUart: [{ id: 'Serial', tx: 'D1', rx: 'D0', note: 'Shared with the USB serial bridge' }],
      bluetooth: { classic: false, ble: false },
      maxGpioSinkMa: 40,
      recommendedGpioSinkMa: 20,
    },
  }),

  def({
    id: 'arduino-nano',
    name: 'Arduino Nano',
    category: 'microcontroller',
    description:
      'ATmega328P in a DIP-30 breadboard-friendly form factor. Electrically equivalent to the Uno with 8 analog inputs (A0–A7) and a mini-B / micro-USB connector.',
    voltage: 5,
    minVoltage: 4.5,
    maxVoltage: 5.5,
    currentRequirements: { typicalMa: 40, maxMa: 200, note: 'Per-pin absolute maximum 40 mA; 20 mA recommended.' },
    communicationProtocols: ['uart', 'i2c', 'spi', 'adc', 'pwm'],
    pins: [
      pin('D0', 'uart', 'bidirectional', { signal: 'Hardware UART RX', aliases: ['RX', '0'] }),
      pin('D1', 'uart', 'bidirectional', { signal: 'Hardware UART TX', aliases: ['TX', '1'] }),
      pin('D2', 'digital', 'bidirectional', { signal: 'INT0', aliases: ['2'] }),
      pin('D3', 'pwm', 'bidirectional', { signal: 'INT1 / PWM', aliases: ['3'] }),
      pin('D4', 'digital', 'bidirectional', { aliases: ['4'] }),
      pin('D5', 'pwm', 'bidirectional', { aliases: ['5'] }),
      pin('D6', 'pwm', 'bidirectional', { aliases: ['6'] }),
      pin('D7', 'digital', 'bidirectional', { aliases: ['7'] }),
      pin('D8', 'digital', 'bidirectional', { aliases: ['8'] }),
      pin('D9', 'pwm', 'bidirectional', { aliases: ['9'] }),
      pin('D10', 'pwm', 'bidirectional', { signal: 'SPI SS', aliases: ['10'] }),
      pin('D11', 'pwm', 'bidirectional', { signal: 'SPI MOSI', aliases: ['11'] }),
      pin('D12', 'digital', 'bidirectional', { signal: 'SPI MISO', aliases: ['12'] }),
      pin('D13', 'digital', 'bidirectional', { signal: 'SPI SCK / on-board LED', aliases: ['13'] }),
      pin('A0', 'analog', 'input', { aliases: ['14'] }),
      pin('A1', 'analog', 'input', { aliases: ['15'] }),
      pin('A2', 'analog', 'input', { aliases: ['16'] }),
      pin('A3', 'analog', 'input', { aliases: ['17'] }),
      pin('A4', 'i2c', 'bidirectional', { signal: 'I2C SDA', aliases: ['SDA', '18'] }),
      pin('A5', 'i2c', 'bidirectional', { signal: 'I2C SCL', aliases: ['SCL', '19'] }),
      pin('A6', 'analog', 'input', { signal: 'Analog only — cannot be used as digital', aliases: ['20'] }),
      pin('A7', 'analog', 'input', { signal: 'Analog only — cannot be used as digital', aliases: ['21'] }),
      pin('5V', 'power', 'power', { required: true, voltage: 5, aliases: ['VCC'] }),
      pin('3V3', 'power', 'power', { voltage: 3.3, aliases: ['3.3V'] }),
      pin('GND', 'ground', 'ground', { required: true }),
      pin('VIN', 'power', 'power', { voltage: 9, aliases: ['RAW'], signal: '7–12 V unregulated input' }),
      pin('RESET', 'control', 'input', { aliases: ['RST'] }),
    ],
    libraryRequirements: [{ name: 'Arduino AVR core', import: 'Arduino.h', manager: 'arduino', purpose: 'Board support package', builtIn: true }],
    exampleUsage: ['Compact wearable/robot controller', 'Breadboard prototyping of ATmega328P designs'],
    aliases: ['nano', 'arduino nano', 'atmega328 nano'],
    keywords: ['arduino', 'nano', 'atmega328p', 'avr', '5v', 'microcontroller', 'mcu', 'compact'],
    simulator: { part: 'wokwi-arduino-nano', supported: false, notes: 'AVR board — confirm the current simulator part id before targeting Wokwi.' },
    metadata: {
      mcuProfileId: 'arduino-nano',
      logicVoltage: 5,
      mcu: 'ATmega328P',
      clockMhz: 16,
      adcResolutionBits: 10,
      pwmPins: ['D3', 'D5', 'D6', 'D9', 'D10', 'D11'],
      interruptPins: ['D2', 'D3'],
      inputOnlyPins: ['A6', 'A7'],
      reservedPins: [],
      defaultI2c: { sda: 'A4', scl: 'A5' },
      defaultSpi: { mosi: 'D11', miso: 'D12', sck: 'D13', cs: 'D10' },
      defaultUart: [{ id: 'Serial', tx: 'D1', rx: 'D0' }],
      bluetooth: { classic: false, ble: false },
      maxGpioSinkMa: 40,
      recommendedGpioSinkMa: 20,
    },
  }),
];
