/** Microcontroller seed entries. */

import type { ComponentDefinition } from '@/types/component';

import { def, pin } from './helpers';

/**
 * ESP32 DevKit V1 (ESP-WROOM-32).
 * GPIO34-GPIO39 are input only (no internal pull-ups, cannot drive outputs).
 * GPIO6-GPIO11 are wired to the SPI flash and must never be used.
 * GPIO0/2/12/15 are strapping pins — usable but must not block boot.
 */
export const MICROCONTROLLERS: ComponentDefinition[] = [
  def({
    id: 'esp32-devkit-v1',
    name: 'ESP32 DevKit V1 (ESP-WROOM-32)',
    category: 'microcontroller',
    description:
      'Dual-core 32-bit MCU with integrated Wi-Fi 802.11 b/g/n and Bluetooth Classic + BLE. 3.3 V logic, 30 usable GPIO, 12-bit ADC, LEDC PWM, capacitive touch. Powered over USB or VIN (5 V) with an on-board 3.3 V regulator.',
    voltage: 3.3,
    minVoltage: 3.0,
    maxVoltage: 3.6,
    currentRequirements: {
      typicalMa: 80,
      maxMa: 500,
      note: 'Radio transmit bursts can reach ~500 mA on the 3.3 V rail; keep a bulk capacitor near the board.',
    },
    communicationProtocols: ['wifi', 'bluetooth', 'ble', 'uart', 'i2c', 'spi', 'i2s', 'adc', 'pwm', 'dac', 'one_wire'],
    compatibleMicrocontrollers: [],
    pins: [
      pin('3V3', 'power', 'power', { required: true, signal: '3.3 V logic supply output', voltage: 3.3, aliases: ['3.3V', 'VCC', '3V'] }),
      pin('VIN', 'power', 'power', { required: false, signal: '5 V unregulated input (USB pass-through)', voltage: 5, aliases: ['5V', 'VUSB'] }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Common ground', aliases: ['VSS'] }),
      pin('EN', 'control', 'input', { signal: 'Chip enable / reset', aliases: ['RESET', 'RST'] }),
      pin('GPIO0', 'digital', 'bidirectional', { signal: 'Strapping pin (boot mode)', aliases: ['0', 'D0'] }),
      pin('GPIO1', 'uart', 'bidirectional', { signal: 'UART0 TX (default Serial)', aliases: ['1', 'TX', 'TX0'] }),
      pin('GPIO2', 'digital', 'bidirectional', { signal: 'Strapping pin, on-board LED on most DevKits', aliases: ['2', 'D2'] }),
      pin('GPIO3', 'uart', 'bidirectional', { signal: 'UART0 RX (default Serial)', aliases: ['3', 'RX', 'RX0'] }),
      pin('GPIO4', 'digital', 'bidirectional', { signal: 'ADC2_CH0 / touch0', aliases: ['4', 'D4', 'A4'] }),
      pin('GPIO5', 'digital', 'bidirectional', { signal: 'VSPI CS default', aliases: ['5', 'D5'] }),
      pin('GPIO12', 'digital', 'bidirectional', { signal: 'Strapping pin (MTDI) — drives flash voltage, avoid as an output at boot', aliases: ['12', 'D12'] }),
      pin('GPIO13', 'digital', 'bidirectional', { signal: 'ADC2_CH4', aliases: ['13', 'D13'] }),
      pin('GPIO14', 'digital', 'bidirectional', { signal: 'VSPI SCK default / ADC2_CH6', aliases: ['14', 'D14'] }),
      pin('GPIO15', 'digital', 'bidirectional', { signal: 'Strapping pin (MTDO)', aliases: ['15', 'D15'] }),
      pin('GPIO16', 'digital', 'bidirectional', { signal: 'UART2 RX (PSRAM shares these on WROVER modules)', aliases: ['16', 'D16'] }),
      pin('GPIO17', 'digital', 'bidirectional', { signal: 'UART2 TX', aliases: ['17', 'D17'] }),
      pin('GPIO18', 'digital', 'bidirectional', { signal: 'VSPI SCK', aliases: ['18', 'D18'] }),
      pin('GPIO19', 'digital', 'bidirectional', { signal: 'VSPI MISO', aliases: ['19', 'D19'] }),
      pin('GPIO21', 'digital', 'bidirectional', { signal: 'Default I2C SDA', aliases: ['21', 'D21', 'SDA'] }),
      pin('GPIO22', 'digital', 'bidirectional', { signal: 'Default I2C SCL', aliases: ['22', 'D22', 'SCL'] }),
      pin('GPIO23', 'digital', 'bidirectional', { signal: 'VSPI MOSI', aliases: ['23', 'D23'] }),
      pin('GPIO25', 'digital', 'bidirectional', { signal: 'ADC2_CH8 / DAC1', aliases: ['25', 'D25', 'A0'] }),
      pin('GPIO26', 'digital', 'bidirectional', { signal: 'ADC2_CH9 / DAC2', aliases: ['26', 'D26', 'A1'] }),
      pin('GPIO27', 'digital', 'bidirectional', { signal: 'ADC2_CH7', aliases: ['27', 'D27', 'A2'] }),
      pin('GPIO32', 'digital', 'bidirectional', { signal: 'ADC1_CH4 (Wi-Fi safe ADC)', aliases: ['32', 'D32', 'A3'] }),
      pin('GPIO33', 'digital', 'bidirectional', { signal: 'ADC1_CH5 (Wi-Fi safe ADC)', aliases: ['33', 'D33', 'A4'] }),
      pin('GPIO34', 'analog', 'input', { signal: 'ADC1_CH6 — INPUT ONLY, no internal pull-up', aliases: ['34', 'A6'] }),
      pin('GPIO35', 'analog', 'input', { signal: 'ADC1_CH7 — INPUT ONLY, no internal pull-up', aliases: ['35', 'A7'] }),
      pin('GPIO36', 'analog', 'input', { signal: 'ADC1_CH0 / VP — INPUT ONLY', aliases: ['36', 'VP', 'A8'] }),
      pin('GPIO39', 'analog', 'input', { signal: 'ADC1_CH3 / VN — INPUT ONLY', aliases: ['39', 'VN', 'A9'] }),
    ],
    libraryRequirements: [
      { name: 'ESP32 Arduino core', import: 'Arduino.h', manager: 'arduino', purpose: 'Board support package for the ESP32', builtIn: true },
    ],
    exampleUsage: [
      'Bluetooth Classic (BluetoothSerial) remote control of a motor driver',
      'Wi-Fi telemetry with HTTP/MQTT publishing',
      'I2C sensor hub at 400 kHz on GPIO21/GPIO22',
    ],
    aliases: ['esp32', 'esp-32', 'esp32 devkit', 'esp32 devkit v1', 'esp32-wroom-32', 'esp32 dev module', 'node32s'],
    keywords: ['esp32', 'wifi', 'wi-fi', 'bluetooth', 'ble', '32-bit', 'microcontroller', 'mcu', 'wroom', 'devkit'],
    simulator: { part: 'wokwi-esp32-devkit-v1', supported: true, attrs: {} },
    metadata: {
      mcuProfileId: 'esp32-devkit-v1',
      logicVoltage: 3.3,
      // The board carries its own USB-fed regulator: for a logic-rail-only
      // design it *is* the power supply, so the planner must not report
      // "no power source" and the validator must not demand a battery.
      usbPowered: true,
      usbVoltage: 5,
      usbMaxCurrentMa: 500,
      onboardRegulator: '3.3 V LDO (AMS1117-3.3), fed from USB/VIN',
      cores: 2,
      clockMhz: 240,
      flashMb: 4,
      adcResolutionBits: 12,
      adcChannels: 'GPIO32-GPIO39 (ADC1 = Wi-Fi safe), GPIO0/2/4/12-15/25-27 (ADC2, blocked while Wi-Fi is active)',
      dacChannels: ['GPIO25', 'GPIO26'],
      inputOnlyPins: ['GPIO34', 'GPIO35', 'GPIO36', 'GPIO39'],
      reservedPins: ['GPIO6', 'GPIO7', 'GPIO8', 'GPIO9', 'GPIO10', 'GPIO11'],
      reservedReason: 'Wired to the SPI flash — using them prevents boot.',
      strappingPins: ['GPIO0', 'GPIO2', 'GPIO12', 'GPIO15'],
      defaultI2c: { sda: 'GPIO21', scl: 'GPIO22' },
      defaultSpi: { mosi: 'GPIO23', miso: 'GPIO19', sck: 'GPIO18', cs: 'GPIO5' },
      defaultUart: [
        { id: 'Serial', tx: 'GPIO1', rx: 'GPIO3', note: 'Used by the USB serial bridge / bootloader logs' },
        { id: 'Serial2', tx: 'GPIO17', rx: 'GPIO16', note: 'Free UART, commonly used for Bluetooth/HMI links' },
      ],
      bluetooth: { classic: true, ble: true, library: 'BluetoothSerial.h (Classic SPP), BLEDevice.h (BLE)' },
      maxGpioSinkMa: 12,
      recommendedGpioSinkMa: 8,
    },
  }),

  def({
    id: 'arduino-uno-r3',
    name: 'Arduino Uno R3',
    category: 'microcontroller',
    description:
      'ATmega328P based board. 5 V logic, 14 digital I/O (6 PWM), 6 analog inputs (10-bit ADC), one hardware UART, 7–12 V VIN with on-board regulators for 5 V and 3.3 V.',
    voltage: 5,
    minVoltage: 4.5,
    maxVoltage: 5.5,
    currentRequirements: {
      typicalMa: 45,
      maxMa: 200,
      note: 'Per-pin absolute maximum 40 mA; 20 mA is the recommended continuous limit.',
    },
    communicationProtocols: ['uart', 'i2c', 'spi', 'adc', 'pwm'],
    pins: [
      pin('D0', 'uart', 'bidirectional', { signal: 'Hardware UART RX — avoid, used by Serial/programming', aliases: ['RX', '0'] }),
      pin('D1', 'uart', 'bidirectional', { signal: 'Hardware UART TX — avoid, used by Serial/programming', aliases: ['TX', '1'] }),
      pin('D2', 'digital', 'bidirectional', { signal: 'External interrupt INT0', aliases: ['2'] }),
      pin('D3', 'pwm', 'bidirectional', { signal: 'PWM / external interrupt INT1', aliases: ['3'] }),
      pin('D4', 'digital', 'bidirectional', { aliases: ['4'] }),
      pin('D5', 'pwm', 'bidirectional', { aliases: ['5'] }),
      pin('D6', 'pwm', 'bidirectional', { aliases: ['6'] }),
      pin('D7', 'digital', 'bidirectional', { aliases: ['7'] }),
      pin('D8', 'digital', 'bidirectional', { aliases: ['8'] }),
      pin('D9', 'pwm', 'bidirectional', { aliases: ['9'] }),
      pin('D10', 'pwm', 'bidirectional', { signal: 'SPI SS / PWM', aliases: ['10', 'SS'] }),
      pin('D11', 'pwm', 'bidirectional', { signal: 'SPI MOSI / PWM', aliases: ['11', 'MOSI'] }),
      pin('D12', 'digital', 'bidirectional', { signal: 'SPI MISO', aliases: ['12', 'MISO'] }),
      pin('D13', 'digital', 'bidirectional', { signal: 'SPI SCK / on-board LED', aliases: ['13', 'SCK'] }),
      pin('A0', 'analog', 'input', { signal: 'ADC0, usable as digital D14', aliases: ['14'] }),
      pin('A1', 'analog', 'input', { signal: 'ADC1, usable as digital D15', aliases: ['15'] }),
      pin('A2', 'analog', 'input', { signal: 'ADC2, usable as digital D16', aliases: ['16'] }),
      pin('A3', 'analog', 'input', { signal: 'ADC3, usable as digital D17', aliases: ['17'] }),
      pin('A4', 'i2c', 'bidirectional', { signal: 'ADC4 / I2C SDA', aliases: ['SDA', '18'] }),
      pin('A5', 'i2c', 'bidirectional', { signal: 'ADC5 / I2C SCL', aliases: ['SCL', '19'] }),
      pin('5V', 'power', 'power', { required: true, voltage: 5, aliases: ['VCC', '5v'] }),
      pin('3V3', 'power', 'power', { voltage: 3.3, aliases: ['3.3V'], description: '50 mA max from the on-board regulator' }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Common ground — three physically separate pins on the board, all the same net', aliases: ['VSS', 'GND.1', 'GND.2', 'GND.3'] }),
      pin('VIN', 'power', 'power', { voltage: 9, aliases: ['RAW'], signal: '7–12 V unregulated input' }),
      pin('RESET', 'control', 'input', { aliases: ['RST'] }),
      pin('IOREF', 'power', 'output', { voltage: 5, signal: 'Shield logic-level reference (5 V on a classic Uno)' }),
      pin('AREF', 'analog', 'input', { signal: 'External analog reference for the ADC — only drive it after analogReference(EXTERNAL)' }),
    ],
    libraryRequirements: [{ name: 'Arduino AVR core', import: 'Arduino.h', manager: 'arduino', purpose: 'Board support package', builtIn: true }],
    exampleUsage: ['Line follower with IR sensors', '5 V servo and relay control', 'HC-05 Bluetooth control (needs level shifting on RX)'],
    aliases: ['uno', 'arduino uno', 'arduino uno r3', 'atmega328p'],
    keywords: ['arduino', 'uno', 'atmega328p', 'avr', '5v', 'microcontroller', 'mcu'],
    simulator: { part: 'wokwi-arduino-uno', supported: true, notes: 'Wokwi pins: 0-13, A0-A5, 5V, VIN, GND.1/GND.2/GND.3.' },
    metadata: {
      mcuProfileId: 'arduino-uno-r3',
      logicVoltage: 5,
      usbPowered: true,
      usbVoltage: 5,
      usbMaxCurrentMa: 500,
      onboardRegulator: '5 V from USB, on-board regulator for VIN (7–12 V)',
      mcu: 'ATmega328P',
      clockMhz: 16,
      flashKb: 32,
      sramKb: 2,
      adcResolutionBits: 10,
      pwmPins: ['D3', 'D5', 'D6', 'D9', 'D10', 'D11'],
      interruptPins: ['D2', 'D3'],
      reservedPins: [],
      inputOnlyPins: [],
      defaultI2c: { sda: 'A4', scl: 'A5' },
      defaultSpi: { mosi: 'D11', miso: 'D12', sck: 'D13', cs: 'D10' },
      defaultUart: [{ id: 'Serial', tx: 'D1', rx: 'D0', note: 'Shared with the USB serial bridge' }],
      bluetooth: { classic: false, ble: false },
      maxGpioSinkMa: 40,
      recommendedGpioSinkMa: 20,
    },
  }),

  def({
    id: 'arduino-nano',
    name: 'Arduino Nano',
    category: 'microcontroller',
    description:
      'ATmega328P in a DIP-30 breadboard-friendly form factor. Electrically equivalent to the Uno with 8 analog inputs (A0–A7) and a mini-B / micro-USB connector.',
    voltage: 5,
    minVoltage: 4.5,
    maxVoltage: 5.5,
    currentRequirements: { typicalMa: 40, maxMa: 200, note: 'Per-pin absolute maximum 40 mA; 20 mA recommended.' },
    communicationProtocols: ['uart', 'i2c', 'spi', 'adc', 'pwm'],
    pins: [
      pin('D0', 'uart', 'bidirectional', { signal: 'Hardware UART RX', aliases: ['RX', '0'] }),
      pin('D1', 'uart', 'bidirectional', { signal: 'Hardware UART TX', aliases: ['TX', '1'] }),
      pin('D2', 'digital', 'bidirectional', { signal: 'INT0', aliases: ['2'] }),
      pin('D3', 'pwm', 'bidirectional', { signal: 'INT1 / PWM', aliases: ['3'] }),
      pin('D4', 'digital', 'bidirectional', { aliases: ['4'] }),
      pin('D5', 'pwm', 'bidirectional', { aliases: ['5'] }),
      pin('D6', 'pwm', 'bidirectional', { aliases: ['6'] }),
      pin('D7', 'digital', 'bidirectional', { aliases: ['7'] }),
      pin('D8', 'digital', 'bidirectional', { aliases: ['8'] }),
      pin('D9', 'pwm', 'bidirectional', { aliases: ['9'] }),
      pin('D10', 'pwm', 'bidirectional', { signal: 'SPI SS', aliases: ['10'] }),
      pin('D11', 'pwm', 'bidirectional', { signal: 'SPI MOSI', aliases: ['11'] }),
      pin('D12', 'digital', 'bidirectional', { signal: 'SPI MISO', aliases: ['12'] }),
      pin('D13', 'digital', 'bidirectional', { signal: 'SPI SCK / on-board LED', aliases: ['13'] }),
      pin('A0', 'analog', 'input', { aliases: ['14'] }),
      pin('A1', 'analog', 'input', { aliases: ['15'] }),
      pin('A2', 'analog', 'input', { aliases: ['16'] }),
      pin('A3', 'analog', 'input', { aliases: ['17'] }),
      pin('A4', 'i2c', 'bidirectional', { signal: 'I2C SDA', aliases: ['SDA', '18'] }),
      pin('A5', 'i2c', 'bidirectional', { signal: 'I2C SCL', aliases: ['SCL', '19'] }),
      pin('A6', 'analog', 'input', { signal: 'Analog only — cannot be used as digital', aliases: ['20'] }),
      pin('A7', 'analog', 'input', { signal: 'Analog only — cannot be used as digital', aliases: ['21'] }),
      pin('5V', 'power', 'power', { required: true, voltage: 5, aliases: ['VCC'] }),
      pin('3V3', 'power', 'power', { voltage: 3.3, aliases: ['3.3V'] }),
      pin('GND', 'ground', 'ground', { required: true }),
      pin('VIN', 'power', 'power', { voltage: 9, aliases: ['RAW'], signal: '7–12 V unregulated input' }),
      pin('RESET', 'control', 'input', { aliases: ['RST'] }),
    ],
    libraryRequirements: [{ name: 'Arduino AVR core', import: 'Arduino.h', manager: 'arduino', purpose: 'Board support package', builtIn: true }],
    exampleUsage: ['Compact wearable/robot controller', 'Breadboard prototyping of ATmega328P designs'],
    aliases: ['nano', 'arduino nano', 'atmega328 nano'],
    keywords: ['arduino', 'nano', 'atmega328p', 'avr', '5v', 'microcontroller', 'mcu', 'compact'],
    simulator: { part: 'wokwi-arduino-nano', supported: true, notes: 'Wokwi pins: 0-13, A0-A7, 5V, 3.3V, VIN, GND.1/GND.2/GND.3.' },
    metadata: {
      mcuProfileId: 'arduino-nano',
      logicVoltage: 5,
      usbPowered: true,
      usbVoltage: 5,
      usbMaxCurrentMa: 500,
      onboardRegulator: '5 V from mini-USB, on-board regulator for VIN (7–12 V)',
      mcu: 'ATmega328P',
      clockMhz: 16,
      adcResolutionBits: 10,
      pwmPins: ['D3', 'D5', 'D6', 'D9', 'D10', 'D11'],
      interruptPins: ['D2', 'D3'],
      inputOnlyPins: ['A6', 'A7'],
      reservedPins: [],
      defaultI2c: { sda: 'A4', scl: 'A5' },
      defaultSpi: { mosi: 'D11', miso: 'D12', sck: 'D13', cs: 'D10' },
      defaultUart: [{ id: 'Serial', tx: 'D1', rx: 'D0' }],
      bluetooth: { classic: false, ble: false },
      maxGpioSinkMa: 40,
      recommendedGpioSinkMa: 20,
    },
  }),

  def({
    id: 'arduino-mega',
    name: 'Arduino Mega 2560',
    category: 'microcontroller',
    description:
      'ATmega2560 based board: 5 V logic, 54 digital I/O (15 PWM), 16 analog inputs (10-bit ADC), four hardware UARTs and 8 KB of SRAM. The board to reach for when a Uno runs out of pins — many-sensor builds, 3D printers, large relay/multiplexed designs. Same per-pin limits as the Uno: 40 mA absolute max, 20 mA recommended, ~200 mA total through the on-board regulator.',
    voltage: 5,
    minVoltage: 4.5,
    maxVoltage: 5.5,
    currentRequirements: {
      typicalMa: 70,
      maxMa: 200,
      note: 'Per-pin absolute maximum 40 mA; 20 mA recommended continuous. Total through the 5 V regulator ~200 mA (800 mA for the NCP1117 on R3 boards with good cooling).',
    },
    communicationProtocols: ['uart', 'i2c', 'spi', 'adc', 'pwm'],
    pins: [
      pin('D0', 'uart', 'bidirectional', { signal: 'Serial RX — shared with the USB serial bridge', aliases: ['RX', '0'] }),
      pin('D1', 'uart', 'bidirectional', { signal: 'Serial TX — shared with the USB serial bridge', aliases: ['TX', '1'] }),
      pin('D2', 'digital', 'bidirectional', { signal: 'External interrupt INT0 / PWM', aliases: ['2'] }),
      pin('D3', 'digital', 'bidirectional', { signal: 'External interrupt INT1 / PWM', aliases: ['3'] }),
      pin('D4', 'digital', 'bidirectional', { aliases: ['4'] }),
      pin('D5', 'digital', 'bidirectional', { signal: 'PWM', aliases: ['5'] }),
      pin('D6', 'digital', 'bidirectional', { signal: 'PWM', aliases: ['6'] }),
      pin('D7', 'digital', 'bidirectional', { aliases: ['7'] }),
      pin('D8', 'digital', 'bidirectional', { aliases: ['8'] }),
      pin('D9', 'digital', 'bidirectional', { signal: 'PWM', aliases: ['9'] }),
      pin('D10', 'digital', 'bidirectional', { signal: 'PWM', aliases: ['10'] }),
      pin('D11', 'digital', 'bidirectional', { signal: 'PWM', aliases: ['11'] }),
      pin('D12', 'digital', 'bidirectional', { signal: 'PWM', aliases: ['12'] }),
      pin('D13', 'digital', 'bidirectional', { signal: 'PWM / on-board LED', aliases: ['13', 'SCK_LED'] }),
      pin('D14', 'uart', 'bidirectional', { signal: 'Serial3 TX', aliases: ['TX3', '14'] }),
      pin('D15', 'uart', 'bidirectional', { signal: 'Serial3 RX', aliases: ['RX3', '15'] }),
      pin('D16', 'uart', 'bidirectional', { signal: 'Serial2 TX', aliases: ['TX2', '16'] }),
      pin('D17', 'uart', 'bidirectional', { signal: 'Serial2 RX', aliases: ['RX2', '17'] }),
      pin('D18', 'uart', 'bidirectional', { signal: 'Serial1 TX / external interrupt INT5', aliases: ['TX1', '18'] }),
      pin('D19', 'uart', 'bidirectional', { signal: 'Serial1 RX / external interrupt INT4', aliases: ['RX1', '19'] }),
      pin('D20', 'i2c', 'bidirectional', { signal: 'I2C SDA / external interrupt INT3', aliases: ['SDA', '20'] }),
      pin('D21', 'i2c', 'bidirectional', { signal: 'I2C SCL / external interrupt INT2', aliases: ['SCL', '21'] }),
      pin('D22', 'digital', 'bidirectional', { aliases: ['22'] }),
      pin('D23', 'digital', 'bidirectional', { aliases: ['23'] }),
      pin('D24', 'digital', 'bidirectional', { aliases: ['24'] }),
      pin('D25', 'digital', 'bidirectional', { aliases: ['25'] }),
      pin('D26', 'digital', 'bidirectional', { aliases: ['26'] }),
      pin('D27', 'digital', 'bidirectional', { aliases: ['27'] }),
      pin('D28', 'digital', 'bidirectional', { aliases: ['28'] }),
      pin('D29', 'digital', 'bidirectional', { aliases: ['29'] }),
      pin('D30', 'digital', 'bidirectional', { aliases: ['30'] }),
      pin('D31', 'digital', 'bidirectional', { aliases: ['31'] }),
      pin('D32', 'digital', 'bidirectional', { aliases: ['32'] }),
      pin('D33', 'digital', 'bidirectional', { aliases: ['33'] }),
      pin('D34', 'digital', 'bidirectional', { aliases: ['34'] }),
      pin('D35', 'digital', 'bidirectional', { aliases: ['35'] }),
      pin('D36', 'digital', 'bidirectional', { aliases: ['36'] }),
      pin('D37', 'digital', 'bidirectional', { aliases: ['37'] }),
      pin('D38', 'digital', 'bidirectional', { aliases: ['38'] }),
      pin('D39', 'digital', 'bidirectional', { aliases: ['39'] }),
      pin('D40', 'digital', 'bidirectional', { aliases: ['40'] }),
      pin('D41', 'digital', 'bidirectional', { aliases: ['41'] }),
      pin('D42', 'digital', 'bidirectional', { aliases: ['42'] }),
      pin('D43', 'digital', 'bidirectional', { aliases: ['43'] }),
      pin('D44', 'digital', 'bidirectional', { signal: 'PWM', aliases: ['44'] }),
      pin('D45', 'digital', 'bidirectional', { signal: 'PWM', aliases: ['45'] }),
      pin('D46', 'digital', 'bidirectional', { signal: 'PWM', aliases: ['46'] }),
      pin('D47', 'digital', 'bidirectional', { aliases: ['47'] }),
      pin('D48', 'digital', 'bidirectional', { aliases: ['48'] }),
      pin('D49', 'digital', 'bidirectional', { aliases: ['49'] }),
      pin('D50', 'spi', 'bidirectional', { signal: 'SPI MISO', aliases: ['MISO', '50'] }),
      pin('D51', 'spi', 'bidirectional', { signal: 'SPI MOSI', aliases: ['MOSI', '51'] }),
      pin('D52', 'spi', 'bidirectional', { signal: 'SPI SCK', aliases: ['SCK', '52'] }),
      pin('D53', 'spi', 'bidirectional', { signal: 'SPI SS — leave as OUTPUT even when unused, or SPI slips into slave mode', aliases: ['SS', '53'] }),
      pin('A0', 'analog', 'input', { signal: 'ADC0, usable as digital D54', aliases: ['54'] }),
      pin('A1', 'analog', 'input', { signal: 'ADC1, usable as digital D55', aliases: ['55'] }),
      pin('A2', 'analog', 'input', { signal: 'ADC2, usable as digital D56', aliases: ['56'] }),
      pin('A3', 'analog', 'input', { signal: 'ADC3, usable as digital D57', aliases: ['57'] }),
      pin('A4', 'analog', 'input', { signal: 'ADC4, usable as digital D58', aliases: ['58'] }),
      pin('A5', 'analog', 'input', { signal: 'ADC5, usable as digital D59', aliases: ['59'] }),
      pin('A6', 'analog', 'input', { signal: 'ADC6, usable as digital D60', aliases: ['60'] }),
      pin('A7', 'analog', 'input', { signal: 'ADC7, usable as digital D61', aliases: ['61'] }),
      pin('A8', 'analog', 'input', { signal: 'ADC16, usable as digital D62', aliases: ['62'] }),
      pin('A9', 'analog', 'input', { signal: 'ADC17, usable as digital D63', aliases: ['63'] }),
      pin('A10', 'analog', 'input', { signal: 'ADC18, usable as digital D64', aliases: ['64'] }),
      pin('A11', 'analog', 'input', { signal: 'ADC19, usable as digital D65', aliases: ['65'] }),
      pin('A12', 'analog', 'input', { signal: 'ADC20, usable as digital D66', aliases: ['66'] }),
      pin('A13', 'analog', 'input', { signal: 'ADC21, usable as digital D67', aliases: ['67'] }),
      pin('A14', 'analog', 'input', { signal: 'ADC22, usable as digital D68', aliases: ['68'] }),
      pin('A15', 'analog', 'input', { signal: 'ADC23, usable as digital D69', aliases: ['69'] }),
      pin('5V', 'power', 'power', { required: true, voltage: 5, aliases: ['VCC', '5v'] }),
      pin('3V3', 'power', 'power', { voltage: 3.3, aliases: ['3.3V'], description: '50 mA max from the on-board regulator' }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Common ground — five physically separate pins, all the same net', aliases: ['VSS', 'GND.1', 'GND.2', 'GND.3', 'GND.4', 'GND.5'] }),
      pin('VIN', 'power', 'power', { voltage: 9, aliases: ['RAW'], signal: '7–12 V unregulated input' }),
      pin('RESET', 'control', 'input', { aliases: ['RST'] }),
      pin('IOREF', 'power', 'output', { voltage: 5, signal: 'Shield logic-level reference (5 V)' }),
      pin('AREF', 'analog', 'input', { signal: 'External analog reference for the ADC — only drive it after analogReference(EXTERNAL)' }),
    ],
    libraryRequirements: [{ name: 'Arduino AVR core', import: 'Arduino.h', manager: 'arduino', purpose: 'Board support package', builtIn: true }],
    exampleUsage: [
      '3D printer / CNC controller with many end-stops and drivers',
      'Greenhouse with 10+ sensors and relays on one board',
      'Pin-hungry LED matrix or relay bank without port expanders',
    ],
    aliases: ['mega', 'arduino mega', 'mega 2560', 'arduinomega', 'atmega2560', 'mega2560'],
    keywords: ['arduino', 'mega', '2560', 'atmega2560', 'avr', '5v', 'microcontroller', 'mcu', 'many pins'],
    simulator: {
      part: 'wokwi-arduino-mega',
      supported: true,
      notes: 'Velxio/Wokwi board element: pins 0-53, A0-A15, 5V, 3.3V, VIN, GND.1-GND.5. All four hardware UARTs are emulated.',
    },
    metadata: {
      mcuProfileId: 'arduino-mega',
      logicVoltage: 5,
      usbPowered: true,
      usbVoltage: 5,
      usbMaxCurrentMa: 500,
      onboardRegulator: '5 V from USB, on-board regulator for VIN (7–12 V)',
      mcu: 'ATmega2560',
      clockMhz: 16,
      flashKb: 256,
      sramKb: 8,
      adcResolutionBits: 10,
      pwmPins: ['D2', 'D3', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D44', 'D45', 'D46'],
      interruptPins: ['D2', 'D3', 'D18', 'D19', 'D20', 'D21'],
      reservedPins: [],
      inputOnlyPins: [],
      defaultI2c: { sda: 'D20', scl: 'D21' },
      defaultSpi: { mosi: 'D51', miso: 'D50', sck: 'D52', cs: 'D53' },
      defaultUart: [
        { id: 'Serial', tx: 'D1', rx: 'D0', note: 'Shared with the USB serial bridge' },
        { id: 'Serial1', tx: 'D18', rx: 'D19' },
        { id: 'Serial2', tx: 'D16', rx: 'D17' },
        { id: 'Serial3', tx: 'D14', rx: 'D15' },
      ],
      bluetooth: { classic: false, ble: false },
      maxGpioSinkMa: 40,
      recommendedGpioSinkMa: 20,
    },
  }),
];
