/**
 * Motion hardware seed entries: fans, propellers, pumps, linear actuators,
 * solenoids, vibration motors, brushless motors and their ESCs.
 *
 * Everything in this file is a *load*: it either needs a driver stage
 * (MOSFET / H-bridge / relay / ESC) or an integrated one. Each entry records
 * the real supply window and the honest current figures so the power budget
 * and the wiring planner refuse to hang it off a GPIO.
 */

import type { ComponentDefinition } from '@/types/component';

import { def, pin } from './helpers';

export const MOTION: ComponentDefinition[] = [
  def({
    id: 'fan-5v-40mm',
    name: '40 mm 5 V axial cooling fan (2-wire)',
    category: 'motor',
    description:
      'Two-wire brushless axial fan, 40 x 40 x 10 mm, 5 V DC. Speed is not directly controllable from a logic pin: switch it with a low-side MOSFET or a relay, and add a flyback diode because the fan winding is inductive. Low-frequency PWM (25 kHz recommended, never audio-band) works on the low side only.',
    voltage: 5,
    minVoltage: 4.5,
    maxVoltage: 5.5,
    currentRequirements: {
      typicalMa: 120,
      maxMa: 250,
      note: 'Steady-state ~100-150 mA at 5 V; start-up surge is roughly 2x for a few tens of milliseconds.',
    },
    motorRequirements: {
      motorType: 'dc',
      requiresDriver: true,
      requiresExternalSupply: false,
      supplyVoltageMin: 4.5,
      supplyVoltageMax: 5.5,
      stallCurrentMa: 400,
      controlSignal: 'pwm',
    },
    pins: [
      pin('VCC', 'power', 'power', { required: true, voltage: 5, signal: 'Fan supply +5 V', aliases: ['+', 'V+', 'RED', '5V'] }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Fan return — switch this side with a MOSFET', aliases: ['-', 'V-', 'BLACK'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['fan', 'cooling fan', 'axial fan', '40mm', 'airflow', 'ventilation', 'exhaust'],
    aliases: ['fan', '5v fan', 'cooling fan', '40mm fan', 'case fan'],
    exampleUsage: ['Enclosure exhaust switched by an IRF520 MOSFET module', 'Thermostatic fan controlled from a DS18B20/DHT22 reading'],
    simulator: { supported: false, notes: 'No verified simulator part; model as a switched inductive DC load.' },
    metadata: {
      electrical: true,
      inductiveLoad: true,
      flybackDiodeRequired: true,
      recommendedPwmHz: 25000,
      dimensionsMm: { width: 40, length: 40, height: 10 },
      incompatibleReason: 'Start-up surge and inductive kick exceed a GPIO rating; switch it through a MOSFET, driver or relay.',
    },
  }),

  def({
    id: 'fan-12v-4pin-pwm',
    name: '12 V 4-wire PWM fan (80 mm, tach)',
    category: 'motor',
    description:
      'Intel 4-wire fan standard: permanent 12 V supply, open-drain 25 kHz PWM control input referenced to the fan (5 V tolerant, 3.3 V logic usually works) and an open-collector tachometer output giving 2 pulses per revolution. Never PWM the 12 V rail on a 4-wire fan — use the dedicated PWM pin.',
    voltage: 12,
    minVoltage: 10.8,
    maxVoltage: 13.2,
    currentRequirements: { typicalMa: 200, maxMa: 500, note: 'Typical 80 mm fan draws 0.1-0.25 A at 12 V; high-static-pressure models reach 0.5 A.' },
    motorRequirements: {
      motorType: 'dc',
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 10.8,
      supplyVoltageMax: 13.2,
      controlSignal: 'pwm',
      logicVoltage: 5,
    },
    pins: [
      pin('GND', 'ground', 'ground', { required: true, signal: 'Fan ground — must be common with the MCU ground (pin 1, black)', aliases: ['-', 'BLACK'] }),
      pin('12V', 'power', 'power', { required: true, voltage: 12, signal: 'Continuous 12 V supply (pin 2, yellow)', aliases: ['VCC', '+12V', 'V+', 'YELLOW'] }),
      pin('TACH', 'digital', 'output', { required: false, signal: 'Open-collector tachometer, 2 pulses per revolution — needs a pull-up to the MCU logic rail (pin 3, green)', aliases: ['SENSE', 'RPM', 'GREEN', 'FG'] }),
      pin('PWM', 'pwm', 'input', { required: false, signal: '25 kHz open-drain speed control input (pin 4, blue)', aliases: ['CONTROL', 'BLUE', 'SPEED'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['fan', 'pwm fan', '4-pin fan', 'tachometer', 'rpm', '12v fan', 'cooling'],
    aliases: ['pwm fan', '4 wire fan', '4-pin fan', '12v fan', 'case fan pwm'],
    exampleUsage: ['Closed-loop enclosure cooling with RPM feedback', 'Quiet 3D-printer chamber fan driven at 25 kHz'],
    simulator: { supported: false, notes: 'No verified simulator part; represent as a PWM output plus a pulse input.' },
    metadata: {
      electrical: true,
      pwmFrequencyHz: 25000,
      tachPulsesPerRevolution: 2,
      tachRequiresPullUp: true,
      standard: 'Intel 4-wire PWM-controlled fan specification (rev 1.3)',
      dimensionsMm: { width: 80, length: 80, height: 25 },
    },
  }),

  def({
    id: 'blower-fan-5v-radial',
    name: '5 V radial blower fan (50 x 50 x 15 mm)',
    category: 'motor',
    description:
      'Two-wire centrifugal (squirrel-cage) blower producing higher static pressure than an axial fan at the same size. Same drive rules as any 2-wire fan: low-side MOSFET plus flyback diode.',
    voltage: 5,
    minVoltage: 4.5,
    maxVoltage: 5.5,
    currentRequirements: { typicalMa: 200, maxMa: 400, note: 'Radial impellers load the motor harder than axial fans of the same diameter.' },
    motorRequirements: {
      motorType: 'dc',
      requiresDriver: true,
      requiresExternalSupply: false,
      supplyVoltageMin: 4.5,
      supplyVoltageMax: 5.5,
      stallCurrentMa: 600,
      controlSignal: 'pwm',
    },
    pins: [
      pin('VCC', 'power', 'power', { required: true, voltage: 5, signal: 'Blower supply +5 V', aliases: ['+', 'RED'] }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Return — switch this side', aliases: ['-', 'BLACK'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['blower', 'radial fan', 'centrifugal', 'squirrel cage', 'static pressure', 'hotend fan'],
    aliases: ['blower', 'blower fan', 'radial fan', '5015 blower'],
    simulator: { supported: false },
    metadata: {
      electrical: true,
      inductiveLoad: true,
      flybackDiodeRequired: true,
      dimensionsMm: { width: 50, length: 50, height: 15 },
      incompatibleReason: 'Inductive motor load — must be switched through a MOSFET or driver, not a GPIO.',
    },
  }),

  def({
    id: 'propeller-5045-tri-blade',
    name: '5045 tri-blade propeller (5 in, 4.5 in pitch)',
    category: 'other',
    description:
      'Mechanical propeller for a 22xx-class brushless motor: 5 inch diameter, 4.5 inch pitch, three blades, 5 mm shaft bore with adapter rings. It has no electrical interface — it is a load on the motor and it changes the current the ESC must deliver, so it belongs in the bill of materials and in the thrust/current calculation, not in the wiring.',
    pins: [],
    keywords: ['propeller', 'prop', '5045', 'tri-blade', 'drone', 'quadcopter', 'thrust'],
    aliases: ['propeller', 'prop', '5045 prop', 'tri blade propeller', 'drone propeller'],
    exampleUsage: ['Quadcopter thrust stage paired with a 2205 motor and a 30 A ESC'],
    simulator: { supported: false, notes: 'Mechanical part; nothing to simulate electrically.' },
    metadata: {
      electrical: false,
      mechanicalOnly: true,
      diameterIn: 5,
      pitchIn: 4.5,
      blades: 3,
      shaftBoreMm: 5,
      pairedWith: ['bldc-motor-2205-2300kv'],
      safetyNote: 'Remove propellers before any bench test that spins the motor.',
    },
  }),

  def({
    id: 'propeller-ep-1045-two-blade',
    name: '1045 two-blade propeller (10 in, 4.5 in pitch)',
    category: 'other',
    description:
      'Slow-fly 10 inch two-blade propeller for 2212-class motors on 2-4S packs. Mechanical only; sizing it changes the ESC current draw and the required battery C-rating.',
    pins: [],
    keywords: ['propeller', '1045', 'two blade', 'quadcopter', 'multirotor', 'thrust'],
    aliases: ['1045 prop', '10 inch propeller', 'ep1045'],
    simulator: { supported: false },
    metadata: {
      electrical: false,
      mechanicalOnly: true,
      diameterIn: 10,
      pitchIn: 4.5,
      blades: 2,
      shaftBoreMm: 6,
      pairedWith: ['bldc-motor-2212-1000kv'],
    },
  }),

  def({
    id: 'bldc-motor-2205-2300kv',
    name: '2205 brushless outrunner (2300 KV)',
    category: 'motor',
    description:
      'Three-phase brushless outrunner for 5 inch multirotors: 2300 KV, 3-4S (11.1-14.8 V), roughly 300 W peak with a 5045 propeller. It has no commutator — the three phase wires must be driven by an ESC, and swapping any two of them reverses rotation.',
    voltage: 14.8,
    minVoltage: 7.4,
    maxVoltage: 16.8,
    currentRequirements: { typicalMa: 8000, maxMa: 25000, note: 'Around 8 A hover, 20-25 A at full throttle on 4S with a 5045 prop.' },
    motorRequirements: {
      motorType: 'dc',
      channels: 3,
      requiresDriver: true,
      requiresExternalSupply: true,
      supplyVoltageMin: 7.4,
      supplyVoltageMax: 16.8,
      maxCurrentPerChannelMa: 25000,
      controlSignal: 'pwm',
      rpm: 34000,
    },
    pins: [
      pin('PHASE_A', 'motor', 'input', { required: true, signal: 'Motor phase A', aliases: ['A', 'U', 'PHASE A', 'WIRE1'] }),
      pin('PHASE_B', 'motor', 'input', { required: true, signal: 'Motor phase B', aliases: ['B', 'V', 'PHASE B', 'WIRE2'] }),
      pin('PHASE_C', 'motor', 'input', { required: true, signal: 'Motor phase C', aliases: ['C', 'W', 'PHASE C', 'WIRE3'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano', 'l298n-motor-driver', 'tb6612fng-motor-driver'],
    keywords: ['brushless', 'bldc', 'outrunner', '2205', 'drone', 'quadcopter', 'motor'],
    aliases: ['brushless motor', 'bldc', '2205 motor', 'outrunner', 'drone motor'],
    exampleUsage: ['Quadcopter arm: 2205 motor + 30 A BLHeli ESC + 5045 propeller'],
    simulator: { supported: false, notes: 'No verified simulator part.' },
    metadata: {
      electrical: true,
      noSupplyPins: true,
      kv: 2300,
      poles: 12,
      shaftMm: 5,
      mountPattern: 'M3 16x16 mm',
      requiresEsc: true,
      incompatibleReason: 'Three-phase motor: requires an electronic speed controller, not an H-bridge or a GPIO.',
    },
  }),

  def({
    id: 'bldc-motor-2212-1000kv',
    name: '2212 brushless outrunner (1000 KV)',
    category: 'motor',
    description:
      'Classic 2212-size brushless outrunner, 1000 KV, 2-4S, sized for 8-10 inch propellers on a quadcopter or fixed-wing model. Requires an ESC (typically 30 A) and a bullet-connector or soldered phase joint.',
    voltage: 11.1,
    minVoltage: 7.4,
    maxVoltage: 16.8,
    currentRequirements: { typicalMa: 6000, maxMa: 15000, note: 'About 5-7 A cruise, up to ~15 A peak with a 1045 propeller on 3S.' },
    motorRequirements: {
      motorType: 'dc',
      channels: 3,
      requiresDriver: true,
      requiresExternalSupply: true,
      supplyVoltageMin: 7.4,
      supplyVoltageMax: 16.8,
      maxCurrentPerChannelMa: 15000,
      controlSignal: 'pwm',
      rpm: 11000,
    },
    pins: [
      pin('PHASE_A', 'motor', 'input', { required: true, signal: 'Motor phase A', aliases: ['A', 'U'] }),
      pin('PHASE_B', 'motor', 'input', { required: true, signal: 'Motor phase B', aliases: ['B', 'V'] }),
      pin('PHASE_C', 'motor', 'input', { required: true, signal: 'Motor phase C', aliases: ['C', 'W'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['brushless', 'bldc', '2212', '1000kv', 'quadcopter', 'outrunner'],
    aliases: ['2212 motor', 'a2212', '1000kv brushless'],
    simulator: { supported: false },
    metadata: { electrical: true, noSupplyPins: true, kv: 1000, shaftMm: 3.17, requiresEsc: true },
  }),

  def({
    id: 'esc-30a-bldc',
    name: '30 A brushless ESC (with 5 V/2 A BEC)',
    category: 'motor_driver',
    description:
      'Electronic speed controller for a three-phase brushless motor: 2-4S input, 30 A continuous, driven by a standard 50 Hz servo pulse (1000-2000 us) or OneShot/DShot on modern firmware. Its BEC output can supply 5 V at ~2 A to the flight controller. Arming requires the throttle signal to sit at minimum at power-up.',
    voltage: 11.1,
    minVoltage: 7.4,
    maxVoltage: 16.8,
    currentRequirements: { typicalMa: 15000, maxMa: 30000, note: '30 A continuous, ~40 A burst for a few seconds; the BEC adds up to 2 A on the 5 V rail.' },
    motorRequirements: {
      motorType: 'dc',
      channels: 3,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 7.4,
      supplyVoltageMax: 16.8,
      maxCurrentPerChannelMa: 30000,
      controlSignal: 'pwm',
      logicVoltage: 5,
    },
    pins: [
      pin('SIGNAL', 'pwm', 'input', { required: true, signal: 'Throttle input, 50-490 Hz, 1000-2000 us pulse (white/yellow)', aliases: ['SIG', 'PWM', 'THROTTLE', 'S', 'WHITE'] }),
      pin('BEC_5V', 'power', 'output', { required: false, voltage: 5, signal: '5 V / 2 A BEC output (red) — do not back-feed if the MCU has its own supply', aliases: ['5V', 'VCC', 'BEC', 'RED'] }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Signal and power ground (black/brown)', aliases: ['-', 'BLACK', 'BROWN'] }),
      pin('BAT+', 'power', 'power', { required: true, voltage: 11.1, signal: 'Battery positive (2-4S LiPo)', aliases: ['VBAT', 'B+', 'VIN', 'POWER+'] }),
      pin('BAT-', 'ground', 'ground', { required: true, signal: 'Battery negative', aliases: ['B-', 'POWER-'] }),
      pin('PHASE_A', 'motor', 'output', { required: true, signal: 'Motor phase A', aliases: ['A', 'U', 'M1'] }),
      pin('PHASE_B', 'motor', 'output', { required: true, signal: 'Motor phase B', aliases: ['B', 'V', 'M2'] }),
      pin('PHASE_C', 'motor', 'output', { required: true, signal: 'Motor phase C', aliases: ['C', 'W', 'M3'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    libraryRequirements: [
      { name: 'Servo', import: 'Servo.h', manager: 'arduino', purpose: 'Generates the 1000-2000 us throttle pulse an ESC expects', builtIn: true },
    ],
    keywords: ['esc', 'speed controller', 'brushless', 'blheli', '30a', 'drone', 'throttle'],
    aliases: ['esc', '30a esc', 'brushless esc', 'speed controller'],
    exampleUsage: ['Quadcopter motor channel', 'Brushless RC car / boat propulsion'],
    simulator: { supported: false, notes: 'No verified simulator part; the throttle pulse can be modelled as a servo output.' },
    metadata: {
      electrical: true,
      pulseRangeUs: [1000, 2000],
      armingSequence: 'Hold minimum throttle for ~2 s at power-up before commanding thrust.',
      becOutput: { voltage: 5, currentMa: 2000 },
      protocols: ['pwm', 'oneshot125', 'dshot600'],
      safetyNote: 'Bench-test with propellers removed.',
    },
  }),

  def({
    id: 'vibration-motor-coin-3v',
    name: 'Coin vibration motor (10 mm, 3 V)',
    category: 'motor',
    description:
      'Shaftless eccentric-rotating-mass (ERM) pancake motor, 3 V nominal, ~80 mA. Small enough to be tempting to drive directly from a pin — do not: use a small NPN/MOSFET plus a flyback diode, because the brushed motor injects noise and inductive spikes onto the rail.',
    voltage: 3,
    minVoltage: 2.5,
    maxVoltage: 3.6,
    currentRequirements: { typicalMa: 80, maxMa: 120, note: 'Rated ~75-90 mA at 3 V; start-up peak is roughly 2x.' },
    motorRequirements: {
      motorType: 'dc',
      requiresDriver: true,
      requiresExternalSupply: false,
      supplyVoltageMin: 2.5,
      supplyVoltageMax: 3.6,
      stallCurrentMa: 150,
      controlSignal: 'pwm',
      rpm: 12000,
    },
    pins: [
      pin('+', 'motor', 'input', { required: true, signal: 'Motor positive (red)', aliases: ['VCC', 'A', 'RED'] }),
      pin('-', 'motor', 'input', { required: true, signal: 'Motor negative (blue/black) — switch this side', aliases: ['GND', 'B', 'BLUE', 'BLACK'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1'],
    keywords: ['vibration', 'haptic', 'erm', 'coin motor', 'pancake motor', 'buzz'],
    aliases: ['vibration motor', 'haptic motor', 'coin motor', 'vibrator motor'],
    exampleUsage: ['Haptic feedback on a wearable', 'Silent alert on a handheld device'],
    simulator: { supported: false },
    metadata: {
      electrical: true,
      noSupplyPins: true,
      inductiveLoad: true,
      flybackDiodeRequired: true,
      driverSuggestion: '2N2222/BC337 NPN or a logic-level MOSFET with a 1N4148 flyback diode',
      incompatibleReason: 'A brushed motor on a GPIO risks brownouts and inductive damage even at 80 mA.',
    },
  }),

  def({
    id: 'water-pump-5v-submersible',
    name: 'Submersible water pump (5 V, 120 L/h)',
    category: 'motor',
    description:
      'Small brushed centrifugal pump for irrigation and hydroponics: 5 V, ~200 mA, roughly 120 L/h at zero head and ~40 cm lift. Two wires, no polarity protection, and it must never run dry. Drive it through a MOSFET module or relay with a flyback diode.',
    voltage: 5,
    minVoltage: 3,
    maxVoltage: 6,
    currentRequirements: { typicalMa: 200, maxMa: 350, note: 'Higher when the outlet is restricted; stalls (blocked impeller) draw the most.' },
    motorRequirements: {
      motorType: 'dc',
      requiresDriver: true,
      requiresExternalSupply: false,
      supplyVoltageMin: 3,
      supplyVoltageMax: 6,
      stallCurrentMa: 500,
      controlSignal: 'pwm',
    },
    pins: [
      pin('+', 'motor', 'input', { required: true, signal: 'Pump positive (red)', aliases: ['VCC', 'A', 'RED'] }),
      pin('-', 'motor', 'input', { required: true, signal: 'Pump negative (black) — switched by the driver', aliases: ['GND', 'B', 'BLACK'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['pump', 'water pump', 'submersible', 'irrigation', 'hydroponics', 'plant watering'],
    aliases: ['water pump', 'mini pump', 'submersible pump', '5v pump'],
    exampleUsage: ['Automatic plant watering triggered by a soil-moisture reading', 'Aquarium top-up loop'],
    simulator: { supported: false },
    metadata: {
      electrical: true,
      noSupplyPins: true,
      inductiveLoad: true,
      flybackDiodeRequired: true,
      flowLitresPerHour: 120,
      maxHeadCm: 40,
      operatingNote: 'Dry running destroys the impeller bearing within minutes.',
      incompatibleReason: 'Motor load with start-up surge; a GPIO cannot supply or survive it.',
    },
  }),

  def({
    id: 'peristaltic-pump-12v',
    name: 'Peristaltic dosing pump (12 V, 100 mL/min)',
    category: 'motor',
    description:
      'Geared peristaltic pump: the tube is squeezed by rollers so the fluid never touches the motor. 12 V, ~400 mA, roughly 100 mL/min, reversible if driven from an H-bridge. Ideal for dosing because delivered volume is proportional to run time.',
    voltage: 12,
    minVoltage: 6,
    maxVoltage: 12,
    currentRequirements: { typicalMa: 400, maxMa: 800, note: 'Draw rises with tube compression and viscosity; stall around 800 mA.' },
    motorRequirements: {
      motorType: 'dc',
      requiresDriver: true,
      requiresExternalSupply: true,
      supplyVoltageMin: 6,
      supplyVoltageMax: 12,
      stallCurrentMa: 800,
      controlSignal: 'pwm',
      rpm: 100,
    },
    pins: [
      pin('A', 'motor', 'input', { required: true, signal: 'Motor terminal A', aliases: ['+', 'RED', 'M+'] }),
      pin('B', 'motor', 'input', { required: true, signal: 'Motor terminal B', aliases: ['-', 'BLACK', 'M-'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['peristaltic', 'dosing pump', 'liquid', 'ph dosing', 'hydroponics', 'pump'],
    aliases: ['peristaltic pump', 'dosing pump', 'liquid pump'],
    exampleUsage: ['pH / nutrient dosing driven through an L298N channel', 'Timed reagent delivery in a lab rig'],
    simulator: { supported: false },
    metadata: { electrical: true, noSupplyPins: true, flowMlPerMin: 100, reversible: true, tubeIdMm: 2.5 },
  }),

  def({
    id: 'linear-actuator-12v-100mm',
    name: '12 V linear actuator (100 mm stroke)',
    category: 'actuator',
    description:
      'DC gear motor driving a lead screw with built-in limit switches at both ends of a 100 mm stroke. Extend and retract by reversing polarity, so it needs an H-bridge rated for its stall current. The internal limit switches stop travel but do not protect against continuous stall, so add a timeout in firmware.',
    voltage: 12,
    minVoltage: 10,
    maxVoltage: 14,
    currentRequirements: { typicalMa: 1200, maxMa: 3000, note: '~1 A no-load, up to 3 A at rated load / stall.' },
    motorRequirements: {
      motorType: 'dc',
      requiresDriver: true,
      requiresExternalSupply: true,
      supplyVoltageMin: 10,
      supplyVoltageMax: 14,
      stallCurrentMa: 3000,
      controlSignal: 'digital',
    },
    pins: [
      pin('A', 'motor', 'input', { required: true, signal: 'Actuator terminal A (extend when positive)', aliases: ['+', 'RED', 'M+'] }),
      pin('B', 'motor', 'input', { required: true, signal: 'Actuator terminal B', aliases: ['-', 'BLACK', 'M-'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano', 'tb6612fng-motor-driver', 'drv8833-motor-driver'],
    keywords: ['linear actuator', 'stroke', 'lead screw', 'push pull', 'extend', 'retract'],
    aliases: ['linear actuator', 'actuator', '12v actuator'],
    exampleUsage: ['Automated window / vent opener', 'Camera slider or lifting platform driven by a BTS7960'],
    simulator: { supported: false },
    metadata: {
      electrical: true,
      noSupplyPins: true,
      strokeMm: 100,
      speedMmPerSec: 10,
      maxLoadN: 750,
      builtInLimitSwitches: true,
      incompatibleReason: 'Stall current up to 3 A needs a high-current H-bridge (L298N is marginal; BTS7960 preferred).',
    },
  }),

  def({
    id: 'solenoid-12v-push-pull',
    name: '12 V push-pull solenoid (JF-0530B)',
    category: 'actuator',
    description:
      'Open-frame linear solenoid: energising the coil pulls the plunger about 10 mm. Highly inductive and rated for intermittent duty only (roughly 20-30 % duty cycle) — it overheats if left energised. Drive it with a logic-level MOSFET or relay and an anti-parallel flyback diode across the coil.',
    voltage: 12,
    minVoltage: 9,
    maxVoltage: 12,
    currentRequirements: { typicalMa: 650, maxMa: 1100, note: 'Coil resistance ~18 ohm gives ~0.65 A at 12 V; inrush is higher before the plunger seats.' },
    pins: [
      pin('COIL_A', 'motor', 'input', { required: true, signal: 'Coil terminal A (to +12 V)', aliases: ['+', 'A', 'RED'] }),
      pin('COIL_B', 'motor', 'input', { required: true, signal: 'Coil terminal B (switched to ground by the driver)', aliases: ['-', 'B', 'BLACK'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['solenoid', 'plunger', 'latch', 'push pull', 'actuator', 'door lock'],
    aliases: ['solenoid', '12v solenoid', 'push pull solenoid'],
    exampleUsage: ['Electronic door latch released by an RFID match', 'Coin/ball release mechanism'],
    simulator: { supported: false },
    metadata: {
      electrical: true,
      noSupplyPins: true,
      inductiveLoad: true,
      flybackDiodeRequired: true,
      strokeMm: 10,
      holdingForceN: 5,
      dutyCyclePercent: 25,
      incompatibleReason: 'Inductive 0.65 A coil: needs a MOSFET/relay stage and a flyback diode, never a GPIO.',
    },
  }),

  def({
    id: 'solenoid-valve-12v-water',
    name: '12 V solenoid water valve (1/2 in, normally closed)',
    category: 'actuator',
    description:
      'Normally-closed plastic solenoid valve for low-pressure water: 12 V, ~500 mA, opens while energised. Needs a minimum working pressure (typically 0.02 MPa) to seal correctly and the same MOSFET/relay + flyback treatment as any coil.',
    voltage: 12,
    minVoltage: 9,
    maxVoltage: 13,
    currentRequirements: { typicalMa: 500, maxMa: 700, note: 'Continuous while open; the valve is designed for continuous duty unlike a push-pull solenoid.' },
    pins: [
      pin('COIL_A', 'motor', 'input', { required: true, signal: 'Coil terminal A (+12 V)', aliases: ['+', 'A'] }),
      pin('COIL_B', 'motor', 'input', { required: true, signal: 'Coil terminal B (switched)', aliases: ['-', 'B'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['solenoid valve', 'water valve', 'irrigation', 'normally closed', 'flow control'],
    aliases: ['solenoid valve', 'water valve', '12v valve'],
    exampleUsage: ['Garden irrigation zone switched by a relay module', 'Automatic pet water dispenser'],
    simulator: { supported: false },
    metadata: {
      electrical: true,
      noSupplyPins: true,
      inductiveLoad: true,
      flybackDiodeRequired: true,
      normallyClosed: true,
      minWorkingPressureMpa: 0.02,
      portSize: 'G1/2',
      incompatibleReason: 'Inductive 0.5 A coil at 12 V requires a relay or MOSFET stage.',
    },
  }),
];
