/** Motor and motor-driver seed entries. */

import type { ComponentDefinition } from '@/types/component';

import { def, pin } from './helpers';

export const MOTORS: ComponentDefinition[] = [
  def({
    id: 'dc-motor-generic-6v',
    name: 'DC gear motor (6 V)',
    category: 'motor',
    description:
      'Two-terminal brushed DC motor, typically 3–12 V with a gearbox. Direction is set by reversing polarity across the terminals; speed by PWM duty. Must be driven through an H-bridge — never from an MCU pin.',
    voltage: 6,
    minVoltage: 3,
    maxVoltage: 12,
    currentRequirements: {
      typicalMa: 250,
      maxMa: 1500,
      note: 'Free-run current at 6 V is roughly 150–300 mA; stall current is 5–10x that. Verify against the actual motor datasheet.',
    },
    motorRequirements: {
      motorType: 'dc',
      requiresDriver: true,
      requiresExternalSupply: true,
      supplyVoltageMin: 3,
      supplyVoltageMax: 12,
      stallCurrentMa: 1500,
      controlSignal: 'pwm',
      rpm: 200,
    },
    pins: [
      pin('A', 'motor', 'input', { required: true, signal: 'Motor terminal A', aliases: ['+', 'M+', '1', 'RED'] }),
      pin('B', 'motor', 'input', { required: true, signal: 'Motor terminal B', aliases: ['-', 'M-', '2', 'BLACK'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['dc motor', 'motor', 'gear motor', 'brushed', 'wheel', 'drive'],
    aliases: ['dc motor', 'motor', 'geared dc motor', 'tt motor', 'dc gear motor', 'bo motor'],
    exampleUsage: ['RC car wheel driven by an L298N OUT1/OUT2 pair', 'Conveyor belt driven through a TB6612FNG channel'],
    metadata: {
      electrical: true,
      noSupplyPins: true,
      notes: 'Add a flyback diode (or use a driver with built-in clamp diodes) to absorb back-EMF.',
      incompatibleReason: 'Stall current exceeds any MCU GPIO rating; an H-bridge driver is mandatory.',
    },
  }),

  def({
    id: 'servo-motor-sg90',
    name: 'SG90 micro servo',
    category: 'motor',
    description:
      '9 g hobby servo with an internal driver. Position is set by a 50 Hz PWM pulse of 0.5–2.5 ms. Draws 3.3 V/5 V logic and up to ~500 mA at stall, so a separate supply is recommended for multiple servos.',
    voltage: 5,
    minVoltage: 4.8,
    maxVoltage: 6,
    currentRequirements: { typicalMa: 100, maxMa: 500, note: 'Stall/holding current; idle is a few mA.' },
    motorRequirements: {
      motorType: 'servo',
      requiresDriver: false,
      requiresExternalSupply: false,
      supplyVoltageMin: 4.8,
      supplyVoltageMax: 6,
      stallCurrentMa: 500,
      holdingTorqueKgCm: 1.8,
      controlSignal: 'pwm',
    },
    pins: [
      pin('SIGNAL', 'pwm', 'input', { required: true, signal: '50 Hz position PWM (0.5–2.5 ms)', aliases: ['S', 'SIG', 'PWM', 'DATA', 'ORANGE'] }),
      pin('VCC', 'power', 'power', { required: true, voltage: 5, aliases: ['+', 'V+', 'RED'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['-', 'V-', 'BROWN', 'BLACK'] }),
    ],
    libraryRequirements: [
      { name: 'Servo', import: 'Servo.h', manager: 'arduino', purpose: 'Hardware timer based servo PWM', builtIn: true },
    ],
    keywords: ['servo', 'sg90', 'micro servo', 'position', 'angular', 'steering'],
    aliases: ['servo', 'sg90', 'micro servo', 'hobby servo', '9g servo'],
    exampleUsage: ['RC car steering', 'Sensor pan/tilt', 'Robotic arm joint'],
    simulator: { part: 'wokwi-servo', supported: true },
    metadata: {
      electrical: true,
      pwmFrequencyHz: 50,
      pulseRangeUs: [500, 2500],
      /*
       * A servo is driven to a position and then holds at a few mA; its stall
       * figure is an abnormal, brief condition, not a continuous draw. Treating
       * stall current as sustained made every single-servo build fail the power
       * budget on paper.
       */
      stallIsTransient: true,
    },
  }),

  def({
    id: 'servo-motor-mg996r',
    name: 'MG996R metal-gear servo',
    category: 'motor',
    description:
      'Standard-size metal-gear servo, 4.8–7.2 V, up to ~2.5 A stall. Requires a dedicated supply — an MCU board regulator cannot feed it.',
    voltage: 6,
    minVoltage: 4.8,
    maxVoltage: 7.2,
    currentRequirements: { typicalMa: 170, maxMa: 2500, note: 'Stall current; use a 3 A capable supply and 1000 µF bulk capacitance.' },
    motorRequirements: {
      motorType: 'servo',
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 4.8,
      supplyVoltageMax: 7.2,
      stallCurrentMa: 2500,
      holdingTorqueKgCm: 11,
      controlSignal: 'pwm',
    },
    pins: [
      pin('SIGNAL', 'pwm', 'input', { required: true, signal: '50 Hz position PWM', aliases: ['S', 'SIG', 'PWM', 'ORANGE'] }),
      pin('VCC', 'power', 'power', { required: true, voltage: 6, aliases: ['+', 'RED'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['-', 'BROWN', 'BLACK'] }),
    ],
    libraryRequirements: [{ name: 'Servo', import: 'Servo.h', manager: 'arduino', purpose: 'Servo PWM', builtIn: true }],
    keywords: ['servo', 'mg996r', 'metal gear', 'high torque'],
    aliases: ['mg996r', 'metal gear servo', 'high torque servo'],
    simulator: { part: 'wokwi-servo', supported: true, notes: 'Simulated as a generic servo; current draw is not modelled.' },
    metadata: {
      electrical: true,
      pwmFrequencyHz: 50,
      pulseRangeUs: [500, 2500],
      requiresBulkCapacitor: true,
      // Position servo: stall current is brief and abnormal, not a continuous draw.
      stallIsTransient: true,
    },
  }),

  def({
    id: 'stepper-28byj48-uln2003',
    name: '28BYJ-48 stepper with ULN2003 driver board',
    category: 'motor',
    description:
      '5 V unipolar stepper (64 steps/revolution) geared 64:1, supplied with a ULN2003A Darlington driver board. Driven by sequencing four logic inputs; ~2048 half-steps per output revolution.',
    voltage: 5,
    minVoltage: 5,
    maxVoltage: 12,
    currentRequirements: { typicalMa: 200, maxMa: 550, note: 'Two phases energised at a time on the 5 V variant.' },
    motorRequirements: {
      motorType: 'stepper',
      channels: 4,
      requiresDriver: true,
      requiresExternalSupply: true,
      supplyVoltageMin: 5,
      supplyVoltageMax: 12,
      stepsPerRevolution: 2048,
      controlSignal: 'step_dir',
      rpm: 15,
    },
    pins: [
      pin('IN1', 'digital', 'input', { required: true, signal: 'Phase A', aliases: ['A'] }),
      pin('IN2', 'digital', 'input', { required: true, signal: 'Phase B', aliases: ['B'] }),
      pin('IN3', 'digital', 'input', { required: true, signal: 'Phase C', aliases: ['C'] }),
      pin('IN4', 'digital', 'input', { required: true, signal: 'Phase D', aliases: ['D'] }),
      pin('VCC', 'power', 'power', { required: true, voltage: 5, aliases: ['+', '5V', 'V+'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['-', 'V-'] }),
    ],
    libraryRequirements: [
      { name: 'Stepper', import: 'Stepper.h', manager: 'arduino', purpose: 'Built-in 4-phase stepper sequencing', builtIn: true },
      { name: 'AccelStepper', import: 'AccelStepper.h', manager: 'arduino', purpose: 'Acceleration profiles for smoother motion', builtIn: false },
    ],
    keywords: ['stepper', '28byj48', 'uln2003', 'unipolar', 'geared'],
    aliases: ['stepper motor', '28byj-48', '28byj48', 'uln2003 stepper', 'unipolar stepper'],
    simulator: { supported: false, notes: 'No verified simulator part; represent as four digital loads if needed.' },
    metadata: { electrical: true, halfStepSequence: true, driverIntegrated: 'ULN2003A' },
  }),

  def({
    id: 'stepper-motor-nema17',
    name: 'NEMA 17 bipolar stepper motor',
    category: 'motor',
    description:
      '1.8°/step (200 steps per revolution) bipolar hybrid stepper, 4 wires (2 coils). Requires a chopper driver such as the A4988; coil current typically 1–2 A so it cannot be driven from logic pins.',
    voltage: 12,
    minVoltage: 8,
    maxVoltage: 24,
    currentRequirements: { typicalMa: 1500, maxMa: 2000, note: 'Per-coil rated current; set via the driver VREF trimmer.' },
    motorRequirements: {
      motorType: 'stepper',
      channels: 2,
      requiresDriver: true,
      requiresExternalSupply: true,
      supplyVoltageMin: 8,
      supplyVoltageMax: 24,
      stepsPerRevolution: 200,
      controlSignal: 'step_dir',
      holdingTorqueKgCm: 4,
    },
    pins: [
      pin('COIL_A1', 'motor', 'input', { required: true, aliases: ['A+', '1A', 'BLACK'] }),
      pin('COIL_A2', 'motor', 'input', { required: true, aliases: ['A-', '1B', 'GREEN'] }),
      pin('COIL_B1', 'motor', 'input', { required: true, aliases: ['B+', '2A', 'RED'] }),
      pin('COIL_B2', 'motor', 'input', { required: true, aliases: ['B-', '2B', 'BLUE'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    libraryRequirements: [
      { name: 'AccelStepper', import: 'AccelStepper.h', manager: 'arduino', purpose: 'Step/dir control with acceleration', builtIn: false },
    ],
    keywords: ['stepper', 'nema17', 'bipolar', 'cnc', '3d printer'],
    aliases: ['nema 17', 'nema17', 'bipolar stepper', '17hs4401'],
    simulator: {
      part: 'wokwi-stepper-motor',
      supported: true,
      notes: 'Velxio drives the motor from a paired A4988: each STEP rising edge advances the rotor one (micro)step in the DIR direction. Coil pins map A±/B±; torque, inertia and stall are not modelled.',
    },
    metadata: { electrical: true, noSupplyPins: true, incompatibleReason: 'Requires a chopper driver (A4988/DRV8825) between MCU and motor coils.' },
  }),

  def({
    id: 'l298n-motor-driver',
    name: 'L298N dual H-bridge motor driver',
    category: 'motor_driver',
    description:
      'Dual full-bridge driver module (up to 2 A continuous per channel, 3 A peak). Motor supply 5–35 V on the screw terminal; on-board 78M05 regulator feeds the logic when the supply is above ~7 V. Two logic pins per channel set direction, ENA/ENB accept PWM for speed. Expect a ~1.8–2.5 V saturation drop, so motors see supply minus that drop.',
    voltage: 5,
    minVoltage: 5,
    maxVoltage: 35,
    currentRequirements: { typicalMa: 500, maxMa: 3000, note: 'Per-channel continuous 2 A, peak 3 A; quiescent logic current is small.' },
    motorRequirements: {
      motorType: 'dc',
      channels: 2,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 5,
      supplyVoltageMax: 35,
      maxCurrentPerChannelMa: 2000,
      controlSignal: 'digital',
      logicVoltage: 5,
    },
    pins: [
      pin('IN1', 'digital', 'input', { required: true, signal: 'Channel A direction bit 0', aliases: ['INA1', 'A_IN1'] }),
      pin('IN2', 'digital', 'input', { required: true, signal: 'Channel A direction bit 1', aliases: ['INA2', 'A_IN2'] }),
      pin('IN3', 'digital', 'input', { required: true, signal: 'Channel B direction bit 0', aliases: ['INB1', 'B_IN1'] }),
      pin('IN4', 'digital', 'input', { required: true, signal: 'Channel B direction bit 1', aliases: ['INB2', 'B_IN2'] }),
      pin('ENA', 'enable', 'input', { required: false, signal: 'Channel A speed PWM (jumper pulled HIGH by default)', aliases: ['EN_A', 'PWMA'] }),
      pin('ENB', 'enable', 'input', { required: false, signal: 'Channel B speed PWM (jumper pulled HIGH by default)', aliases: ['EN_B', 'PWMB'] }),
      pin('OUT1', 'motor', 'output', { required: true, signal: 'Channel A output +', aliases: ['OA1', 'MOTOR_A+'] }),
      pin('OUT2', 'motor', 'output', { required: true, signal: 'Channel A output -', aliases: ['OA2', 'MOTOR_A-'] }),
      pin('OUT3', 'motor', 'output', { required: true, signal: 'Channel B output +', aliases: ['OB1', 'MOTOR_B+'] }),
      pin('OUT4', 'motor', 'output', { required: true, signal: 'Channel B output -', aliases: ['OB2', 'MOTOR_B-'] }),
      pin('+12V', 'power', 'power', { required: true, voltage: 12, signal: 'Motor supply input (5–35 V)', aliases: ['VMOT', 'VS', 'VCC_MOTOR', 'POWER'] }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Common ground — must be tied to the MCU ground', aliases: ['VSS', 'COM'] }),
      pin('5V', 'power', 'power', { required: false, voltage: 5, signal: 'Regulated 5 V out (supply > 7 V) or logic supply in (supply <= 7 V)', aliases: ['VCC', 'LOGIC_5V'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['l298n', 'motor driver', 'h-bridge', 'hbridge', 'dual', 'dc motor driver'],
    aliases: ['l298n', 'l298', 'l298d', 'dual h-bridge', 'h bridge module'],
    exampleUsage: ['Two DC motors of an RC car', 'Bipolar stepper (uses IN1–IN4 as phase drive)'],
    simulator: { supported: false, notes: 'No verified simulator part; model the two channels as PWM sources into motor loads.' },
    metadata: {
      electrical: true,
      saturationDropV: 2.0,
      onboardRegulator: '78M05',
      regulatorInputThresholdV: 7,
      enableJumpersRemoveForPwm: true,
      heatSinkRequired: 'Recommended above ~1 A per channel',
      channelMap: [
        { channel: 'A', inputs: ['IN1', 'IN2'], enable: 'ENA', outputs: ['OUT1', 'OUT2'] },
        { channel: 'B', inputs: ['IN3', 'IN4'], enable: 'ENB', outputs: ['OUT3', 'OUT4'] },
      ],
    },
  }),

  def({
    id: 'l293d-motor-driver',
    name: 'L293D quad half-bridge driver',
    category: 'motor_driver',
    description:
      'DIP-16 driver with internal clamp diodes: two full bridges (600 mA continuous, 1.2 A peak per channel) or four half-bridges. Separate logic (VCC1, 4.5–7 V) and motor (VCC2, 4.5–36 V) supplies, and four ground pins that must all be tied together.',
    voltage: 5,
    minVoltage: 4.5,
    maxVoltage: 36,
    currentRequirements: { typicalMa: 300, maxMa: 1200, note: '600 mA continuous per channel, 1.2 A non-repetitive peak.' },
    motorRequirements: {
      motorType: 'dc',
      channels: 2,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 4.5,
      supplyVoltageMax: 36,
      maxCurrentPerChannelMa: 600,
      controlSignal: 'digital',
      logicVoltage: 5,
    },
    pins: [
      pin('EN1_2', 'enable', 'input', { required: true, signal: 'Enable for channel 1 (pin 1)', aliases: ['EN1', 'ENABLE1_2', 'ENA'] }),
      pin('IN1', 'digital', 'input', { required: true, signal: 'Input 1 (pin 2)', aliases: ['1A', 'A1'] }),
      pin('OUT1', 'motor', 'output', { required: true, signal: 'Output 1 (pin 3)', aliases: ['1Y', 'Y1'] }),
      pin('GND4', 'ground', 'ground', { required: true, signal: 'Ground (pin 4)', aliases: ['GND'] }),
      pin('GND5', 'ground', 'ground', { required: true, signal: 'Ground (pin 5)', aliases: ['GND'] }),
      pin('OUT2', 'motor', 'output', { required: true, signal: 'Output 2 (pin 6)', aliases: ['2Y', 'Y2'] }),
      pin('IN2', 'digital', 'input', { required: true, signal: 'Input 2 (pin 7)', aliases: ['2A', 'A2'] }),
      pin('VCC2', 'power', 'power', { required: true, voltage: 6, signal: 'Motor supply 4.5–36 V (pin 8)', aliases: ['VM', 'VMOTOR'] }),
      pin('EN3_4', 'enable', 'input', { required: true, signal: 'Enable for channel 2 (pin 9)', aliases: ['EN2', 'ENABLE3_4', 'ENB'] }),
      pin('IN3', 'digital', 'input', { required: true, signal: 'Input 3 (pin 10)', aliases: ['3A', 'B1'] }),
      pin('OUT3', 'motor', 'output', { required: true, signal: 'Output 3 (pin 11)', aliases: ['3Y'] }),
      pin('GND12', 'ground', 'ground', { required: true, signal: 'Ground (pin 12)', aliases: ['GND'] }),
      pin('GND13', 'ground', 'ground', { required: true, signal: 'Ground (pin 13)', aliases: ['GND'] }),
      pin('OUT4', 'motor', 'output', { required: true, signal: 'Output 4 (pin 14)', aliases: ['4Y'] }),
      pin('IN4', 'digital', 'input', { required: true, signal: 'Input 4 (pin 15)', aliases: ['4A', 'B2'] }),
      pin('VCC1', 'power', 'power', { required: true, voltage: 5, signal: 'Logic supply 4.5–7 V (pin 16)', aliases: ['VCC', 'VLOGIC'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['l293d', 'l293', 'motor driver', 'h-bridge', 'quad half bridge'],
    aliases: ['l293d', 'l293', 'l293d ic'],
    simulator: { supported: false, notes: 'No verified simulator part.' },
    metadata: {
      electrical: true,
      package: 'DIP-16',
      internalClampDiodes: true,
      channelMap: [
        { channel: 'A', inputs: ['IN1', 'IN2'], enable: 'EN1_2', outputs: ['OUT1', 'OUT2'] },
        { channel: 'B', inputs: ['IN3', 'IN4'], enable: 'EN3_4', outputs: ['OUT3', 'OUT4'] },
      ],
    },
  }),

  def({
    id: 'tb6612fng-motor-driver',
    name: 'TB6612FNG dual motor driver breakout',
    category: 'motor_driver',
    description:
      'MOSFET dual H-bridge breakout: 1.2 A continuous (3.2 A peak) per channel, motor supply 2.5–13.5 V, logic 2.7–5.5 V. Much lower voltage drop than the L298N so motors get nearly the full supply. STBY must be pulled high for any output.',
    voltage: 3.3,
    minVoltage: 2.7,
    maxVoltage: 5.5,
    currentRequirements: { typicalMa: 400, maxMa: 3200, note: '1.2 A continuous per channel, 3.2 A peak.' },
    motorRequirements: {
      motorType: 'dc',
      channels: 2,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 2.5,
      supplyVoltageMax: 13.5,
      maxCurrentPerChannelMa: 1200,
      controlSignal: 'pwm',
      logicVoltage: 3.3,
    },
    pins: [
      pin('VM', 'power', 'power', { required: true, voltage: 7.4, signal: 'Motor supply 2.5–13.5 V', aliases: ['VMOT', 'VCC_MOTOR'] }),
      pin('VCC', 'power', 'power', { required: true, voltage: 3.3, signal: 'Logic supply 2.7–5.5 V', aliases: ['VLOGIC', 'VDD'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['VSS'] }),
      pin('STBY', 'enable', 'input', { required: true, signal: 'Standby — drive HIGH to enable outputs', aliases: ['STBY', 'ENABLE'] }),
      pin('AIN1', 'digital', 'input', { required: true, signal: 'Channel A direction bit 0', aliases: ['A_IN1', 'IN1'] }),
      pin('AIN2', 'digital', 'input', { required: true, signal: 'Channel A direction bit 1', aliases: ['A_IN2', 'IN2'] }),
      pin('PWMA', 'pwm', 'input', { required: true, signal: 'Channel A speed PWM', aliases: ['ENA', 'A_PWM'] }),
      pin('AO1', 'motor', 'output', { required: true, signal: 'Channel A output +', aliases: ['A01', 'MOTOR_A+'] }),
      pin('AO2', 'motor', 'output', { required: true, signal: 'Channel A output -', aliases: ['A02', 'MOTOR_A-'] }),
      pin('BIN1', 'digital', 'input', { required: true, signal: 'Channel B direction bit 0', aliases: ['B_IN1', 'IN3'] }),
      pin('BIN2', 'digital', 'input', { required: true, signal: 'Channel B direction bit 1', aliases: ['B_IN2', 'IN4'] }),
      pin('PWMB', 'pwm', 'input', { required: true, signal: 'Channel B speed PWM', aliases: ['ENB', 'B_PWM'] }),
      pin('BO1', 'motor', 'output', { required: true, signal: 'Channel B output +', aliases: ['B01', 'MOTOR_B+'] }),
      pin('BO2', 'motor', 'output', { required: true, signal: 'Channel B output -', aliases: ['B02', 'MOTOR_B-'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['tb6612', 'tb6612fng', 'motor driver', 'dual', 'mosfet', 'low drop'],
    aliases: ['tb6612', 'tb6612fng', 'tb6612fng breakout'],
    simulator: { supported: false, notes: 'No verified simulator part.' },
    metadata: {
      electrical: true,
      saturationDropV: 0.1,
      standbyPinRequired: true,
      channelMap: [
        { channel: 'A', inputs: ['AIN1', 'AIN2'], enable: 'PWMA', outputs: ['AO1', 'AO2'] },
        { channel: 'B', inputs: ['BIN1', 'BIN2'], enable: 'PWMB', outputs: ['BO1', 'BO2'] },
      ],
    },
  }),

  def({
    id: 'a4988-stepper-driver',
    name: 'A4988 stepper driver breakout',
    category: 'motor_driver',
    description:
      'Microstepping chopper driver for bipolar steppers: STEP + DIR interface, 1/1 to 1/16 microstepping, motor supply 8–35 V, logic 3–5.5 V, up to 2 A per coil with a heat sink (≈1 A without). Requires a bulk capacitor across VMOT/GND and VREF trimming for coil current.',
    voltage: 3.3,
    minVoltage: 3,
    maxVoltage: 5.5,
    currentRequirements: { typicalMa: 1000, maxMa: 2000, note: 'Per-coil current set by VREF: I = VREF / (8 x Rsense).' },
    motorRequirements: {
      motorType: 'stepper',
      channels: 1,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 8,
      supplyVoltageMax: 35,
      maxCurrentPerChannelMa: 2000,
      controlSignal: 'step_dir',
      logicVoltage: 3.3,
    },
    pins: [
      pin('VMOT', 'power', 'power', { required: true, voltage: 12, signal: 'Motor supply 8–35 V', aliases: ['VM', 'VCC_MOTOR'] }),
      pin('GND_MOT', 'ground', 'ground', { required: true, aliases: ['GNDMOT', 'GND'] }),
      pin('1B', 'motor', 'output', { required: true, signal: 'Coil A output -', aliases: ['B1'] }),
      pin('1A', 'motor', 'output', { required: true, signal: 'Coil A output +', aliases: ['A1'] }),
      pin('2A', 'motor', 'output', { required: true, signal: 'Coil B output +', aliases: ['A2'] }),
      pin('2B', 'motor', 'output', { required: true, signal: 'Coil B output -', aliases: ['B2'] }),
      pin('VDD', 'power', 'power', { required: true, voltage: 5, signal: 'Logic supply 3–5.5 V', aliases: ['VCC'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['GND_LOGIC'] }),
      pin('STP', 'digital', 'input', { required: true, signal: 'Step pulse', aliases: ['STEP'] }),
      pin('DIR', 'digital', 'input', { required: true, signal: 'Direction' }),
      pin('EN', 'enable', 'input', { required: false, signal: 'Enable (active low)', aliases: ['ENABLE'] }),
      pin('MS1', 'digital', 'input', { required: false, signal: 'Microstepping select 1' }),
      pin('MS2', 'digital', 'input', { required: false, signal: 'Microstepping select 2' }),
      pin('MS3', 'digital', 'input', { required: false, signal: 'Microstepping select 3' }),
      pin('RST', 'control', 'input', { required: false, signal: 'Reset (active low) — usually jumpered to SLP' }),
      pin('SLP', 'control', 'input', { required: false, signal: 'Sleep (active low) — usually jumpered to RST' }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['a4988', 'stepper driver', 'microstepping', 'step dir', 'pololu'],
    aliases: ['a4988', 'pololu a4988', 'stepstick'],
    simulator: {
      part: 'wokwi-a4988',
      supported: true,
      notes: 'Velxio advances a paired stepper motor on each STEP rising edge in the DIR direction (with MS1-MS3 microstepping selected). VREF trimming, decay mode and the fault protections are not modelled.',
    },
    metadata: { electrical: true, requiresBulkCapacitor: true, vrefFormula: 'Imax = VREF / (8 x Rsense)', microstepping: [1, 2, 4, 8, 16] },
  }),
  def({
    id: 'drv8833-motor-driver',
    name: 'DRV8833 dual motor driver carrier',
    category: 'motor_driver',
    description:
      'Low-voltage MOSFET dual H-bridge (TI DRV8833): 2.7-10.8 V motor supply, 1.2 A continuous and 2 A peak per channel, no separate logic supply needed because the inputs are 3 V/5 V compatible. Each channel takes two PWM-capable inputs (IN1/IN2) instead of a direction + enable pair, and nSLEEP must be high for the outputs to work.',
    voltage: 3.3,
    minVoltage: 2.7,
    maxVoltage: 10.8,
    currentRequirements: { typicalMa: 400, maxMa: 2000, note: '1.2 A continuous per channel, 2 A peak; channels can be paralleled for 2.4 A.' },
    motorRequirements: {
      motorType: 'dc',
      channels: 2,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 2.7,
      supplyVoltageMax: 10.8,
      maxCurrentPerChannelMa: 1200,
      controlSignal: 'pwm',
      logicVoltage: 3.3,
    },
    pins: [
      pin('VIN', 'power', 'power', { required: true, voltage: 7.4, signal: 'Reverse-protected motor supply 2.7-10.8 V', aliases: ['VM', 'VMOT', 'VCC'] }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Common ground with the MCU', aliases: ['-', 'VSS'] }),
      pin('AIN1', 'pwm', 'input', { required: true, signal: 'Channel A input 1 (PWM capable)', aliases: ['IN1', 'A_IN1'] }),
      pin('AIN2', 'pwm', 'input', { required: true, signal: 'Channel A input 2 (PWM capable)', aliases: ['IN2', 'A_IN2'] }),
      pin('BIN1', 'pwm', 'input', { required: true, signal: 'Channel B input 1 (PWM capable)', aliases: ['IN3', 'B_IN1'] }),
      pin('BIN2', 'pwm', 'input', { required: true, signal: 'Channel B input 2 (PWM capable)', aliases: ['IN4', 'B_IN2'] }),
      pin('AOUT1', 'motor', 'output', { required: true, signal: 'Channel A output 1', aliases: ['AO1', 'MOTOR_A+'] }),
      pin('AOUT2', 'motor', 'output', { required: true, signal: 'Channel A output 2', aliases: ['AO2', 'MOTOR_A-'] }),
      pin('BOUT1', 'motor', 'output', { required: true, signal: 'Channel B output 1', aliases: ['BO1', 'MOTOR_B+'] }),
      pin('BOUT2', 'motor', 'output', { required: true, signal: 'Channel B output 2', aliases: ['BO2', 'MOTOR_B-'] }),
      pin('SLP', 'enable', 'input', { required: false, signal: 'nSLEEP — pull HIGH to enable (pulled high on most carriers)', aliases: ['nSLEEP', 'SLEEP', 'STBY'] }),
      pin('FLT', 'digital', 'output', { required: false, signal: 'nFAULT — open-drain, LOW on over-current / over-temperature / under-voltage', aliases: ['nFAULT', 'FAULT'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['drv8833', 'motor driver', 'h-bridge', 'dual', 'low voltage', 'mosfet'],
    aliases: ['drv8833', 'drv 8833', 'cjmcu-8833'],
    exampleUsage: ['Two N20 gear motors on a small line-following robot', 'Bipolar micro stepper driven as two H-bridges'],
    simulator: { supported: false, notes: 'No verified simulator part.' },
    metadata: {
      electrical: true,
      saturationDropV: 0.36,
      logicSupplyRequired: false,
      inputMode: 'in-in (both inputs PWM capable)',
      channelMap: [
        { channel: 'A', inputs: ['AIN1', 'AIN2'], outputs: ['AOUT1', 'AOUT2'] },
        { channel: 'B', inputs: ['BIN1', 'BIN2'], outputs: ['BOUT1', 'BOUT2'] },
      ],
    },
  }),

  def({
    id: 'bts7960-motor-driver',
    name: 'BTS7960 (IBT-2) high-current half-bridge pair',
    category: 'motor_driver',
    description:
      'Two BTS7960 half-bridges forming one very high-current H-bridge: 6-27 V motor supply, 43 A peak (realistically ~10 A continuous with cooling), 3.3 V/5 V logic. RPWM and LPWM set direction and speed; R_EN and L_EN must both be HIGH to enable, and R_IS / L_IS give an analog current-sense signal.',
    voltage: 5,
    minVoltage: 5,
    maxVoltage: 27,
    currentRequirements: { typicalMa: 10000, maxMa: 43000, note: '43 A peak per the datasheet; ~10 A continuous is realistic without forced airflow.' },
    motorRequirements: {
      motorType: 'dc',
      channels: 1,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 6,
      supplyVoltageMax: 27,
      maxCurrentPerChannelMa: 43000,
      controlSignal: 'pwm',
      logicVoltage: 5,
    },
    pins: [
      pin('RPWM', 'pwm', 'input', { required: true, signal: 'Forward PWM input (active high)', aliases: ['R_PWM', 'PWM1', 'FORWARD'] }),
      pin('LPWM', 'pwm', 'input', { required: true, signal: 'Reverse PWM input (active high)', aliases: ['L_PWM', 'PWM2', 'REVERSE'] }),
      pin('R_EN', 'enable', 'input', { required: true, signal: 'Forward half-bridge enable (active high)', aliases: ['REN', 'R-EN'] }),
      pin('L_EN', 'enable', 'input', { required: true, signal: 'Reverse half-bridge enable (active high)', aliases: ['LEN', 'L-EN'] }),
      pin('R_IS', 'analog', 'output', { required: false, signal: 'Forward-side current sense / alarm output', aliases: ['RIS'] }),
      pin('L_IS', 'analog', 'output', { required: false, signal: 'Reverse-side current sense / alarm output', aliases: ['LIS'] }),
      pin('VCC', 'power', 'power', { required: true, voltage: 5, signal: 'Logic supply 3.3-5 V from the MCU', aliases: ['5V', 'VDD'] }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Logic ground — must be common with the MCU', aliases: ['-'] }),
      pin('B+', 'power', 'power', { required: true, voltage: 12, signal: 'Motor battery positive 6-27 V', aliases: ['VM', 'VBAT', 'M+', 'POWER+'] }),
      pin('B-', 'ground', 'ground', { required: true, signal: 'Motor battery negative', aliases: ['POWER-', 'PGND'] }),
      pin('M+', 'motor', 'output', { required: true, signal: 'Motor output +', aliases: ['MOTOR+', 'OUT1'] }),
      pin('M-', 'motor', 'output', { required: true, signal: 'Motor output -', aliases: ['MOTOR-', 'OUT2'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['bts7960', 'ibt-2', 'ibt2', 'high current', 'motor driver', 'h-bridge', '43a'],
    aliases: ['bts7960', 'ibt-2', 'ibt2', 'bts7960b', 'high current motor driver'],
    exampleUsage: ['12 V wheelchair or scooter motor', '12 V linear actuator needing 3 A stall'],
    simulator: { supported: false, notes: 'No verified simulator part.' },
    metadata: {
      electrical: true,
      pwmFrequencyMaxHz: 25000,
      protections: ['over-current', 'over-temperature', 'under-voltage'],
      neverBothPwmHigh: 'Driving RPWM and LPWM high simultaneously shoots through the bridge — always zero one side first.',
      channelMap: [{ channel: 'A', inputs: ['RPWM', 'LPWM'], enable: 'R_EN+L_EN', outputs: ['M+', 'M-'] }],
    },
  }),

  def({
    id: 'drv8825-stepper-driver',
    name: 'DRV8825 stepper driver breakout',
    category: 'motor_driver',
    description:
      'Higher-voltage alternative to the A4988: 8.2-45 V motor supply, up to 2.2 A per coil with cooling, 1/32 microstepping. Pin-compatible with the A4988 footprint but the microstep table and the VREF formula differ (Imax = VREF x 2).',
    voltage: 3.3,
    minVoltage: 2.5,
    maxVoltage: 5.25,
    currentRequirements: { typicalMa: 1000, maxMa: 2200, note: 'Per-coil current set by VREF: Imax = VREF x 2 on standard Pololu-style carriers.' },
    motorRequirements: {
      motorType: 'stepper',
      channels: 1,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 8.2,
      supplyVoltageMax: 45,
      maxCurrentPerChannelMa: 2200,
      controlSignal: 'step_dir',
      logicVoltage: 3.3,
    },
    pins: [
      pin('VMOT', 'power', 'power', { required: true, voltage: 24, signal: 'Motor supply 8.2-45 V', aliases: ['VM', 'VCC_MOTOR'] }),
      pin('GND_MOT', 'ground', 'ground', { required: true, aliases: ['GNDMOT', 'PGND'] }),
      pin('A1', 'motor', 'output', { required: true, signal: 'Coil A output +' }),
      pin('A2', 'motor', 'output', { required: true, signal: 'Coil A output -' }),
      pin('B1', 'motor', 'output', { required: true, signal: 'Coil B output +' }),
      pin('B2', 'motor', 'output', { required: true, signal: 'Coil B output -' }),
      pin('VDD', 'power', 'power', { required: true, voltage: 5, signal: 'Logic supply 2.5-5.25 V', aliases: ['VCC'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['GND_LOGIC'] }),
      pin('STEP', 'digital', 'input', { required: true, signal: 'Step pulse (rising edge)', aliases: ['STP'] }),
      pin('DIR', 'digital', 'input', { required: true, signal: 'Direction' }),
      pin('EN', 'enable', 'input', { required: false, signal: 'Enable (active low)', aliases: ['ENABLE', 'nEN'] }),
      pin('M0', 'digital', 'input', { required: false, signal: 'Microstep select 0', aliases: ['MS1'] }),
      pin('M1', 'digital', 'input', { required: false, signal: 'Microstep select 1', aliases: ['MS2'] }),
      pin('M2', 'digital', 'input', { required: false, signal: 'Microstep select 2', aliases: ['MS3'] }),
      pin('RST', 'control', 'input', { required: false, signal: 'Reset (active low) — usually jumpered to SLP' }),
      pin('SLP', 'control', 'input', { required: false, signal: 'Sleep (active low) — usually jumpered to RST' }),
      pin('FAULT', 'digital', 'output', { required: false, signal: 'Open-drain fault output (over-current / over-temperature)', aliases: ['nFAULT'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    libraryRequirements: [
      { name: 'AccelStepper', import: 'AccelStepper.h', manager: 'arduino', purpose: 'Step/dir control with acceleration ramps', builtIn: false },
    ],
    keywords: ['drv8825', 'stepper driver', 'microstepping', '1/32', 'pololu', 'step dir'],
    aliases: ['drv8825', 'drv 8825', 'stepstick drv8825'],
    simulator: { supported: false },
    metadata: {
      electrical: true,
      requiresBulkCapacitor: true,
      vrefFormula: 'Imax = VREF x 2',
      microstepping: [1, 2, 4, 8, 16, 32],
      minStepPulseUs: 1.9,
    },
  }),

  def({
    id: 'tmc2209-stepper-driver',
    name: 'TMC2209 silent stepper driver',
    category: 'motor_driver',
    description:
      'StealthChop2 stepper driver for near-silent motion: 4.75-29 V motor supply, 1.4 A RMS (2 A peak) per coil, up to 1/256 interpolated microstepping and an optional single-wire UART for runtime current, microstep and StallGuard configuration. Also supports sensorless homing through the DIAG pin.',
    voltage: 3.3,
    minVoltage: 3,
    maxVoltage: 5.5,
    currentRequirements: { typicalMa: 1200, maxMa: 2000, note: '1.4 A RMS continuous per coil, 2 A peak; VREF or UART sets the limit.' },
    motorRequirements: {
      motorType: 'stepper',
      channels: 1,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 4.75,
      supplyVoltageMax: 29,
      maxCurrentPerChannelMa: 1400,
      controlSignal: 'step_dir',
      logicVoltage: 3.3,
    },
    pins: [
      pin('VM', 'power', 'power', { required: true, voltage: 24, signal: 'Motor supply 4.75-29 V', aliases: ['VMOT', 'VS'] }),
      pin('GND_MOT', 'ground', 'ground', { required: true, aliases: ['PGND', 'GND'] }),
      pin('OA1', 'motor', 'output', { required: true, signal: 'Coil A output 1', aliases: ['A1', 'M1A'] }),
      pin('OA2', 'motor', 'output', { required: true, signal: 'Coil A output 2', aliases: ['A2', 'M1B'] }),
      pin('OB1', 'motor', 'output', { required: true, signal: 'Coil B output 1', aliases: ['B1', 'M2A'] }),
      pin('OB2', 'motor', 'output', { required: true, signal: 'Coil B output 2', aliases: ['B2', 'M2B'] }),
      pin('VIO', 'power', 'power', { required: true, voltage: 3.3, signal: 'Logic supply 3-5 V', aliases: ['VDD', 'VCC_IO'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['GND_LOGIC'] }),
      pin('STEP', 'digital', 'input', { required: true, signal: 'Step pulse' }),
      pin('DIR', 'digital', 'input', { required: true, signal: 'Direction' }),
      pin('EN', 'enable', 'input', { required: false, signal: 'Enable (active low)', aliases: ['ENN', 'nEN'] }),
      pin('PDN_UART', 'uart', 'bidirectional', { required: false, signal: 'Single-wire UART for runtime configuration (1 kOhm series resistor when bridging TX/RX)', aliases: ['UART', 'PDN', 'TX/RX'] }),
      pin('MS1', 'digital', 'input', { required: false, signal: 'Microstep / UART address select 1', aliases: ['AD0'] }),
      pin('MS2', 'digital', 'input', { required: false, signal: 'Microstep / UART address select 2', aliases: ['AD1'] }),
      pin('DIAG', 'digital', 'output', { required: false, signal: 'StallGuard / diagnostic output used for sensorless homing' }),
      pin('INDEX', 'digital', 'output', { required: false, signal: 'Pulses once per electrical full step cycle' }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    libraryRequirements: [
      { name: 'TMCStepper', import: 'TMCStepper.h', manager: 'arduino', purpose: 'UART configuration of current, microsteps and StallGuard', builtIn: false },
      { name: 'AccelStepper', import: 'AccelStepper.h', manager: 'arduino', purpose: 'Motion profiles on the STEP/DIR interface', builtIn: false },
    ],
    keywords: ['tmc2209', 'silent', 'stealthchop', 'stallguard', 'stepper driver', 'trinamic'],
    aliases: ['tmc2209', 'tmc 2209', 'silent stepper driver'],
    exampleUsage: ['Quiet 3D-printer or camera-slider axis', 'Sensorless-homing linear stage'],
    simulator: { supported: false },
    metadata: {
      electrical: true,
      requiresBulkCapacitor: true,
      microstepping: [1, 2, 4, 8, 16, 32, 64, 128, 256],
      features: ['StealthChop2', 'SpreadCycle', 'StallGuard4', 'CoolStep'],
      vrefFormula: 'Irms = (VREF x 1.77) / 2.5 on common BigTreeTech carriers; prefer UART configuration.',
    },
  }),

  def({
    id: 'uln2003-darlington-array',
    name: 'ULN2003A Darlington transistor array',
    category: 'motor_driver',
    description:
      'Seven open-collector Darlington sinks (500 mA each, 50 V max) with integrated free-wheeling diodes on the COM pin. The workhorse for switching relays, unipolar steppers, small solenoids and lamps from logic pins — it only sinks current, so the load sits between the supply and the output.',
    voltage: 5,
    minVoltage: 3,
    maxVoltage: 50,
    currentRequirements: { typicalMa: 300, maxMa: 500, note: '500 mA per channel; total package dissipation limits how many channels can run at full current simultaneously.' },
    pins: [
      pin('IN1', 'digital', 'input', { required: true, signal: 'Channel 1 input (pin 1)', aliases: ['1B'] }),
      pin('IN2', 'digital', 'input', { required: false, signal: 'Channel 2 input (pin 2)', aliases: ['2B'] }),
      pin('IN3', 'digital', 'input', { required: false, signal: 'Channel 3 input (pin 3)', aliases: ['3B'] }),
      pin('IN4', 'digital', 'input', { required: false, signal: 'Channel 4 input (pin 4)', aliases: ['4B'] }),
      pin('IN5', 'digital', 'input', { required: false, signal: 'Channel 5 input (pin 5)', aliases: ['5B'] }),
      pin('IN6', 'digital', 'input', { required: false, signal: 'Channel 6 input (pin 6)', aliases: ['6B'] }),
      pin('IN7', 'digital', 'input', { required: false, signal: 'Channel 7 input (pin 7)', aliases: ['7B'] }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Ground / emitter common (pin 8)', aliases: ['E', 'VSS'] }),
      pin('COM', 'power', 'power', { required: true, voltage: 12, signal: 'Free-wheeling diode common — tie to the load supply (pin 9)', aliases: ['COMMON', 'VCC', 'CD'] }),
      pin('OUT7', 'digital', 'output', { required: false, signal: 'Channel 7 open-collector output (pin 10)', aliases: ['7C'] }),
      pin('OUT6', 'digital', 'output', { required: false, signal: 'Channel 6 open-collector output (pin 11)', aliases: ['6C'] }),
      pin('OUT5', 'digital', 'output', { required: false, signal: 'Channel 5 open-collector output (pin 12)', aliases: ['5C'] }),
      pin('OUT4', 'digital', 'output', { required: false, signal: 'Channel 4 open-collector output (pin 13)', aliases: ['4C'] }),
      pin('OUT3', 'digital', 'output', { required: false, signal: 'Channel 3 open-collector output (pin 14)', aliases: ['3C'] }),
      pin('OUT2', 'digital', 'output', { required: false, signal: 'Channel 2 open-collector output (pin 15)', aliases: ['2C'] }),
      pin('OUT1', 'digital', 'output', { required: true, signal: 'Channel 1 open-collector output (pin 16)', aliases: ['1C'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['uln2003', 'darlington', 'driver array', 'sink', 'relay driver', 'unipolar stepper'],
    aliases: ['uln2003', 'uln2003a', 'darlington array', 'uln2803'],
    exampleUsage: ['Driving four relay coils from four GPIOs', 'Unipolar 28BYJ-48 stepper phases'],
    simulator: { supported: false },
    metadata: {
      electrical: true,
      package: 'DIP-16',
      channels: 7,
      sinkOnly: true,
      integratedFlybackDiodes: true,
      saturationDropV: 1.1,
    },
  }),

  def({
    id: 'mosfet-module-irf520',
    name: 'IRF520 MOSFET switch module',
    category: 'motor_driver',
    description:
      'Single low-side N-channel MOSFET switch board for DC loads up to 24 V. Convenient for fans, LED strips, pumps and solenoids, but note the IRF520 is not a true logic-level FET: at 5 V gate drive it is only partially enhanced, so keep continuous current under ~1 A on this module and prefer an IRLZ44N/AO3400-based board for heavier loads.',
    voltage: 5,
    minVoltage: 3.3,
    maxVoltage: 24,
    currentRequirements: { typicalMa: 500, maxMa: 5000, note: 'Module traces and the un-heatsinked TO-220 realistically allow ~1 A continuous despite the 9 A device rating.' },
    pins: [
      pin('SIG', 'pwm', 'input', { required: true, signal: 'Gate drive from the MCU (PWM capable)', aliases: ['PWM', 'IN', 'SIGNAL'] }),
      pin('VCC', 'power', 'power', { required: false, voltage: 5, signal: 'Logic reference supply', aliases: ['5V', '+'] }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Common ground with the MCU and the load supply', aliases: ['-'] }),
      pin('V+', 'power', 'power', { required: true, voltage: 12, signal: 'Load supply input (up to 24 V)', aliases: ['VIN', 'POWER+'] }),
      pin('V-', 'ground', 'ground', { required: true, signal: 'Load supply ground', aliases: ['POWER-'] }),
      pin('OUT+', 'motor', 'output', { required: true, signal: 'Load positive (passes V+ straight through)', aliases: ['LOAD+'] }),
      pin('OUT-', 'motor', 'output', { required: true, signal: 'Load negative — switched to ground by the MOSFET', aliases: ['LOAD-'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['mosfet', 'irf520', 'switch', 'low side', 'pwm', 'led strip', 'fan driver'],
    aliases: ['irf520', 'mosfet module', 'mosfet switch', 'irf520n module'],
    exampleUsage: ['PWM speed control of a 12 V fan', 'Switching a 12 V solenoid valve', 'Dimming a single-colour LED strip'],
    simulator: { supported: false },
    metadata: {
      electrical: true,
      switchSide: 'low',
      logicLevelGate: false,
      notes: 'Add an external flyback diode for inductive loads; this module does not include one.',
      betterAlternatives: ['IRLZ44N', 'AO3400', 'IRLB8721'],
    },
  }),

  def({
    id: 'pca9685-servo-driver',
    name: 'PCA9685 16-channel PWM/servo driver',
    category: 'motor_driver',
    description:
      'I2C 16-channel 12-bit PWM generator with one shared frequency (24 Hz-1526 Hz) for all channels. Standard way to drive up to 16 hobby servos or LED channels from two MCU pins; boards are chainable to 62 addresses. The servo power rail (V+) must come from a separate supply, not the MCU regulator.',
    voltage: 3.3,
    minVoltage: 2.3,
    maxVoltage: 5.5,
    currentRequirements: { typicalMa: 10, maxMa: 25, note: 'Logic-side current only; the servos draw from V+.' },
    motorRequirements: {
      motorType: 'servo',
      channels: 16,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 5,
      supplyVoltageMax: 6,
      controlSignal: 'serial',
      logicVoltage: 3.3,
    },
    pins: [
      pin('VCC', 'power', 'power', { required: true, voltage: 3.3, signal: 'Logic supply 2.3-5.5 V', aliases: ['VDD', '3V3', '5V'] }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Common ground for logic and servo supply', aliases: ['-', 'VSS'] }),
      pin('SDA', 'i2c', 'bidirectional', { required: true, signal: 'I2C data', aliases: ['DATA'] }),
      pin('SCL', 'i2c', 'input', { required: true, signal: 'I2C clock', aliases: ['CLK'] }),
      pin('V+', 'power', 'power', { required: true, voltage: 5, signal: 'Servo power rail — feed from a dedicated 5-6 V supply', aliases: ['VSERVO', 'VCC_SERVO', 'POWER'] }),
      pin('OE', 'enable', 'input', { required: false, signal: 'Output enable (active low); leave unconnected to keep outputs enabled', aliases: ['nOE', 'ENABLE'] }),
      pin('PWM0', 'pwm', 'output', { required: false, signal: 'Channel 0 PWM output', aliases: ['CH0', '0'] }),
      pin('PWM15', 'pwm', 'output', { required: false, signal: 'Channel 15 PWM output', aliases: ['CH15', '15'] }),
      pin('EXTCLK', 'control', 'input', { required: false, signal: 'Optional external clock input' }),
    ],
    communicationProtocols: ['i2c'],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    libraryRequirements: [
      { name: 'Adafruit PWM Servo Driver Library', import: 'Adafruit_PWMServoDriver.h', manager: 'arduino', purpose: '12-bit PWM channel control over I2C', builtIn: false },
      { name: 'Wire', import: 'Wire.h', manager: 'arduino', purpose: 'I2C transport', builtIn: true },
    ],
    keywords: ['pca9685', 'servo driver', '16 channel', 'pwm', 'i2c', 'robot arm', 'hexapod'],
    aliases: ['pca9685', 'servo shield', '16 channel servo driver', 'pwm driver'],
    exampleUsage: ['Six-servo robotic arm from an ESP32', '18-servo hexapod using two chained boards'],
    simulator: { supported: false, notes: 'No verified simulator part; behaves as an I2C peripheral at 0x40 by default.' },
    metadata: {
      electrical: true,
      i2cAddress: '0x40 (0x40-0x7F selectable, 62 boards chainable)',
      channels: 16,
      pwmResolutionBits: 12,
      pwmFrequencyRangeHz: [24, 1526],
      servoFrequencyHz: 50,
      separateServoSupplyRequired: true,
    },
  }),

  def({
    id: 'servo-motor-mg90s',
    name: 'MG90S metal-gear micro servo',
    category: 'motor',
    description:
      'Metal-gear upgrade of the SG90 in the same 9 g footprint: 4.8-6 V, about 2.2 kg-cm at 6 V, ~700 mA stall. Same 50 Hz PWM interface; the metal gear train survives shock loads that strip the plastic SG90.',
    voltage: 5,
    minVoltage: 4.8,
    maxVoltage: 6,
    currentRequirements: { typicalMa: 150, maxMa: 700, note: 'Stall current; holding position with no load is a few mA.' },
    motorRequirements: {
      motorType: 'servo',
      requiresDriver: false,
      requiresExternalSupply: false,
      supplyVoltageMin: 4.8,
      supplyVoltageMax: 6,
      stallCurrentMa: 700,
      holdingTorqueKgCm: 2.2,
      controlSignal: 'pwm',
    },
    pins: [
      pin('SIGNAL', 'pwm', 'input', { required: true, signal: '50 Hz position PWM (0.5-2.4 ms)', aliases: ['S', 'SIG', 'PWM', 'ORANGE'] }),
      pin('VCC', 'power', 'power', { required: true, voltage: 5, aliases: ['+', 'RED'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['-', 'BROWN', 'BLACK'] }),
    ],
    libraryRequirements: [{ name: 'Servo', import: 'Servo.h', manager: 'arduino', purpose: 'Hardware timer servo PWM', builtIn: true }],
    keywords: ['servo', 'mg90s', 'metal gear', 'micro servo'],
    aliases: ['mg90s', 'mg90', 'metal gear micro servo'],
    simulator: { part: 'wokwi-servo', supported: true, notes: 'Simulated as a generic servo.' },
    metadata: { electrical: true, pwmFrequencyHz: 50, pulseRangeUs: [500, 2400], stallIsTransient: true },
  }),

  def({
    id: 'servo-continuous-fs90r',
    name: 'FS90R continuous-rotation servo',
    category: 'motor',
    description:
      'Continuous-rotation (360 degree) servo: the PWM pulse commands speed and direction rather than an angle. 1.5 ms is stop, shorter pulses spin one way and longer the other, with a trim pot to null the stop point. Gives a geared, self-contained drive wheel with no H-bridge.',
    voltage: 5,
    minVoltage: 4.8,
    maxVoltage: 6,
    currentRequirements: { typicalMa: 120, maxMa: 700, note: 'Stall current about 700 mA at 6 V.' },
    motorRequirements: {
      motorType: 'servo',
      requiresDriver: false,
      requiresExternalSupply: false,
      supplyVoltageMin: 4.8,
      supplyVoltageMax: 6,
      stallCurrentMa: 700,
      controlSignal: 'pwm',
      rpm: 110,
    },
    pins: [
      pin('SIGNAL', 'pwm', 'input', { required: true, signal: '50 Hz speed PWM: 1.5 ms stop, 1.0/2.0 ms full speed either way', aliases: ['S', 'SIG', 'PWM', 'ORANGE'] }),
      pin('VCC', 'power', 'power', { required: true, voltage: 5, aliases: ['+', 'RED'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['-', 'BROWN'] }),
    ],
    libraryRequirements: [{ name: 'Servo', import: 'Servo.h', manager: 'arduino', purpose: 'Speed command through the standard servo pulse', builtIn: true }],
    keywords: ['continuous rotation servo', 'fs90r', '360 servo', 'drive wheel', 'robot'],
    aliases: ['fs90r', 'continuous servo', '360 degree servo', 'continuous rotation servo'],
    exampleUsage: ['Two-wheel differential drive robot with no motor driver'],
    simulator: { part: 'wokwi-servo', supported: true, notes: 'Simulated as a generic servo; rotation is not modelled.' },
    metadata: { electrical: true, pwmFrequencyHz: 50, pulseRangeUs: [1000, 2000], stopPulseUs: 1500, continuousRotation: true, stallIsTransient: true },
  }),

  def({
    id: 'n20-gear-motor-encoder',
    name: 'N20 micro gear motor with magnetic encoder',
    category: 'motor',
    description:
      'Small 6 V N20 brushed gear motor with a two-channel Hall encoder on the rear shaft. The motor terminals need an H-bridge; the encoder is a separate 3.3-5 V logic device whose A/B outputs feed two interrupt-capable inputs for closed-loop speed or odometry.',
    voltage: 6,
    minVoltage: 3,
    maxVoltage: 12,
    currentRequirements: { typicalMa: 120, maxMa: 800, note: 'No-load ~40-70 mA; stall around 0.8 A at 6 V depending on the gear ratio.' },
    motorRequirements: {
      motorType: 'dc',
      requiresDriver: true,
      requiresExternalSupply: true,
      supplyVoltageMin: 3,
      supplyVoltageMax: 12,
      stallCurrentMa: 800,
      controlSignal: 'pwm',
      rpm: 200,
    },
    pins: [
      pin('M1', 'motor', 'input', { required: true, signal: 'Motor terminal 1', aliases: ['A', 'M+', 'MOTOR+'] }),
      pin('M2', 'motor', 'input', { required: true, signal: 'Motor terminal 2', aliases: ['B', 'M-', 'MOTOR-'] }),
      pin('ENC_VCC', 'power', 'power', { required: true, voltage: 3.3, signal: 'Encoder supply 3.3-5 V (separate from the motor supply)', aliases: ['VCC', 'C1_VCC', '+'] }),
      pin('ENC_GND', 'ground', 'ground', { required: true, signal: 'Encoder ground', aliases: ['GND', '-'] }),
      pin('ENC_A', 'digital', 'output', { required: true, signal: 'Encoder channel A (quadrature)', aliases: ['C1', 'A', 'OUT_A'], requiresCapability: ['interrupt'] }),
      pin('ENC_B', 'digital', 'output', { required: true, signal: 'Encoder channel B (quadrature, 90 degrees out of phase)', aliases: ['C2', 'B', 'OUT_B'], requiresCapability: ['interrupt'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['n20', 'gear motor', 'encoder', 'quadrature', 'odometry', 'closed loop', 'micro motor'],
    aliases: ['n20 motor', 'n20 gear motor', 'micro gear motor', 'encoder motor'],
    exampleUsage: ['PID speed control of a small robot wheel', 'Odometry for a line-following or maze robot'],
    simulator: { supported: false },
    metadata: {
      electrical: true,
      encoderCountsPerMotorRev: 7,
      encoderChannels: 2,
      gearRatioExample: '1:100 (700 counts per output shaft revolution in 1x mode)',
      driverRequired: 'Any dual H-bridge: TB6612FNG, DRV8833 or L298N.',
    },
  }),
];
