/** Motor and motor-driver seed entries. */

import type { ComponentDefinition } from '@/types/component';

import { def, pin } from './helpers';

export const MOTORS: ComponentDefinition[] = [
  def({
    id: 'dc-motor-generic-6v',
    name: 'DC gear motor (6 V)',
    category: 'motor',
    description:
      'Two-terminal brushed DC motor, typically 3–12 V with a gearbox. Direction is set by reversing polarity across the terminals; speed by PWM duty. Must be driven through an H-bridge — never from an MCU pin.',
    voltage: 6,
    minVoltage: 3,
    maxVoltage: 12,
    currentRequirements: {
      typicalMa: 250,
      maxMa: 1500,
      note: 'Free-run current at 6 V is roughly 150–300 mA; stall current is 5–10x that. Verify against the actual motor datasheet.',
    },
    motorRequirements: {
      motorType: 'dc',
      requiresDriver: true,
      requiresExternalSupply: true,
      supplyVoltageMin: 3,
      supplyVoltageMax: 12,
      stallCurrentMa: 1500,
      controlSignal: 'pwm',
      rpm: 200,
    },
    pins: [
      pin('A', 'motor', 'input', { required: true, signal: 'Motor terminal A', aliases: ['+', 'M+', '1', 'RED'] }),
      pin('B', 'motor', 'input', { required: true, signal: 'Motor terminal B', aliases: ['-', 'M-', '2', 'BLACK'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['dc motor', 'motor', 'gear motor', 'brushed', 'wheel', 'drive'],
    aliases: ['dc motor', 'motor', 'geared dc motor', 'tt motor', 'dc gear motor', 'bo motor'],
    exampleUsage: ['RC car wheel driven by an L298N OUT1/OUT2 pair', 'Conveyor belt driven through a TB6612FNG channel'],
    metadata: {
      electrical: true,
      notes: 'Add a flyback diode (or use a driver with built-in clamp diodes) to absorb back-EMF.',
      incompatibleReason: 'Stall current exceeds any MCU GPIO rating; an H-bridge driver is mandatory.',
    },
  }),

  def({
    id: 'servo-motor-sg90',
    name: 'SG90 micro servo',
    category: 'motor',
    description:
      '9 g hobby servo with an internal driver. Position is set by a 50 Hz PWM pulse of 0.5–2.5 ms. Draws 3.3 V/5 V logic and up to ~500 mA at stall, so a separate supply is recommended for multiple servos.',
    voltage: 5,
    minVoltage: 4.8,
    maxVoltage: 6,
    currentRequirements: { typicalMa: 100, maxMa: 500, note: 'Stall/holding current; idle is a few mA.' },
    motorRequirements: {
      motorType: 'servo',
      requiresDriver: false,
      requiresExternalSupply: false,
      supplyVoltageMin: 4.8,
      supplyVoltageMax: 6,
      stallCurrentMa: 500,
      holdingTorqueKgCm: 1.8,
      controlSignal: 'pwm',
    },
    pins: [
      pin('SIGNAL', 'pwm', 'input', { required: true, signal: '50 Hz position PWM (0.5–2.5 ms)', aliases: ['S', 'SIG', 'PWM', 'DATA', 'ORANGE'] }),
      pin('VCC', 'power', 'power', { required: true, voltage: 5, aliases: ['+', 'V+', 'RED'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['-', 'V-', 'BROWN', 'BLACK'] }),
    ],
    libraryRequirements: [
      { name: 'Servo', import: 'Servo.h', manager: 'arduino', purpose: 'Hardware timer based servo PWM', builtIn: true },
    ],
    keywords: ['servo', 'sg90', 'micro servo', 'position', 'angular', 'steering'],
    aliases: ['servo', 'sg90', 'micro servo', 'hobby servo', '9g servo'],
    exampleUsage: ['RC car steering', 'Sensor pan/tilt', 'Robotic arm joint'],
    simulator: { part: 'wokwi-servo', supported: true },
    metadata: { electrical: true, pwmFrequencyHz: 50, pulseRangeUs: [500, 2500] },
  }),

  def({
    id: 'servo-motor-mg996r',
    name: 'MG996R metal-gear servo',
    category: 'motor',
    description:
      'Standard-size metal-gear servo, 4.8–7.2 V, up to ~2.5 A stall. Requires a dedicated supply — an MCU board regulator cannot feed it.',
    voltage: 6,
    minVoltage: 4.8,
    maxVoltage: 7.2,
    currentRequirements: { typicalMa: 170, maxMa: 2500, note: 'Stall current; use a 3 A capable supply and 1000 µF bulk capacitance.' },
    motorRequirements: {
      motorType: 'servo',
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 4.8,
      supplyVoltageMax: 7.2,
      stallCurrentMa: 2500,
      holdingTorqueKgCm: 11,
      controlSignal: 'pwm',
    },
    pins: [
      pin('SIGNAL', 'pwm', 'input', { required: true, signal: '50 Hz position PWM', aliases: ['S', 'SIG', 'PWM', 'ORANGE'] }),
      pin('VCC', 'power', 'power', { required: true, voltage: 6, aliases: ['+', 'RED'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['-', 'BROWN', 'BLACK'] }),
    ],
    libraryRequirements: [{ name: 'Servo', import: 'Servo.h', manager: 'arduino', purpose: 'Servo PWM', builtIn: true }],
    keywords: ['servo', 'mg996r', 'metal gear', 'high torque'],
    aliases: ['mg996r', 'metal gear servo', 'high torque servo'],
    simulator: { part: 'wokwi-servo', supported: true, notes: 'Simulated as a generic servo; current draw is not modelled.' },
    metadata: { electrical: true, pwmFrequencyHz: 50, pulseRangeUs: [500, 2500], requiresBulkCapacitor: true },
  }),

  def({
    id: 'stepper-28byj48-uln2003',
    name: '28BYJ-48 stepper with ULN2003 driver board',
    category: 'motor',
    description:
      '5 V unipolar stepper (64 steps/revolution) geared 64:1, supplied with a ULN2003A Darlington driver board. Driven by sequencing four logic inputs; ~2048 half-steps per output revolution.',
    voltage: 5,
    minVoltage: 5,
    maxVoltage: 12,
    currentRequirements: { typicalMa: 200, maxMa: 550, note: 'Two phases energised at a time on the 5 V variant.' },
    motorRequirements: {
      motorType: 'stepper',
      channels: 4,
      requiresDriver: true,
      requiresExternalSupply: true,
      supplyVoltageMin: 5,
      supplyVoltageMax: 12,
      stepsPerRevolution: 2048,
      controlSignal: 'step_dir',
      rpm: 15,
    },
    pins: [
      pin('IN1', 'digital', 'input', { required: true, signal: 'Phase A', aliases: ['A'] }),
      pin('IN2', 'digital', 'input', { required: true, signal: 'Phase B', aliases: ['B'] }),
      pin('IN3', 'digital', 'input', { required: true, signal: 'Phase C', aliases: ['C'] }),
      pin('IN4', 'digital', 'input', { required: true, signal: 'Phase D', aliases: ['D'] }),
      pin('VCC', 'power', 'power', { required: true, voltage: 5, aliases: ['+', '5V', 'V+'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['-', 'V-'] }),
    ],
    libraryRequirements: [
      { name: 'Stepper', import: 'Stepper.h', manager: 'arduino', purpose: 'Built-in 4-phase stepper sequencing', builtIn: true },
      { name: 'AccelStepper', import: 'AccelStepper.h', manager: 'arduino', purpose: 'Acceleration profiles for smoother motion', builtIn: false },
    ],
    keywords: ['stepper', '28byj48', 'uln2003', 'unipolar', 'geared'],
    aliases: ['stepper motor', '28byj-48', '28byj48', 'uln2003 stepper', 'unipolar stepper'],
    simulator: { supported: false, notes: 'No verified simulator part; represent as four digital loads if needed.' },
    metadata: { electrical: true, halfStepSequence: true, driverIntegrated: 'ULN2003A' },
  }),

  def({
    id: 'stepper-motor-nema17',
    name: 'NEMA 17 bipolar stepper motor',
    category: 'motor',
    description:
      '1.8°/step (200 steps per revolution) bipolar hybrid stepper, 4 wires (2 coils). Requires a chopper driver such as the A4988; coil current typically 1–2 A so it cannot be driven from logic pins.',
    voltage: 12,
    minVoltage: 8,
    maxVoltage: 24,
    currentRequirements: { typicalMa: 1500, maxMa: 2000, note: 'Per-coil rated current; set via the driver VREF trimmer.' },
    motorRequirements: {
      motorType: 'stepper',
      channels: 2,
      requiresDriver: true,
      requiresExternalSupply: true,
      supplyVoltageMin: 8,
      supplyVoltageMax: 24,
      stepsPerRevolution: 200,
      controlSignal: 'step_dir',
      holdingTorqueKgCm: 4,
    },
    pins: [
      pin('COIL_A1', 'motor', 'input', { required: true, aliases: ['A+', '1A', 'BLACK'] }),
      pin('COIL_A2', 'motor', 'input', { required: true, aliases: ['A-', '1B', 'GREEN'] }),
      pin('COIL_B1', 'motor', 'input', { required: true, aliases: ['B+', '2A', 'RED'] }),
      pin('COIL_B2', 'motor', 'input', { required: true, aliases: ['B-', '2B', 'BLUE'] }),
    ],
    incompatibleComponents: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    libraryRequirements: [
      { name: 'AccelStepper', import: 'AccelStepper.h', manager: 'arduino', purpose: 'Step/dir control with acceleration', builtIn: false },
    ],
    keywords: ['stepper', 'nema17', 'bipolar', 'cnc', '3d printer'],
    aliases: ['nema 17', 'nema17', 'bipolar stepper', '17hs4401'],
    simulator: { supported: false, notes: 'Not available in common simulators.' },
    metadata: { electrical: true, incompatibleReason: 'Requires a chopper driver (A4988/DRV8825) between MCU and motor coils.' },
  }),

  def({
    id: 'l298n-motor-driver',
    name: 'L298N dual H-bridge motor driver',
    category: 'motor_driver',
    description:
      'Dual full-bridge driver module (up to 2 A continuous per channel, 3 A peak). Motor supply 5–35 V on the screw terminal; on-board 78M05 regulator feeds the logic when the supply is above ~7 V. Two logic pins per channel set direction, ENA/ENB accept PWM for speed. Expect a ~1.8–2.5 V saturation drop, so motors see supply minus that drop.',
    voltage: 5,
    minVoltage: 5,
    maxVoltage: 35,
    currentRequirements: { typicalMa: 500, maxMa: 3000, note: 'Per-channel continuous 2 A, peak 3 A; quiescent logic current is small.' },
    motorRequirements: {
      motorType: 'dc',
      channels: 2,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 5,
      supplyVoltageMax: 35,
      maxCurrentPerChannelMa: 2000,
      controlSignal: 'digital',
      logicVoltage: 5,
    },
    pins: [
      pin('IN1', 'digital', 'input', { required: true, signal: 'Channel A direction bit 0', aliases: ['INA1', 'A_IN1'] }),
      pin('IN2', 'digital', 'input', { required: true, signal: 'Channel A direction bit 1', aliases: ['INA2', 'A_IN2'] }),
      pin('IN3', 'digital', 'input', { required: true, signal: 'Channel B direction bit 0', aliases: ['INB1', 'B_IN1'] }),
      pin('IN4', 'digital', 'input', { required: true, signal: 'Channel B direction bit 1', aliases: ['INB2', 'B_IN2'] }),
      pin('ENA', 'enable', 'input', { required: false, signal: 'Channel A speed PWM (jumper pulled HIGH by default)', aliases: ['EN_A', 'PWMA'] }),
      pin('ENB', 'enable', 'input', { required: false, signal: 'Channel B speed PWM (jumper pulled HIGH by default)', aliases: ['EN_B', 'PWMB'] }),
      pin('OUT1', 'motor', 'output', { required: true, signal: 'Channel A output +', aliases: ['OA1', 'MOTOR_A+'] }),
      pin('OUT2', 'motor', 'output', { required: true, signal: 'Channel A output -', aliases: ['OA2', 'MOTOR_A-'] }),
      pin('OUT3', 'motor', 'output', { required: true, signal: 'Channel B output +', aliases: ['OB1', 'MOTOR_B+'] }),
      pin('OUT4', 'motor', 'output', { required: true, signal: 'Channel B output -', aliases: ['OB2', 'MOTOR_B-'] }),
      pin('+12V', 'power', 'power', { required: true, voltage: 12, signal: 'Motor supply input (5–35 V)', aliases: ['VMOT', 'VS', 'VCC_MOTOR', 'POWER'] }),
      pin('GND', 'ground', 'ground', { required: true, signal: 'Common ground — must be tied to the MCU ground', aliases: ['VSS', 'COM'] }),
      pin('5V', 'power', 'power', { required: false, voltage: 5, signal: 'Regulated 5 V out (supply > 7 V) or logic supply in (supply <= 7 V)', aliases: ['VCC', 'LOGIC_5V'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['l298n', 'motor driver', 'h-bridge', 'hbridge', 'dual', 'dc motor driver'],
    aliases: ['l298n', 'l298', 'l298d', 'dual h-bridge', 'h bridge module'],
    exampleUsage: ['Two DC motors of an RC car', 'Bipolar stepper (uses IN1–IN4 as phase drive)'],
    simulator: { supported: false, notes: 'No verified simulator part; model the two channels as PWM sources into motor loads.' },
    metadata: {
      electrical: true,
      saturationDropV: 2.0,
      onboardRegulator: '78M05',
      regulatorInputThresholdV: 7,
      enableJumpersRemoveForPwm: true,
      heatSinkRequired: 'Recommended above ~1 A per channel',
      channelMap: [
        { channel: 'A', inputs: ['IN1', 'IN2'], enable: 'ENA', outputs: ['OUT1', 'OUT2'] },
        { channel: 'B', inputs: ['IN3', 'IN4'], enable: 'ENB', outputs: ['OUT3', 'OUT4'] },
      ],
    },
  }),

  def({
    id: 'l293d-motor-driver',
    name: 'L293D quad half-bridge driver',
    category: 'motor_driver',
    description:
      'DIP-16 driver with internal clamp diodes: two full bridges (600 mA continuous, 1.2 A peak per channel) or four half-bridges. Separate logic (VCC1, 4.5–7 V) and motor (VCC2, 4.5–36 V) supplies, and four ground pins that must all be tied together.',
    voltage: 5,
    minVoltage: 4.5,
    maxVoltage: 36,
    currentRequirements: { typicalMa: 300, maxMa: 1200, note: '600 mA continuous per channel, 1.2 A non-repetitive peak.' },
    motorRequirements: {
      motorType: 'dc',
      channels: 2,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 4.5,
      supplyVoltageMax: 36,
      maxCurrentPerChannelMa: 600,
      controlSignal: 'digital',
      logicVoltage: 5,
    },
    pins: [
      pin('EN1_2', 'enable', 'input', { required: true, signal: 'Enable for channel 1 (pin 1)', aliases: ['EN1', 'ENABLE1_2', 'ENA'] }),
      pin('IN1', 'digital', 'input', { required: true, signal: 'Input 1 (pin 2)', aliases: ['1A', 'A1'] }),
      pin('OUT1', 'motor', 'output', { required: true, signal: 'Output 1 (pin 3)', aliases: ['1Y', 'Y1'] }),
      pin('GND4', 'ground', 'ground', { required: true, signal: 'Ground (pin 4)', aliases: ['GND'] }),
      pin('GND5', 'ground', 'ground', { required: true, signal: 'Ground (pin 5)', aliases: ['GND'] }),
      pin('OUT2', 'motor', 'output', { required: true, signal: 'Output 2 (pin 6)', aliases: ['2Y', 'Y2'] }),
      pin('IN2', 'digital', 'input', { required: true, signal: 'Input 2 (pin 7)', aliases: ['2A', 'A2'] }),
      pin('VCC2', 'power', 'power', { required: true, voltage: 6, signal: 'Motor supply 4.5–36 V (pin 8)', aliases: ['VM', 'VMOTOR'] }),
      pin('EN3_4', 'enable', 'input', { required: true, signal: 'Enable for channel 2 (pin 9)', aliases: ['EN2', 'ENABLE3_4', 'ENB'] }),
      pin('IN3', 'digital', 'input', { required: true, signal: 'Input 3 (pin 10)', aliases: ['3A', 'B1'] }),
      pin('OUT3', 'motor', 'output', { required: true, signal: 'Output 3 (pin 11)', aliases: ['3Y'] }),
      pin('GND12', 'ground', 'ground', { required: true, signal: 'Ground (pin 12)', aliases: ['GND'] }),
      pin('GND13', 'ground', 'ground', { required: true, signal: 'Ground (pin 13)', aliases: ['GND'] }),
      pin('OUT4', 'motor', 'output', { required: true, signal: 'Output 4 (pin 14)', aliases: ['4Y'] }),
      pin('IN4', 'digital', 'input', { required: true, signal: 'Input 4 (pin 15)', aliases: ['4A', 'B2'] }),
      pin('VCC1', 'power', 'power', { required: true, voltage: 5, signal: 'Logic supply 4.5–7 V (pin 16)', aliases: ['VCC', 'VLOGIC'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['l293d', 'l293', 'motor driver', 'h-bridge', 'quad half bridge'],
    aliases: ['l293d', 'l293', 'l293d ic'],
    simulator: { supported: false, notes: 'No verified simulator part.' },
    metadata: {
      electrical: true,
      package: 'DIP-16',
      internalClampDiodes: true,
      channelMap: [
        { channel: 'A', inputs: ['IN1', 'IN2'], enable: 'EN1_2', outputs: ['OUT1', 'OUT2'] },
        { channel: 'B', inputs: ['IN3', 'IN4'], enable: 'EN3_4', outputs: ['OUT3', 'OUT4'] },
      ],
    },
  }),

  def({
    id: 'tb6612fng-motor-driver',
    name: 'TB6612FNG dual motor driver breakout',
    category: 'motor_driver',
    description:
      'MOSFET dual H-bridge breakout: 1.2 A continuous (3.2 A peak) per channel, motor supply 2.5–13.5 V, logic 2.7–5.5 V. Much lower voltage drop than the L298N so motors get nearly the full supply. STBY must be pulled high for any output.',
    voltage: 3.3,
    minVoltage: 2.7,
    maxVoltage: 5.5,
    currentRequirements: { typicalMa: 400, maxMa: 3200, note: '1.2 A continuous per channel, 3.2 A peak.' },
    motorRequirements: {
      motorType: 'dc',
      channels: 2,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 2.5,
      supplyVoltageMax: 13.5,
      maxCurrentPerChannelMa: 1200,
      controlSignal: 'pwm',
      logicVoltage: 3.3,
    },
    pins: [
      pin('VM', 'power', 'power', { required: true, voltage: 7.4, signal: 'Motor supply 2.5–13.5 V', aliases: ['VMOT', 'VCC_MOTOR'] }),
      pin('VCC', 'power', 'power', { required: true, voltage: 3.3, signal: 'Logic supply 2.7–5.5 V', aliases: ['VLOGIC', 'VDD'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['VSS'] }),
      pin('STBY', 'enable', 'input', { required: true, signal: 'Standby — drive HIGH to enable outputs', aliases: ['STBY', 'ENABLE'] }),
      pin('AIN1', 'digital', 'input', { required: true, signal: 'Channel A direction bit 0', aliases: ['A_IN1', 'IN1'] }),
      pin('AIN2', 'digital', 'input', { required: true, signal: 'Channel A direction bit 1', aliases: ['A_IN2', 'IN2'] }),
      pin('PWMA', 'pwm', 'input', { required: true, signal: 'Channel A speed PWM', aliases: ['ENA', 'A_PWM'] }),
      pin('AO1', 'motor', 'output', { required: true, signal: 'Channel A output +', aliases: ['A01', 'MOTOR_A+'] }),
      pin('AO2', 'motor', 'output', { required: true, signal: 'Channel A output -', aliases: ['A02', 'MOTOR_A-'] }),
      pin('BIN1', 'digital', 'input', { required: true, signal: 'Channel B direction bit 0', aliases: ['B_IN1', 'IN3'] }),
      pin('BIN2', 'digital', 'input', { required: true, signal: 'Channel B direction bit 1', aliases: ['B_IN2', 'IN4'] }),
      pin('PWMB', 'pwm', 'input', { required: true, signal: 'Channel B speed PWM', aliases: ['ENB', 'B_PWM'] }),
      pin('BO1', 'motor', 'output', { required: true, signal: 'Channel B output +', aliases: ['B01', 'MOTOR_B+'] }),
      pin('BO2', 'motor', 'output', { required: true, signal: 'Channel B output -', aliases: ['B02', 'MOTOR_B-'] }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['tb6612', 'tb6612fng', 'motor driver', 'dual', 'mosfet', 'low drop'],
    aliases: ['tb6612', 'tb6612fng', 'tb6612fng breakout'],
    simulator: { supported: false, notes: 'No verified simulator part.' },
    metadata: {
      electrical: true,
      saturationDropV: 0.1,
      standbyPinRequired: true,
      channelMap: [
        { channel: 'A', inputs: ['AIN1', 'AIN2'], enable: 'PWMA', outputs: ['AO1', 'AO2'] },
        { channel: 'B', inputs: ['BIN1', 'BIN2'], enable: 'PWMB', outputs: ['BO1', 'BO2'] },
      ],
    },
  }),

  def({
    id: 'a4988-stepper-driver',
    name: 'A4988 stepper driver breakout',
    category: 'motor_driver',
    description:
      'Microstepping chopper driver for bipolar steppers: STEP + DIR interface, 1/1 to 1/16 microstepping, motor supply 8–35 V, logic 3–5.5 V, up to 2 A per coil with a heat sink (≈1 A without). Requires a bulk capacitor across VMOT/GND and VREF trimming for coil current.',
    voltage: 3.3,
    minVoltage: 3,
    maxVoltage: 5.5,
    currentRequirements: { typicalMa: 1000, maxMa: 2000, note: 'Per-coil current set by VREF: I = VREF / (8 x Rsense).' },
    motorRequirements: {
      motorType: 'stepper',
      channels: 1,
      requiresDriver: false,
      requiresExternalSupply: true,
      supplyVoltageMin: 8,
      supplyVoltageMax: 35,
      maxCurrentPerChannelMa: 2000,
      controlSignal: 'step_dir',
      logicVoltage: 3.3,
    },
    pins: [
      pin('VMOT', 'power', 'power', { required: true, voltage: 12, signal: 'Motor supply 8–35 V', aliases: ['VM', 'VCC_MOTOR'] }),
      pin('GND_MOT', 'ground', 'ground', { required: true, aliases: ['GNDMOT', 'GND'] }),
      pin('1B', 'motor', 'output', { required: true, signal: 'Coil A output -', aliases: ['B1'] }),
      pin('1A', 'motor', 'output', { required: true, signal: 'Coil A output +', aliases: ['A1'] }),
      pin('2A', 'motor', 'output', { required: true, signal: 'Coil B output +', aliases: ['A2'] }),
      pin('2B', 'motor', 'output', { required: true, signal: 'Coil B output -', aliases: ['B2'] }),
      pin('VDD', 'power', 'power', { required: true, voltage: 5, signal: 'Logic supply 3–5.5 V', aliases: ['VCC'] }),
      pin('GND', 'ground', 'ground', { required: true, aliases: ['GND_LOGIC'] }),
      pin('STP', 'digital', 'input', { required: true, signal: 'Step pulse', aliases: ['STEP'] }),
      pin('DIR', 'digital', 'input', { required: true, signal: 'Direction' }),
      pin('EN', 'enable', 'input', { required: false, signal: 'Enable (active low)', aliases: ['ENABLE'] }),
      pin('MS1', 'digital', 'input', { required: false, signal: 'Microstepping select 1' }),
      pin('MS2', 'digital', 'input', { required: false, signal: 'Microstepping select 2' }),
      pin('MS3', 'digital', 'input', { required: false, signal: 'Microstepping select 3' }),
      pin('RST', 'control', 'input', { required: false, signal: 'Reset (active low) — usually jumpered to SLP' }),
      pin('SLP', 'control', 'input', { required: false, signal: 'Sleep (active low) — usually jumpered to RST' }),
    ],
    compatibleMicrocontrollers: ['esp32-devkit-v1', 'arduino-uno-r3', 'arduino-nano'],
    keywords: ['a4988', 'stepper driver', 'microstepping', 'step dir', 'pololu'],
    aliases: ['a4988', 'pololu a4988', 'stepstick'],
    simulator: { supported: false, notes: 'No verified simulator part.' },
    metadata: { electrical: true, requiresBulkCapacitor: true, vrefFormula: 'Imax = VREF / (8 x Rsense)', microstepping: [1, 2, 4, 8, 16] },
  }),
];
